- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/namespace.py
I have sometimes seen misuse of a keyword argument `options`  in read_xxx/to_xxx functions. E.g.,
```py
kdf = ks.read_csv(..., options={ ... })
```
In this case, the argument `options` is actually `{'options': { ... }}`, which is not what the user wants to do.
We can help those cases by getting the `'options'` value.
> Help misuse of options argument.

- databricks/koalas/base.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
This is a follow-up of #1399.
When performing mod/rmod, if the operands are series from different dataframes, we needed three joins.
```py
>>> kser = ks.Series([100, None, -300, None, 500, -700], name="Koalas")
>>> (kser % ks.Series([150] * 6)).to_frame().explain()
*(9) Project [CASE WHEN isnotnull(__index_level_0__#317L) THEN __index_level_0__#317L ELSE __index_level_0__#228L END AS __index_level_0__#378L, (Koalas#364 % cast(0#229L as double)) AS Koalas#425]
+- SortMergeJoin [__index_level_0__#317L], [__index_level_0__#228L], FullOuter
:- *(7) Sort [__index_level_0__#317L ASC NULLS FIRST], false, 0
:  +- Exchange hashpartitioning(__index_level_0__#317L, 200)
:     +- *(6) Project [CASE WHEN isnotnull(__index_level_0__#254L) THEN __index_level_0__#254L ELSE …
```
> Reduce the number of joins for mod/rmod.

- .github/workflows/master.yml
- README.md
- databricks/koalas/__init__.py
- databricks/koalas/utils.py
- requirements-dev.txt
- setup.py
This PR adds PyArrow 0.15 support back with a better documentation and error message.
Error message will look as below:
Warning when pyarrow>=0.15 and pyspark<3.0 but `ARROW_PRE_0_15_IPC_FORMAT` not set.
```
WARNING:root:'ARROW_PRE_0_15_IPC_FORMAT' environment variable was not set. It is required 
to set this environment variable to '1' if you use pyarrow>=0.15 and pyspark<3.0. Koalas will 
set it for you but it does not work if there is a Spark context already launched.
```
Exceptions when `ARROW_PRE_0_15_IPC_FORMAT` is set in valid cases:
```
RuntimeError: Please explicitly unset 'ARROW_PRE_0_15_IPC_FORMAT' environment variable 
in both driver and executor sides. Check your spark.executorEnv.*, spark.yarn.appMasterEnv.*, 
spark.mesos.driverEnv.* and spark.kubernetes.driverEnv.* …
```
> Add PyArrow 0.15 support back, and test PyArrow 0.16 in CI

- README.md
Seems like just using a `conda` command may break MLR environment.
We should add a note to install Koalas on MLR properly.
> Add a note for Databricks Runtime for Machine Learning 6.0 and above.

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_internal.py
When the input pandas DataFrame has the same index name as a column name, `ks.from_pandas()` fails with the following error:
```py
>>> pdf = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
>>> pdf.index.name = "a"
>>> pdf
a  b
a
0  1  4
1  2  5
2  3  6
>>> kdf = ks.from_pandas(pdf)
...
ValueError: cannot insert a, already exists
```
Resolves #1361, Closes #1375.
> Fix from_pandas to handle the same index name as a column name.

- docs/source/user_guide/best_practices.rst
Resolves https://github.com/databricks/koalas/issues/1414
I have added a preemptive guide to non-Koalas APIs to `best practeces`.
Please check.
> Add documentation about non-Koalas APIs

- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
Resolves #1422 
Adding a dummy keyword argument `deep` which is doing nothing for `DataFrame.copy()`, since we doesn't support keyword `deep` for the `DataFrame.copy()`.
> Hot-fixing the lack of keyword argument 'deep' for DataFrame.copy()

- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
Adding `unique` function to `SeriesGroupBy`.
E.g.,
```py
>>> df = ks.DataFrame({'a': [1, 1, 1, 2, 2, 2, 3, 3, 3],
...                    'b': [1, 2, 2, 2, 3, 3, 3, 4, 4]}, columns=['a', 'b'])
>>> df.groupby(['a'])['b'].unique().sort_index()  # doctest: +SKIP
a
1    [1, 2]
2    [2, 3]
3    [3, 4]
Name: b, dtype: object
```
Resolves #875.
> Add unique function to SeriesGroupBy.

- databricks/koalas/strings.py
- databricks/koalas/tests/test_series_string.py
Adding `expand` parameter support if `n` is a positive integer in `Series.str.split`/`rsplit` with a couple of restrictions that:
- `n` parameter must be a positive integer
- the number of columns will always be `n + 1`.
E.g.,
```py
>>> kser = ks.Series(['A_1', 'A_2', 'A_3', 'A_4', 'A_5'])
>>> kser
0    A_1
1    A_2
2    A_3
3    A_4
4    A_5
>>> kser.str.split('_', n=1, expand=True)
0  1
0  A  1
1  A  2
2  A  3
3  A  4
4  A  5
>>> kser.str.split('_', n=2, expand=True)
0  1     2
0  A  1  None
1  A  2  None
2  A  3  None
3  A  4  None
4  A  5  None
```
The last example is different from pandas'.
```py
>>> kser.to_pandas().str.split('_', n=2, expand=True)
0  1
0  A  1
1  A  2
2  A  3
3  A  4
4  A  5
```
Resolves #1421.
> Support expand parameter if n is a positive integer in Series.str.split/rsplit.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/typedef.py
Making `Series.astype(bool)` follow the concept of "truthy" and "falsey".
```py
>>> kser = ks.Series(["hi", "hi ", " ", " \t", "", None], name="x")
>>> kser
0      hi
1     hi
2
3      \t
4
5    None
Name: x, dtype: object
>>> kser.astype(bool)
0     True
1     True
2     True
3     True
4    False
5    False
Name: x, dtype: bool
>>> kser.str.strip().astype(bool)
0     True
1     True
2    False
3    False
4    False
5    False
Name: x, dtype: bool
```
Resolves #1430.
> Make Series.astype(bool) follow the concept of "truthy" and "falsey".

- databricks/koalas/base.py
- databricks/koalas/tests/test_series.py
Resolves #1428 
```python
>>> pser = pd.Series([-100, 0, 100, None, np.nan], name="Koalas")
>>> kser = ks.from_pandas(pser)
>>> pser // np.nan
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Koalas, dtype: float64
>>> kser // np.nan                                                                                                                
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Koalas, dtype: float64
```
> Fix incompatible behaviour with pandas for floordiv with np.nan

- databricks/koalas/indexing.py
Refactoring indexers to separate `_select_rows` and `_select_cols` into small methods.
> Separate _select_rows and _select_cols into small methods.

- dev/reformat
After this PR, `dev/reformat` script is not affected by the current working directory.
> Make reformat script working directory free

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/series.py
- databricks/koalas/typedef.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
- docs/source/reference/indexing.rst
- docs/source/reference/series.rst
This PR is exposing `spark_column` property representing the Series/Index for users who are familiar with Spark functions to make it easier to work with them.
E.g.:
```py
>>> kdf = ks.DataFrame({'a': [1.0, 1.0, 1.0, 2.0, 2.0, 2.0], 'b': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})
>>> from pyspark.sql import functions as F
>>> kdf['greatest'] = F.greatest(kdf.a.spark_column, kdf.b.spark_column)
>>> kdf['least'] = F.least(kdf.a.spark_column, kdf.b.spark_column)
>>> kdf
a    b  greatest  least
0  1.0  1.0       1.0    1.0
1  1.0  2.0       2.0    1.0
2  1.0  3.0       3.0    1.0
3  2.0  4.0       4.0    2.0
4  2.0  5.0       5.0    2.0
5  2.0  6.0       6.0    2.0
```
> Expose spark_column from Series/Index to make it easier to work with Spark Columns.

- databricks/koalas/base.py
- databricks/koalas/tests/test_series_datetime.py
Since currently we don't support `timedelta` type in pandas, we haven't support subtraction of dates, but we already have a workaround for subtraction of timestamps returning long instead of `timedelta`. We can also support subtraction of dates returning int.
We should revisit after we support `timedelta` type.
> Use F.datediff() for subtraction of dates as a workaround.

- databricks/koalas/base.py
- databricks/koalas/datetimes.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/strings.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/typedef/__init__.py
- databricks/koalas/typedef/string_typehints.py
- databricks/koalas/typedef/typehints.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
This PR adds:
- `DataFrame.transform_batch()` (previously `pandas_wraps`)
- `Series.transform_batch()` (previously `pandas_wraps`)
- `DataFrame.apply_batch()` (previously `DataFrame.map_in_pandas`)
also deprecates:
- `ks.pandas_wraps` (now `DataFrame.transform_batch` and `Series.transform_batch`)
- `DataFrame.map_in_pandas` (now `DataFrame.apply_batch()`)
In addition, this PR adds a support of type inference for string literal type hint expressions. It's a bit hacky but works. (see `string_literal_typehints.py`).
<br/>
For `pandas_wraps`, the codes can be converted as below:
Before:
```python
kdf = ks.DataFrame({'a': [1,2,3], 'b':[4,5,6]})
@ks.pandas_wraps
def pandas_plus_one(col1, col2) -> ks.Series[int]:
return col1 + col2
pandas_plus_one(kdf.a, kdf.b)
``` …
> Add (DataFrame|Series).transform_batch and DataFrame.apply_batch

- setup.py
Read the docs build seems being failed :
```
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/latest/lib/python3.6/site-packages/sphinx/config.py", line 319, in eval_config_file
execfile_(filename, namespace)
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/latest/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
exec(code, _globals)
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/checkouts/latest/docs/source/conf.py", line 19, in <module>
from databricks import koalas
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/latest/lib/python3.6/site-packages/databricks/koalas/__init__.py", line 73, in <module>
from databricks.koalas.frame import DataFrame
File …
```
> Add new package 'typedef' into setup.py

- databricks/koalas/frame.py
- docs/source/reference/frame.rst
Add `spark_schema` and `print_schema` to see the underlying Spark schema since `dtypes` are sometimes ambiguous.
> Add spark_schema and print_schema.

- databricks/koalas/typedef/typehints.py
`dtype` for `DateType` should be `np.dtype("object")`.
```py
>>> import datetime
>>> pdf = pd.DataFrame({'dt': [datetime.date(2020,1,1),datetime.date(2020,1,2)], 'ts':[datetime.datetime(2020,1,1,0,0,0), datetime.datetime(2020,1,2,0,0,0)]})
>>> pdf.dtypes
dt            object
ts    datetime64[ns]
dtype: object
```
whereas:
```py
>>> ks.from_pandas(pdf).dtypes
dt    datetime64[ns]
ts    datetime64[ns]
dtype: object
```
> dtype for DateType should be np.dtype("object").

- setup.py
Koalas currently can't support because Spark 2.x does not support Python 3.8. Python 3.8 is supported from Spark 3.
> Specify upperbound for Python version in setup.py

- requirements-dev.txt
The build environment for `Conda (Python, Spark, pandas, PyArrow) (3.7, 2.4.5, 1.0.3, 0.15.1)` has been broken due to conda installation issue that `pinned spec pyarrow==0.15.1 conflicts with explicit specs.  Overriding pinned spec.` and conda downgrades to `0.11.1`.
```
The following packages will be SUPERSEDED by a higher-priority channel:
arrow-cpp          pkgs/main::arrow-cpp-0.15.1-py37h7cd5~ --> conda-forge::arrow-cpp-0.11.1-py37h3bd774a_1
libprotobuf        pkgs/main::libprotobuf-3.11.2-hd40887~ --> conda-forge::libprotobuf-3.8.0-h8b12597_0
pyarrow            pkgs/main::pyarrow-0.15.1-py37h0573a6~ --> conda-forge::pyarrow-0.11.1-py37hbbcf98d_1002
```
I'm not 100% sure about the root cause, but seems like upper bound for `libprotobuf` we added at #824 causes the issue. Maybe the …
> Remove upper bound for libprotobuf.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
We need to manage the name in the result Series only when it's from a `SeriesGroupBy`.
```py
>>> pdf = pd.DataFrame({"A": [1, 2, 2, 3, 3, 3], "B": [1, 1, 2, 3, 3, 3]})
>>> pdf.groupby("A").size()
A
1    1
2    2
3    3
dtype: int64
>>> pdf.groupby("A")["B"].size()
A
1    1
2    2
3    3
Name: B, dtype: int64
>>> pdf.groupby("A")[["B"]].size()
A
1    1
2    2
3    3
dtype: int64
```
> Remove an unnecessary instance variable.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
pandas' `DataFrame.reset_index()` raises an error if the index name is the same as one of columns but allow it when `drop=True`.
```py
>>> pdf = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]}, index=np.random.rand(3))
>>> pdf.index.name = "a"
>>> pdf.reset_index()
...
ValueError: cannot insert a, already exists
>>> pdf.reset_index(drop=True)
a  b
0  1  4
1  2  5
2  3  6
```
whereas Koalas raises another error for both cases:
```py
>>> ks.from_pandas(pdf).reset_index()
...
pyspark.sql.utils.AnalysisException: "Reference 'a' is ambiguous, could be: a, a.;"
>>> ks.from_pandas(pdf).reset_index(drop=True)
...
pyspark.sql.utils.AnalysisException: "Reference 'a' is ambiguous, could …
```
> Make reset_index disallow the same name but allow it when drop=True.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
This PR takes over #1000.
Closes #1000
> Fix named aggregation for MultiIndex

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
When `as_index=False`, the behavior of groupby for statistic functions like `sum`, `min`, `max`, etc. and `aggregate` function is not the same as pandas'.
```py
>>> pdf = pd.DataFrame({"a": [1, 2, 6, 4, 4, 6, 4, 3, 7], "b": [4, 2, 7, 3, 3, 1, 1, 1, 2]}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> pdf.groupby(pdf.b, as_index=False).sum()
b   a
0  1  13
1  2   9
2  3   8
3  4   1
4  7   6
>>> pdf.groupby(pdf.b + 1, as_index=False).sum()
a  b
0  13  3
1   9  4
2   8  6
3   1  4
4   6  7
```
For Koalas,
```py
>>> kdf.groupby(kdf.b, as_index=False).sum().sort_values('b')
b   a
1  1  13
3  2   9
2  3   8
4  4   1
0  7   6
>>> kdf.groupby(kdf.b + 1, as_index=False).sum()
...
ValueError: cannot insert b, already exists
```
The first one is fine, but the second one …
> Fix groupby when as_index=False.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
`groupby.apply` in pandas<0.25 runs the functions twice for the first group, so if the function has a side effect, it could cause an unexpected behavior.
```py
>>> pd.__version__
'0.24.2'
>>> kdf = ks.DataFrame({"d": [1.0, 1.0, 1.0, 2.0, 2.0, 2.0], "v": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})
>>> acc = ks.utils.default_session().sparkContext.accumulator(0)
>>> def sum_with_acc_frame(x) -> ks.DataFrame[np.float64, np.float64]:
...   global acc
...   acc += 1
...   return np.sum(x)
...
>>> kdf.groupby("d").apply(sum_with_acc_frame)
c0    c1
0  3.0   6.0
1  6.0  15.0
>>> acc.value
4
```
whereas:
```py
>>> pd.__version__
'0.25.3'
...
>>> acc.value
2
```
The `acc.value` should be `2` since there are only 2 groups and the function should be called twice.
> Make groupby.apply in pandas<0.25 run the function only once per group.

- databricks/koalas/generic.py
- databricks/koalas/utils.py
Extending `verify_temp_column_name` to support column labels when the `df` is Koalas DataFrame.
> Support tuple for as a temp column label in verify_temp_column_name.

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/utils.py
Fixing `Series.groupby` on the Series from different DataFrames.
```py
>>> kdf1 = ks.DataFrame({"C": [0.362, 0.227, 1.267, -0.562], "B": [1, 2, 3, 4]})
>>> kdf2 = ks.DataFrame({"A": [1, 1, 2, 2]})
>>> kdf1.B.groupby(kdf2.A).sum()
...
pyspark.sql.utils.AnalysisException: 'Resolved attribute(s) __tmp_groupkey_0__#118L missing from ...\n'
```
> Fix Series.groupby on the Series from different DataFrames.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fixing groupby functions using `GroupBy._apply_series_op`, such as `cumxxx`, `diff`, `shift`, etc to use the original group keys since `Series` doesn't know the modified group keys in `SeriesGroupBy`, otherwise it doesn't follow the actual group keys.
```py
>>> kdf
a  b   c
0  1  1   1
1  2  1   4
2  3  2   9
3  4  3  16
4  5  5  25
5  6  8  36
>>> kdf.groupby((kdf.b // 5).rename('b')).cumsum().sort_index()
a  b   c
0  1  1   1
1  3  2   5
2  3  2   9
3  4  3  16
4  5  5  25
5  6  8  36
```
```py
>>> pdf.groupby((pdf.b // 5).rename('b')).cumsum().sort_index()
a   b   c
0   1   1   1
1   3   2   5
2   6   4  14
3  10   7  30
4   5   5  25
5  11  13  61
```
Or even raises …
> Fix functions using GroupBy._apply_series_op.

- docs/source/user_guide/options.rst
This PR adds an explicit warning when `distributed` default index type and 'compute.ops_on_diff_frames' are used together.
> More explicitly warn about distributed index type and 'compute.ops_on_diff_frames'

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_reshape.py
Resolves #1469 
```python
>>> df = ks.DataFrame({'A': ['a', 'b', 'a'], 'B': ['b', 'a', 'c'], 'C': [1, 2, 3]}, columns=['A', 'B', 'C'])
>>> ks.get_dummies(df, prefix={'B': 'ohe_B', 'C': 'ohe_C'}, columns=['B', 'C'])
A  ohe_B_a  ohe_B_b  ohe_B_c  ohe_C_1  ohe_C_2  ohe_C_3
0  a        0        1        0        1        0        0
1  b        1        0        0        0        1        0
2  a        0        0        1        0        0        1
>>> pd.get_dummies(df.to_pandas(), prefix={'B': 'ohe_B', 'C': 'ohe_C'}, columns=['B', 'C'])
A  ohe_B_a  ohe_B_b  ohe_B_c  ohe_C_1  ohe_C_2  ohe_C_3
0  a        0        1        0        1        0        0
1  b        1        0        0        0        1        0
2  a        0        0        1        0        0        1
```
> Fix get dummies when uses the prefix parameter whose type is dict

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fixing `GroupBy.head` to recognize `agg_columns`.
```py
>>> kdf = ks.DataFrame({"a": [1, 1, 1, 1, 2, 2, 2, 3, 3, 3] * 3, "b": [2, 3, 1, 4, 6, 9, 8, 10, 7, 5] * 3, "c": [3, 5, 2, 5, 1, 2, 6, 4, 3, 6] * 3})
>>> kdf.groupby("a")[["b"]].head(2).sort_index()
a   b  c
0  1   2  3
1  1   3  5
4  2   6  1
5  2   9  2
7  3  10  4
8  3   7  3
```
```py
>>> pdf.groupby("a")[["b"]].head(2).sort_index()
b
0   2
1   3
4   6
5   9
7  10
8   7
```
> Fix GroupBy.head to recognize agg_columns.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fixing `GroupBy.filter` to follow complex group keys.
```py
>>> kdf.groupby(kdf["b"] // 5).filter(lambda x: any(x.a == 2))
a  b  c
0  1  1  1
1  2  1  4
```
```py
>>> pdf.groupby(pdf["b"] // 5).filter(lambda x: any(x.a == 2))
a  b   c
0  1  1   1
1  2  1   4
2  3  2   9
3  4  3  16
```
> Fix GroupBy.filter to follow complex group keys.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fixing `GroupBy.transform` to follow complex group keys.
```py
>>> kdf.groupby(kdf.b // 5).transform(lambda x: x + x.min())
a   c
0   2   2
1   3   5
2   6  18
3   8  32
4  10  50
5  12  72
```
```py
>>> pdf.groupby(pdf.b // 5).transform(lambda x: x + x.min())
a   b   c
0   2   2   2
1   3   2   5
2   4   3  10
3   5   4  17
4  10  10  50
5  11  13  61
```
Also fixing handling agg_columns,
```py
>>> kdf.groupby(kdf.b)[['c']].transform(lambda x: x + x.min())
a   c
0   2   2
1   3   5
2   6  18
3   8  32
4  10  50
5  12  72
>>> pdf.groupby(pdf.b)[['c']].transform(lambda x: x + x.min())
c
0   2
1   5
2  18
3  32
4  50
5  72
```
> Fix GroupBy.transform to follow complex group keys.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fixing `GroupBy.apply` to follow complex group keys.
```py
>>> kdf.groupby(kdf.b // 5).apply(lambda x: x + x.min())
a   b   c
0   2   2   2
1   3   2   5
2   6   4  18
3   8   6  32
4  10  10  50
5  12  16  72
```
```py
>>> pdf.groupby(pdf.b // 5).apply(lambda x: x + x.min())
a   b   c
0   2   2   2
1   3   2   5
2   4   3  10
3   5   4  17
4  10  10  50
5  11  13  61
```
> Fix GroupBy.apply to follow complex group keys.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
`GroupBy.fillna` can also use `GroupBy._apply_series_op` instead of its own logic to collect Series.
> Fix GroupBy.fillna to use GroupBy._apply_series_op.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fix `GroupBy.filter` and `GroupBy.apply` to handle `agg_columns`.
```py
>>> kdf.groupby("b")[["a"]].apply(lambda x: x + x.min())
a   b   c
0   2   2   2
1   3   2   5
2   6   4  18
3   8   6  32
4  10  10  50
5  12  16  72
>>> kdf.groupby("b")[["a"]].filter(lambda x: any(x.a == 2))
a  b  c
0  1  1  1
```
These should be:
```py
>>> pdf.groupby("b")[["a"]].apply(lambda x: x + x.min())
a
0   2
1   3
2   6
3   8
4  10
5  12
>>> pdf.groupby("b")[["a"]].filter(lambda x: any(x.a == 2))
a
0  1
1  2
```
, respectively.
> Fix GroupBy.filter and apply to handle agg_columns.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This PR adds extra argument support in Koalas `DataFrame.apply` and `DataFrame.apply_batch` to match with pandas' [`DataFrame.apply`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html).
```python
ks.range(10).apply(lambda a, b, c: a + b + c, args=(1,), c=3)
```
```
id
0   4
1   5
2   6
3   7
4   8
5   9
6  10
7  11
8  12
9  13
```
```python
def func(a, b, c, d=123) -> ks.Series[int]:
return a + b + c + d
ks.range(10).apply(func, args=(1,), c=3)
```
```
id
0  127
1  128
2  129
3  130
4  131
5  132
6  133
7  134
8  135
9  136
```
> Add extra arguments support in DataFrame.apply and DataFrame.apply_batch

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
This PR adds extra arguments support in DataFrame.transform, DataFrame.transform_batch and Series.transform_batch.
For example, 
```python
>>> from databricks import koalas as ks
>>> ks.range(10).transform_batch(lambda pdf, a, b, c: pdf.id + a + b + c, 1, 2, c=3)
0     6
1     7
2     8
3     9
4    10
5    11
6    12
7    13
8    14
9    15
Name: id, dtype: int64
```
> Add extra arguments support in DataFrame.transform, DataFrame.transform_batch and Series.transform_batch

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
This PR adds the extra arguments support in `Groupby.apply` and `Groupby.transform`.
```python
kdf = ks.DataFrame(
{"a": [1, 2, 3, 4, 5, 6], "b": [1, 1, 2, 3, 5, 8], "c": [1, 4, 9, 16, 25, 36]},
columns=["a", "b", "c"])
kdf.groupby(["a", "b"]).apply(lambda x, y, z: x + x.min() + y + z, 1, z=2)
```
```
a   b   c
0   5   5   5
1   7   5  11
2   9   7  21
3  11   9  35
4  13  13  53
5  15  19  75
```
> Add extra arguments support in GroupBy.apply and GroupBy.transform

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
Adding `SeriesGroupBy.filter`.
```py
>>> df = ks.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar'], 'B' : [1, 2, 3, 4, 5, 6], 'C' : [2.0, 5., 8., 1., 2., 9.]})
>>> df.B.groupby(df.A).filter(lambda x: x.mean() > 3.)
1    2
3    4
5    6
Name: B, dtype: int64
```
> Support SeriesGroupBy.filter.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
Fixing `GroupBy.apply`, `filter`, and `head` to ignore temp columns when ops from different DataFrames, otherwise the result includes the temp columns.
```py
>>> kkey = ks.Series([1, 1, 2, 3, 5, 8])
>>> kdf.groupby(kkey).apply(lambda x: x + x.min())
a   b   c  __tmp_groupkey_0__
0   2   2   2                   2
5  12  16  72                  16
1   3   2   5                   2
3   8   6  32                   6
2   6   4  18                   4
4  10  10  50                  10
```
> Fix GroupBy apply, filter, and head to ignore temp columns when ops from different DataFrames.

- databricks/koalas/frame.py
- databricks/koalas/internal.py
We can simplify `DataFrame.columns` setter using `_InternalFrame.with_new_columns`.
> Simplify DataFrame.columns setter.

- databricks/koalas/groupby.py
- databricks/koalas/indexing.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/utils.py
Fixing `GroupBy` functions which need natural orderings, such as `head`, `cumxxx`, etc., to follow the order when opts from different DataFrames, otherwise the result will be non-deterministic because of the shuffle needed to join the group keys.
```py
>>> kdf = ks.DataFrame({"a": [1, 1, 1, 1, 2, 2, 2, 3, 3, 3] * 3, "b": [2, 3, 1, 4, 6, 9, 8, 10, 7, 5] * 3, "c": [3, 5, 2, 5, 1, 2, 6, 4, 3, 6] * 3})
>>> kkey = ks.Series([1, 1, 1, 1, 2, 2, 2, 3, 3, 3] * 3)
>>> kdf.groupby(kkey).head(2)
a  b  c
0   1  2  3
22  1  1  2
29  3  5  6
19  3  5  6
26  2  8  6
25  2  9  2
```
```py
>>> pdf.groupby(pkey).head(2)
a   b  c
0  1   2  3
1  1   3  5
4  2   6  1
5  2   9  2
7  3  10  4
8  3   7  3
```
> Fix GroupBy functions which need natural orderings to follow the order when opts from different DataFrames.

- databricks/koalas/mlflow.py
The build came to fail due to scikit-learn upgrade.
The output string seems changed since scikit-learn 0.23.0 which was just released on May 12, 2020.
```
134     >>> mlflow.set_experiment("my_experiment")
135
136     We aim at learning this numerical function using a simple linear regressor.
137
138     >>> from sklearn.linear_model import LinearRegression
139     >>> train = pd.DataFrame({"x1": np.arange(8), "x2": np.arange(8)**2,
140     ...                       "y": np.log(2 + np.arange(8))})
141     >>> train_x = train[["x1", "x2"]]
142     >>> train_y = train[["y"]]
143     >>> with mlflow.start_run():
Expected:
LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)
Got:
LinearRegression()
```
> Fix build failure due to scikit-learn upgrade.

- databricks/koalas/frame.py
Resolves https://github.com/databricks/koalas/issues/1498
I removed the `max_rows` parameter from the `DataFrame.to_markdown` function.
> Remove max_rows parameter from DataFrame.to_markdown function

- databricks/koalas/base.py
- databricks/koalas/tests/test_series.py
There is an incompatible hehaviour with pandas when divide `np.inf` by 0
```python
>>> pser
0    0.0
1    NaN
2    inf
>>> kser
0    0.0
1    NaN
2    inf
>>> pser.div(0)
0    NaN
1    NaN
2    inf
>>> kser.div(0)
0   NaN
1   NaN
2   NaN  # Have to be a `inf`
```
This PR fixed it.
> Fix Series.div when div/floordiv np.inf by zero

- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Since several APIs are missing in the docs, just added them.
> Add missing docs in series.rst & frame.rst

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
This PR proposes `Series.item`
```python
>>> kser = ks.Series([10])
>>> kser.item()
10
```
> Implement Series.item

- databricks/koalas/series.py
When users try to call the wrong name of property or function with Series,
The existing error message seems not proper like the below.
```python
>>> kser.itholic()  # 'kser' is Series of Koalas
...
AttributeError: Not a struct: LongType
```
Fixed it to:
```python
>>> kser.itholic()  # 'kser' is Series of Koalas
...
AttributeError: 'Series' object has no attribute 'itholic'
```
This way is same as pandas and other APIs (DataFrame, Index ...)
> Fix message for AttributeError properly for Series.

- databricks/koalas/frame.py
```
Warning, treated as error:
/.../koalas/databricks/koalas/frame.py:docstring of databricks.koalas.DataFrame.pop:6:Unexpected indentation.
```
Similar with https://github.com/databricks/koalas/pull/1509. For some reasons, it didn't fail before but after new more changes in the current master, it started to fail as above. We should fix the style mistakes anyway ..
> Fix documentations style in DataFrame.pop

- databricks/koalas/frame.py
This PR proposes to use `mapInPandas` which is available from Spark 3.0 at `DataFrame.apply`. I manually ran the existing tests against Apache Spark 3.0.
> Use mapInPandas in DataFrame.apply

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
According to the comment https://github.com/databricks/koalas/pull/1502#discussion_r427560507, fixed `Series.item` to run a Spark job not twice, once.
> Fix Series.item to run a Spark job once

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/utils.py
Trying to loosen anchor restriction.
When the underlying Spark DataFrame is the same and index metadata is not modified, we can work without joins.
> Loosen anchor restriction.

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
Currently `Series.clip` creates a new DataFrame, so assigning back to the anchor DataFrame can't be executed without the option "compute.ops_on_diff_frames":
```py
>>> kdf = ks.DataFrame({"a": [1, 2, 6, 4, 4, 6, 4, 3, 7]})
>>> kdf['clip'] = kdf.a.clip(3, 6)
...
ValueError: Cannot combine the series or dataframe because it comes from a different dataframe. In order to allow this operation, enable 'compute.ops_on_diff_frames' option.
```
> Fix Series.clip not to create a new DataFrame.

- databricks/koalas/generic.py
- databricks/koalas/indexes.py
- databricks/koalas/utils.py
Adding `__bool__` function explicitly to raise an error when `DataFrame`, `Series`, and `Index` are used as bool, otherwise they might be used mistakenly.
> Add __bool__ function.

- databricks/koalas/frame.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_dataframe.py
Seems like current `InternalFrame.to_external_spark_frame` is only used in `DataFraem.to_spark()` without `index_col` argument.
I think we can just remove it for now and consolidate the logic between with and without `index_col` argument.
> Remove InternalFrame.to_external_spark_frame.

- databricks/koalas/generic.py
- databricks/koalas/tests/test_dataframe.py
I don't think anyone is using `compute()` function.
> Remove compute function.

- databricks/koalas/base.py
- databricks/koalas/datetimes.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/spark.py
- databricks/koalas/strings.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_dataframe_spark_io.py
- databricks/koalas/tests/test_indexops_spark.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
- docs/source/reference/frame.rst
- docs/source/reference/indexing.rst
- docs/source/reference/series.rst
- docs/source/user_guide/best_practices.rst
This PR proposes to have `spark` namespace in `DataFrame`, `Series`, `Index` and `MultiIndex`.
Spark related features are placed under this namespace.
- `(Series|Index|MultiIndex).spark_type` -> `(Series|Index|MultiIndex).spark.data_type`
`spark_type` is deprecated
- `(Series|Index|MultiIndex).spark_column` -> `(Series|Index|MultiIndex).spark.column`
`spark_column` is deprecated
- New API `(Series|Index).transform`
```python
>>> import pyspark.sql.functions as F
>>> kss = ks.Series(["example"])
>>> kss.spark.transform(lambda s: F.trim(F.upper(s)))
0    EXAMPLE
```
I intentionally named it `transform` because it needs to have the same length.
- `DataFrame.spark_schema` -> `DataFrame.spark.schema`
`DataFrame.spark_schema` is …
> Add spark namespace in DataFrame, Series, Index and MultiIndex

- databricks/koalas/spark.py
- databricks/koalas/tests/test_frame_spark.py
- docs/source/reference/frame.rst
This PR adds `DataFrame.spark.apply`:
```python
ks.range(10).spark.apply(lambda sdf: sdf.selectExpr("id + 1"))
```
```
(id + 1)
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10
```
> Add DataFrame.spark.apply

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
Fix `Series.combine_first` to support tupled names.
```py
>>> kser1 = ks.Series({"falcon": 330.0, "eagle": 160.0})
>>> kser2 = ks.Series({"falcon": 345.0, "eagle": 200.0, "duck": 30.0})
>>> kser1.name = ("X", "A")
>>> kser2.name = ("Y", "B")
>>> kser1.combine_first(kser2)
...
pyspark.sql.utils.AnalysisException: 'Cannot resolve column name "__this_(\'X\', \'A\')" among (__index_level_0__, __this_(X, A), __that_(Y, B), __natural_order__);'
```
> Fix combine_first to support tupled names.

- databricks/koalas/base.py
Fixing `hasnans` to follow the modified column.
E.g.,
```py
>>> (ks.Series([1.0, 2.0, np.nan]) + 1).hasnans
...
pyspark.sql.utils.AnalysisException: 'Resolved attribute(s) 0#1 missing from (0 + 1)#10 in operator ...
```
> Fix hasnans to follow the modified column.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Koalas doesn't guarantee the underlying Spark DataFrame has columns named `name_like_string(column_label)`. We should always retrieve the Spark column, the column name, etc. using internal methods.
E.g.,
```py
>>> kdf = ks.DataFrame({("A", "X"): [[-1.0, np.nan], [0.0, np.inf], [1.0, -np.inf]], ("B", "Y"): 1})
>>> kdf
A  B
X  Y
0  [-1.0, nan]  1
1   [0.0, inf]  1
2  [1.0, -inf]  1
>>> kdf.A.explode("X")
...
AttributeError: 'DataFrame' object has no attribute 'explode'
```
Also added a negative test.
> Fix explode to use internal methods.

- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_indexops_spark.py
- docs/source/reference/series.rst
This PR adds `Series.spark.apply` to allow arbitrary length such as aggregation:
```python
import pyspark.sql.functions as F
kss = ks.Series([1, 2, 3, 4])
kss.spark.apply(lambda s: F.collect_list(s))
```
```
0    [1, 2, 3, 4]
```
Note that It will lose index which can result in performance degradation due to using the default index. I don't think we should encourage this API.
> Add Series.spark.apply

- databricks/koalas/groupby.py
- databricks/koalas/series.py
Use `collections.abc` instead of `collection` to suppress the following warnings:
```
/path/to/databricks/koalas/groupby.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Callable, OrderedDict, namedtuple
```
> Use collections.abc to suppress warnings.

- databricks/koalas/indexes.py
Using Spark accessor directly in `Index.spark_type` should be fine, and we can show more proper warning.
> Use spark accessor directly in Index.spark_type.

- databricks/koalas/internal.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- docs/source/reference/series.rst
`DataFrame.fillna` reuses `Series.fillna` which always runs a Spark job to check if there are null values, then it ends up with running many jobs if the DataFrame has a lot of columns.
We should avoid it, and we can check its nullability defined by Spark instead.
> Fix Series.fillna to avoid Spark jobs.

- databricks/koalas/base.py
- databricks/koalas/indexes.py
There are some places remaining using `spark_type` instead of `spark.data_type`.
> Use spark.data_type instead of spark_type.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_expanding.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby_expanding.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby_rolling.py
- databricks/koalas/tests/test_rolling.py
- databricks/koalas/window.py
Fix `Rolling` and `Expanding` to handle `agg_columns`.
E.g.,
```py
>>> kdf
a    b
0  1  4.0
1  2  2.0
2  3  3.0
3  2  1.0
>>> kdf.groupby(kdf.a)[['b']].rolling(2).sum()
a    b
a
1 0  NaN  NaN
3 2  NaN  NaN
2 1  NaN  NaN
3  4.0  3.0
```
```py
>>> pdf.groupby(pdf.a)[['b']].rolling(2).sum()
b
a
1 0  NaN
2 1  NaN
3  3.0
3 2  NaN
```
Also, it raises errors for other cases:
```py
>>> kdf.b.groupby(kdf.a).rolling(2).sum()
...
pyspark.sql.utils.AnalysisException: "cannot resolve '`a`' given input columns: ...
>>> kdf.groupby(kdf.a)['b'].rolling(2).sum()
...
pyspark.sql.utils.AnalysisException: "cannot resolve '`a`' given input columns: ...
```
> Fix RollingGroupby and ExpandingGroupby to handle agg_columns.

- .github/workflows/master.yml
Because new version of pandas (1.0.4) was released on May 28, also bumped up our test version of pandas to the latest one.
> pandas 1.0.3 -> 1.0.4 for CI

- databricks/koalas/utils.py
It was renamed at https://github.com/apache/spark/commit/68d7edf9497bea2f73707d32ab55dd8e53088e7c
> Reflect renaming of configuration spark.sql.analyzer.failAmbiguousSelfJoin

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/ml.py
- databricks/koalas/mlflow.py
- databricks/koalas/namespace.py
- databricks/koalas/plot.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/utils.py
This PR makes huge changes on the way of `InternalFrame` management to avoid creating very many Spark DataFrames.
It will make a lot of DataFrame operations without enabling "compute.ops_on_diff_frames" option possible.
```py
df + df + df
df['foo'] = df['bar']['baz']
df[['x', 'y']] = df[['x', 'y']].fillna(0)
```
The new way in functions to manage `InternalFrame` is:
- If the function only needs to handle Spark columns, e.g., functions using `InternalFrame. with_new_columns`, use the new columns without creating new Spark DataFrame. Basically we can just use the `with_new_columns` to create a new `InternalFrame`.
- If the function needs to create a new Spark DataFrame, e.g., functions need filter, order, groupby, use `_internal.spark_frame` with columns from `_internal.spark_column_for`. …
> Manage data_spark_columns to avoid creating very many Spark DataFrames.

- databricks/koalas/spark/accessors.py
Since Spark 3.0 will support `DataFrame.explain(extended: str)` case (apache/spark#28711), we can follow it.
```py
>>> df.spark.explain("extended")  # doctest: +ELLIPSIS
== Parsed Logical Plan ==
...
== Analyzed Logical Plan ==
...
== Optimized Logical Plan ==
...
...
```
> Support DataFrame.spark.explain(extended: str) case.

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/namespace.py
- databricks/koalas/numpy_compat.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_series.py
This PR implements `__abs__` in Koalas Series, Index and DataFrame.
Pandas:
```python
>>> abs(pd.Series([-1, -2, -3]))
0    1
1    2
2    3
dtype: int64
>>> np.abs(pd.Series([-1, -2, -3]))
0    1
1    2
2    3
dtype: int64
```
Koalas:
```python
>>> from databricks import koalas as ks
>>> abs(ks.Series([-1, -2, -3]))
0    1
1    2
2    3
>>> np.abs(ks.Series([-1, -2, -3]))
0    1
1    2
2    3
```
> Implement __abs__ in Series, Index and DataFrame

- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
IPython calls Spark jobs twice due to Notebook calls both `__repr__` and `_repr_html_`.
See https://github.com/ipython/ipython/issues/9771
> Cache an internal pandas object to avoid run twice in Jupyter.

- requirements-dev.txt
Setting the upper bound for Sphinx for now to unblock PRs since Sphinx 3.1.0 which was published 5 hours ago causes `lint-python` failure.
> Set upper bound for Sphinx.

- databricks/koalas/frame.py
- databricks/koalas/sql.py
```
/home/runner/miniconda/envs/test-environment/lib/python3.8/site-packages/numpydoc/docscrape.py:377: UserWarning: Unknown section Raises: in the docstring of <function DataFrame.rename at 0x7f381f361e50> in /home/runner/work/koalas/koalas/databricks/koalas/frame.py.
warn(msg)
/home/runner/miniconda/envs/test-environment/lib/python3.8/site-packages/numpydoc/docscrape.py:377: UserWarning: Unknown section Raises: in the docstring of <function DataFrame.rename at 0x7f381f361e50> in /home/runner/work/koalas/koalas/databricks/koalas/frame.py.
warn(msg)
/home/runner/miniconda/envs/test-environment/lib/python3.8/site-packages/numpydoc/docscrape.py:377: UserWarning: Unknown section Raises: in the docstring of <function DataFrame.rename at 0x7f381f361e50> in …
```
> Fix some legitimate doc errors from the latest Sphinx

- databricks/koalas/series.py
- databricks/koalas/spark/functions.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
It's good to support `Series` as `repeats` in `Series.repeat()`.
```py
>>> kdf = ks.DataFrame({"a": ["a", "b", "c"], "rep": [1, 2, 3]})
>>> kdf
a  rep
0  a    1
1  b    2
2  c    3
>>> kdf.a.repeat(kdf.rep)
0    a
1    b
1    b
2    c
2    c
2    c
Name: a, dtype: object
```
As this PR is using a function added since Spark 2.4, it doesn't support Spark 2.3.
> Support Series as repeats in Series.repeat.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
`Series.fillna` should handle NaN properly.
```py
>>> kser = ks.Series([1, 2, 3, 4, 5, 6], name="x")
>>> kser.loc[0] = np.nan
>>> kser
0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
Name: x, dtype: float64
>>> kser.fillna(0)
0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
Name: x, dtype: float64
```
```py
>>> kser.fillna(0)
0    0.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
Name: x, dtype: float64
```
> Fix fillna to handle NaN properly.

- .github/workflows/master.yml
Even if packages are listed as pinned_packages, conda still tries to upgrade/downgrade them if the packages are in `requirements-dev.txt` without the version or with a version range.
```
pinned spec pyarrow==0.15.1 conflicts with explicit specs.  Overriding pinned spec.
```
The installed version satisfies the version range, though.
> Rewrite requirements-dev.txt before installing in conda CI.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
`DataFrame.replace()` doesn't need to create a new Spark DataFrame.
> Fix DataFrame.replace to avoid creating a new Spark DataFrame.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/missing/series.py
- databricks/koalas/tests/test_series.py
This PR propses `Series.bfill` and `Series.ffill` integrating with `DataFrame.bfill` and `DataFrame.ffill` to the `generic.py`
```python
>>> kser = ks.Series([np.nan, 2, 3, 4, np.nan, 6], name="x")
>>> kser
0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
Name: x, dtype: float64
>>> kser.bfill()
0    2.0
1    2.0
2    3.0
3    4.0
4    6.0
5    6.0
Name: x, dtype: float64
>>> kser.ffill()
0    NaN
1    2.0
2    3.0
3    4.0
4    4.0
5    6.0
Name: x, dtype: float64
```
> Adding Series.bfill and Series.ffill

- databricks/koalas/frame.py
Fix `DataFrame.reindex` not to update internal.
```py
>>> index = ["A", "B", "C", "D", "E"]
>>> kdf = ks.DataFrame({"numbers": [1.0, 2.0, 3.0, 4.0, 5.0]}, index=index)
>>> kdf.reindex(["A", "B", "C"], columns=["numbers", "2", "3"], copy=False)
numbers   2   3
B      2.0 NaN NaN
C      3.0 NaN NaN
A      1.0 NaN NaN
>>> kdf
numbers   2   3
B      2.0 NaN NaN
C      3.0 NaN NaN
A      1.0 NaN NaN
```
whereas:
```py
>>> pdf.reindex(["A", "B", "C"], columns=["numbers", "2", "3"], copy=False)
numbers   2   3
A      1.0 NaN NaN
B      2.0 NaN NaN
C      3.0 NaN NaN
>>> pdf
numbers
A      1.0
B      2.0
C      3.0
D      4.0
E      5.0
```
`copy=False` parameter doesn't mean inplace update.
> Fix reindex not to update internal.

- databricks/koalas/tests/test_dataframe.py
The test must be intended to use `dummy_xxx`.
> Fix test_query with inplace=True.

- databricks/koalas/__init__.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/string_typehints.py
- databricks/koalas/typedef/typehints.py
This PR proposes to support the type hints with pandas Series and pandas DataFrame directly.
```python
def transform(pdf) -> pd.DataFrame[int]:
return pdf + 1
ks.range(10).apply_batch(transform)
```
```
c0
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
```
Note that:
- The type hints with Pandas only works with Python 3.7+.
- The previous way with Koalas DataFrame type hint will still work but will be deprecated once we deprecate Python 3.5 and 3.6.
```python
def transform(pdf) -> ks.DataFrame[int]:
return pdf + 1
ks.range(10).apply_batch(transform)
```
> Support pd.DataFrame and pd.Series in return type hints

- databricks/koalas/tests/test_indexes.py
We should use `assertRaisesRegex` instead of `assertRaisesRegexp`.
```
DeprecationWarning: Please use assertRaisesRegex instead.
```
> Fix test_indexes to suppress warnings.

- postBuild
> Remove to set ARROW_PRE_0_15_IPC_FORMAT in binder and use PySpark 3.0

- .readthedocs.yml
- docs/requirements-readthedocs.txt
- docs/source/conf.py
- requirements-dev.txt
This PR proposes to use PySpark 3.0 and remove unnecessary dependency to install JDK 8.
> Make Read the Docs build to use PySpark 3.0, and remove hacks due to JDK

- databricks/conftest.py
- dev/pytest
Since Delta Lake 0.7.0 on Apache Spark 3.0 has been released, we can enable the tests now.
https://github.com/delta-io/delta/releases/tag/v0.7.0
> Enables Delta tests for Spark 3.0 CI.

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/mlflow.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/utils.py
Making `DataFrame` and `Series`/`Index` manage the connection with each other to support inplace updates.
`Series` and `Index` don't manage its own `InternalFrame` anymore, basically they refer the anchor `DataFrame` and create the `InternalFrame` only when needed.
E.g.,
```py
>>> pdf = pd.DataFrame({"x": [np.nan, 2, 3, 4, np.nan, 6], "y": [np.nan, 2, 3, 4, np.nan, 6]})
>>> pser = pdf.x
>>> pser.fillna(0, inplace=True)
>>> pser
0    0.0
1    2.0
2    3.0
3    4.0
4    0.0
5    6.0
Name: x, dtype: float64
>>> pdf
x    y
0  0.0  NaN
1  2.0  2.0
2  3.0  3.0
3  4.0  4.0
4  0.0  NaN
5  6.0  6.0
```
Here, `pser.fillna(0, inplace=True)` should also update `pdf`, whereas:
```py
>>> kdf = ks.DataFrame({"x": [np.nan, 2, 3, 4, np.nan, 6], "y": [np.nan, 2, 3, 4, np.nan, 6]})
>>> kser = kdf.x
>>> …
```
> Make DataFrame and Series/Index manage the connection with each other.

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
This PR proposes a way to specify names in the type hint in DataFrame. See the examples below:
```python
pdf = pd.DataFrame({'a': [1, 2, 3], 'b': [3, 4, 5]})
kdf = ks.from_pandas(pdf)
def transform(pdf) -> pd.DataFrame[zip(pdf.columns, pdf.dtypes)]:
return pdf + 1
kdf.apply_batch(transform)
```
```
a  b
0  2  4
1  3  5
2  4  6
```
```python
def transform(pdf) -> pd.DataFrame["id": int, "A": int]:
pdf['A'] = pdf.id + 1
return pdf
ks.range(10).apply_batch(transform)
```
```
id   A
0   0   1
1   1   2
2   2   3
3   3   4
4   4   5
5   5   6
6   6   7
7   7   8
8   8   9
9   9  10
```
I think we should take this as an experimental feature which could change between minor releases.
This PR …
> Support pandas typehints names

- docs/source/user_guide/index.rst
- docs/source/user_guide/typehints.rst
This PR adds some documentations for https://github.com/databricks/koalas/pull/1578
> Add documentation for new type hints in Koalas

- README.md
- docs/source/index.rst
- docs/source/user_guide/faq.rst
Koalas 1.0.0 will be released very soon.
> Remove the sentences about the project being beta

- databricks/koalas/generic.py
Currently, if the columns contain some expressions depending on hidden columns, `to_csv` fails:
This is because it uses the columns in the previous Spark DataFrame before the projection which does not have the natural order column:
> Fix to_csv to use the column names directly from the Spark DataFrame internally

- databricks/koalas/groupby.py
Temporary group keys should preserve the names.
```py
>>> kdf = ks.DataFrame({"a": [1, 2, 6, 4, 4, 6, 4, 3, 7], "b": [4, 2, 7, 3, 3, 1, 1, 1, 2], "c": [4, 2, 7, 3, None, 1, 1, 1, 2], "d": list("abcdefght")}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> kdf.groupby(kdf.b + 1).sum().sort_index()
a  b    c
__tmp_groupkey_0__
2                   13  3  3.0
3                    9  4  4.0
4                    8  6  3.0
5                    1  4  4.0
8                    6  7  7.0
```
```py
>>> pdf.groupby(pdf.b + 1).sum().sort_index()
a  b    c
b
2  13  3  3.0
3   9  4  4.0
4   8  6  3.0
5   1  4  4.0
8   6  7  7.0
```
> Temporary group keys should preserve the names.

- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
Clean up `InternalFrame` to remove `spark_column` and fix around it, also add some utility methods.
> Clean up InternalFrame and around anchor.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Fixing `DataFrame.rename` with `columns` parameter to use updated Spark columns; otherwise it rolls back the updates for columns.
```py
>>> kdf = ks.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=pd.MultiIndex.from_tuples([("X", "A"), ("X", "B"), ("Y", "C"), ("Y", "D")]))
>>> kdf
X     Y
A  B  C  D
0  1  2  3  4
1  5  6  7  8
>>> kdf1 = kdf + 1
>>> def str_lower(s) -> str:
...   return str.lower(s)
...
>>> kdf1.rename(columns=str_lower)
x     y
a  b  c  d
0  1  2  3  4
1  5  6  7  8
```
```py
>>> pdf1.rename(columns=str_lower)
x     y
a  b  c  d
0  2  3  4  5
1  6  7  8  9
```
Resolves #1608
> Fix DataFrame.rename to use updated Spark columns.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
`ks.DataFrame.iteritems` returns a list whereas `pd.DataFrame.iteritems` returns a generator.
```python
>>> pdf
species  population
panda       bear        1864
polar       bear       22000
koala  marsupial       80000
>>> kdf
species  population
panda       bear        1864
polar       bear       22000
koala  marsupial       80000
>>> pdf.iteritems()
<generator object DataFrame.iteritems at 0x11eeb4318>
>>> kdf.iteritems()
[('species', panda         bear
polar         bear
koala    marsupial
Name: species, dtype: object), ('population', panda     1864
polar    22000
koala    80000
Name: population, dtype: int64)]
```
This PR synced them and added test.
```python
>>> pdf.iteritems()
<generator object DataFrame.iteritems at 0x121c8e840>
>>> kdf.iteritems()
<generator object …
```
> Fixing DataFrame.iteritems to return generator

- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
Now that Series has a different anchor from the one it is originally derived from if it is modified, we don't need to check Spark column's equality in groupby.
Also fixing a bug when it needs `compute.ops_on_diff_frames` but the first group key is from the same DataFrame but modified.
E.g.,
```py
>>> kdf1 = ks.DataFrame({"C": [0.362, 0.227, 1.267, -0.562], "B": [1, 2, 3, 4]})
>>> kdf2 = ks.DataFrame({"A": [1, 1, 2, 2]})
>>> kdf1.groupby([kdf1.C + 1, kdf2.A]).sum()
...
AttributeError: 'NoneType' object has no attribute '_internal'
```
> Clean up groupby to use the anchor.

- databricks/koalas/groupby.py
As `databricks/koalas/internal.py` or `databricks/koalas/typedef/typehints.py` import `is_datetime64_dtype` and `is_datetime64tz_dtype` from `pandas.api.types`, `databricks/koalas/groupby.py` should also import them from the package.
> Import is_datetime64_dtype and is_datetime64tz_dtype from pandas.api.types.

- .gitignore
- databricks/koalas/extensions.py
- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_accessor.py
- databricks/koalas/tests/test_extension.py
- docs/source/reference/extensions.rst
- docs/source/reference/index.rst
This should close #1465 and #1285.
> Add support for API extensions

- databricks/koalas/namespace.py
- databricks/koalas/series.py
We can simplify `Series.to_frame` and avoid creating a new Spark DataFrame.
> Simplify Series.to_frame.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_expanding.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_rolling.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/window.py
Make Window functions create a new Spark DataFrame; otherwise, `AnalysisException` will be raised when aggregate function is applied after the window function.
```py
>>> kdf = ks.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=["A", "B", "C", "D"])
>>> kdf.cumsum().sum()
...
pyspark.sql.utils.AnalysisException: It is not allowed to use a window function inside an aggregate function. Please use the inner window function in a sub-query.;
```
> Make Window functions create a new DataFrame.

- databricks/koalas/__init__.py
- databricks/koalas/usage_logging/usage_logger.py
Since Koalas works only in Python 3, we don't need to use `pyspark.util._exception_message`.
> Avoid using _exception_message.

- databricks/koalas/accessors.py
- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/strings.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
We should always use alias when `IndexOpsMixin._with_new_scol` to make sure the column name is valid.
```py
>>> kser = ks.Series([1, 2, 3, 4, 5, 6, 7], name="x")
>>> (kser.rename("y") + 1).head()
...
pyspark.sql.utils.AnalysisException: syntax error in attribute name: `(x AS `y` + 1)`;
```
Resolves #1633.
> Fix Series._with_new_scol to use alias.

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
As since Spark 3.0 supports a `tail()`, this PR proposes a `Series.tail()` and `DataFrame.tail()` for Koalas based on it.
- Series
```python
>>> kser = ks.Series([1, 2, 3, 4, 5])
>>> kser
0    1
1    2
2    3
3    4
4    5
>>> kser.tail(3)
2    3
3    4
4    5
```
- DataFrame
```python
>>> df = ks.DataFrame({'animal': ['alligator', 'bee', 'falcon', 'lion',
...                    'monkey', 'parrot', 'shark', 'whale', 'zebra']})
>>> df
animal
0  alligator
1        bee
2     falcon
3       lion
4     monkey
5     parrot
6      shark
7      whale
8      zebra
>>> df.tail()
animal
4  monkey
5  parrot
6   shark
7   whale
8   zebra
>>> df.tail(3)
animal
6  shark
7  whale
8  zebra
>>> df.tail(-3)
animal
3    lion
4  monkey
5  parrot
6   shark
7   whale …
```
> Implementing Series.tail() & DataFrame.tail()

- databricks/koalas/sql.py
Since Koalas is only in Python 3, we don't need the prefix 'u' for strings.
> Remove the prefix 'u' for strings.

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
Resolves #1614 
This pull request implements droplevel functionality for koalas dataframe.
```
>>> df
level_1   c   d
level_2   e   f
a b
1 2      3   4
5 6      7   8
9 10    11  12
>>> df.droplevel('a')
level_1   c   d
level_2   e   f
b
2        3   4
6        7   8
10      11  12
>>> df.droplevel('level_2', axis=1)
level_1   c   d
a b
1 2      3   4
5 6      7   8
9 10    11  12
```
> Added droplevel function to dataframe

- databricks/koalas/frame.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/test_namespace.py
Adding `sort` parameter to `ks.concat()`.
> Add sort parameter to concat.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Enables to assign list to `DataFrame`.
```py
>>> kdf = ks.DataFrame({"A": [0, 2, 4], "B": [1, 3, 5], "C": [6, 7, 8]}, index=[10, 11, 12])
>>> kdf['D'] = [9, 10, 11]
>>> kdf
A  B  C   D
10  0  1  6   9
11  2  3  7  10
12  4  5  8  11
```
Resolves #1403.
> Enable to assign list.

- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/utils.py
Use `SPARK_INDEX_NAME_FORMAT` in `utils.combine_frames` to avoid ambiguity.
```py
>>> kdf = ks.DataFrame({"a": [1, 2, 3], "Koalas": [0, 1, 2]}).set_index("Koalas", drop=False)
>>> kdf.index.name = None
>>> kdf["NEW"] = ks.Series([100, 200, 300])
>>> kdf
...
pyspark.sql.utils.AnalysisException: Reference 'Koalas' is ambiguous, could be: Koalas, Koalas.;
```
Related to #1647 as well.
> Use SPARK_INDEX_NAME_FORMAT in combine_frames to avoid ambiguity.

- databricks/koalas/indexes.py
Consolidates the logic for `Index.to_frame()` and `MultiIndex.to_frame()` and rename Spark columns only when `index=False`.
Related to https://github.com/databricks/koalas/issues/1647#issuecomment-657405518, but not fully fixes it.
> Rename spark columns only when index=False.

- databricks/koalas/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
This should close #1615 
```python
>>> kser = ks.Series(
...     [1, 2, 3],
...     index=pd.MultiIndex.from_tuples(
...         [("x", "a"), ("x", "b"), ("y", "c")], names=["level_1", "level_2"]
...     ),
... )
>>> kser
level_1  level_2
x        a          1
b          2
y        c          3
```
Removing specific index level by level
```python
>>> kser.droplevel(0)
level_2
a    1
b    2
c    3
```
Removing specific index level by name
```python
>>> kser.droplevel("level_2")
level_1
x    1
x    2
y    3
```
> Implementing Series.droplevel

- docs/source/getting_started/videos_blogs.rst
A blog post:
- Introducing Koalas 1.0
Spark+AI Summit 2020 talks:
- Introducing Apache Spark 3.0: A retrospective of the Last 10 Years, and a Look Forward to the Next 10 Years to Come.
- Koalas: Making an Easy Transition from Pandas to Apache Spark
- Koalas: Pandas on Apache Spark
> Add recent talks and a blog post.

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_csv.py
Implement reading of number of rows (nrows) in read_csv by using spark's limit.
On the first read, this does not seem to help much with regards to reading speed, because `inferSchema` is True and spark seems to scan over the full data anyway (see e.g. [here](https://stackoverflow.com/questions/44277019/how-to-read-only-n-rows-of-large-csv-file-on-hdfs-using-spark-csv-package)). It would help to use it as a similar parameter to `read_csv` than in pandas to make the API more compatible.
> read_csv: Implement reading of number of rows

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
The existing `ks.Index.to_series()` work not properly with `name` parameter
(**Although Its test was passed !**)
```python
>>> kidx = ks.Index([1, 2, 3])
>>> kidx.to_series(name="Koalas")
1    1
2    2
3    3
Name: 0, dtype: int64  # It should have renamed to 'Koalas'
```
This PR addressed it.
> Fixed ks.Index.to_series() to work properly with name paramter

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_series.py
`fillna` with `method="ffill"` or `method="bfill"` uses Spark's Window functions internally, so we should create a new Spark DataFrame to apply the function properly.
Fixes #1651:
```py
>>> from databricks.koalas import Series
>>> a = ["Bob", "John", None]
>>> b = ["Bob", "John", np.nan]
>>> s1 = Series(a)
>>> s2 = Series(b)
>>> r1 = s1.fillna(method="ffill")
>>> r1
0     Bob
1    John
2    John
>>> r1[2]
'John'
>>> r2 = s2.fillna(method="ffill")
>>> r2
0     Bob
1    John
2    John
>>> r2[2]
'John'
```
> Fix fillna to handle "ffill" and "bfill" properly.

- databricks/koalas/tests/test_indexes.py
Since numpy 1.19, `np.delete` came to fail on out-of-bounds indices (https://github.com/numpy/numpy/pull/15804) and pandas will as well since it depends on numpy.
> Fix test failures caused by numpy upgrade.

- requirements-dev.txt
Sets the lower bound for Plotly, just in case, since Plotly works as a plotting background since `4.8`.
> Since version 0.25, Pandas has provided a mechanism to use different backends, and as of version 4.8 of plotly, you can now use a Plotly Express-powered backend for Pandas plotting.
https://plotly.com/python/pandas-backend/
> Set the lower bound for Plotly.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_csv.py
- databricks/koalas/tests/test_dataframe_conversion.py
- databricks/koalas/tests/test_dataframe_spark_io.py
Refine Spark I/O to:
- Set `partitionBy` explicitly in `to_parquet`.
- Add `mode` and `partition_cols` to `to_csv` and `to_json`.
- Fix type hints to use `Optional`.
Resolves #1666.
> Refine Spark I/O.

- databricks/koalas/tests/test_indexes.py
- requirements-dev.txt
So far pandas sets the upper bound for numpy: https://github.com/pandas-dev/pandas/blob/master/requirements-dev.txt#L4
I'd revert the previous change to fix build and set the upper bound here as well.
Tracking to remove the upper bounds for `numpy` and `matplotlib` at #1670.
> Set the upper bound for numpy.

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
Currently `ks.read_excel` is trying to read a file in the Driver local file system, but it should read from DFS the same as the other `read_xxx` functions.
This PR uses `binaryFile` file format supported in Spark 3.0, so it only works with Spark 3.0 or above.
> Make read_excel read from DFS if the underlying Spark is 3.0.0 or above.

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
To match an error message same as pandas.
```python
>>> pdf
dogs  cats
a   0.2   0.3
b   0.0   0.6
c   0.6   0.0
d   0.2   0.1
>>> kdf
dogs  cats
a   0.2   0.3
b   0.0   0.6
c   0.6   0.0
d   0.2   0.1
>>> pdf['dogs'].index.to_series(name=["x", "a"])
...
TypeError: Series.name must be a hashable type
>>> kdf['dogs'].index.to_series(name=["x", "a"])
...
TypeError: Series.name must be a hashable type
```
> Matching an error message same as pandas for Index.to_series

- dev/pytest
As `pytest 6.0.0` which was released on Jul 28, 2020 dropped undocumented -k syntaxes (https://github.com/pytest-dev/pytest/pull/7210, https://github.com/pytest-dev/pytest/pull/7122), we should use a full sentence query for the parameter:
```
ERROR: Wrong expression passed to '-k': not melt -to_delta -read_delta -to_clipboard: at column 10: expected end of input; got identifier
```
> Avoid using undocumented -k syntaxes.

- .github/workflows/master.yml
- databricks/koalas/tests/test_dataframe_spark_io.py
PyArrow 1.0.0 was released. We should test against it as well.
Closes #1680.
> Upgrade PyArrow to 1.0.0 in CI.

- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
This PR fixes two things.
1. Support `Callable` instances that are not functions:
```python
ks.DataFrame({'a': [-1, -2, 3, 4]}).apply(abs)
```
```
a
0  1
1  2
2  3
3  4
```
2. Keep index name when `DataFrameGroupBy` returns a `Series`:
```python
ks.DataFrame({'a': [1, 2, 2, 2], 'b': [1, 2, 3, 4]}).groupby("a").apply(len)
```
```
a
1    1
2    3
```
Resolves #1684
> Support callable instances to apply as a function, and fix groupby.apply to keep the index when possible

- databricks/koalas/base.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_series.py
`ks.Series.hasnans` and `ks.Index.hasnans` seems not work properly for non-DoubleType.
```python
>>> ks.Series([True, True, np.nan]).hasnans
...
pyspark.sql.utils.AnalysisException: cannot resolve 'isnan(`0`)' due to data type mismatch: argument 1 requires (double or float) type, however, '`0`' is of boolean type.;;
'Aggregate [max((isnull(0#12) OR isnan(0#12))) AS max(((0 IS NULL) OR isnan(0)))#21]
+- Project [__index_level_0__#11L, 0#12, monotonically_increasing_id() AS __natural_order__#15L]
+- LogicalRDD [__index_level_0__#11L, 0#12], false
```
This PR fixed it.
> Bug fixing for hasnans when non-DoubleType.

- requirements-dev.txt
- setup.py
Setting the upper bound for pandas as the behavior changed in pandas 1.1.0.
Fixing the behavior to follow pandas 1.1.0 is working at #1688.
> Set the upper bound for pandas.

- databricks/koalas/namespace.py
Fixes the wrong usage of "binaryFile" format.
The first column is not the content, but actually `path`.
```
root
|-- path: string (nullable = true)
|-- modificationTime: timestamp (nullable = true)
|-- length: long (nullable = true)
|-- content: binary (nullable = true)
```
> Fix the wrong usage of "binaryFile" format in read_excel.

- databricks/koalas/namespace.py
Fixes `read_excel` with Spark 3.0 and pandas<1.0.
```
ValueError: Must explicitly set engine if not passing in buffer or path for io.
```
> Fix read_excel with Spark 3.0 and pandas<1.0.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Adding support `axis=1` or `axis='column'` for `DataFrame.dropna()`.
```py
>>> kdf = ks.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
...                     "toy": [None, 'Batmobile', 'Bullwhip'],
...                     "born": [None, "1940-04-25", None]},
...                    columns=['name', 'toy', 'born'])
>>> kdf
name        toy        born
0    Alfred       None        None
1    Batman  Batmobile  1940-04-25
2  Catwoman   Bullwhip        None
>>> kdf.dropna(axis='columns')
name
0    Alfred
1    Batman
2  Catwoman
```
Resolves #1053.
> Support axis=1 for DataFrame.dropna().

- databricks/koalas/frame.py
This PR proposes to allow assigning an index as a column:
```python
>>> kdf = koalas.range(3)
>>> kdf["col"] = kdf.index
>>> kdf
```
```
id  col
0   0    0
1   1    1
2   2    2
```
Note that this is rather a bandaid fix. If we have a change in the index, it doesn't currently work:
```
>>> kdf["col"] = kdf.index + 1
>>> kdf
```
```
File "/.../koalas/databricks/koalas/frame.py", line 9979, in __repr__
pdf = self._get_or_create_repr_pandas_cache(max_display_count)
File "/.../koalas/databricks/koalas/frame.py", line 9971, in _get_or_create_repr_pandas_cache
self._repr_pandas_cache = {n: self.head(n + 1)._to_internal_pandas()}
File "/.../koalas/databricks/koalas/frame.py", line 4985, in head
sdf = …
```
> Allow assigning index as a column

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
Implemented `Series.product` (`Series.prod` as an alias).
*Note that since It is implemented by using `exp(sum(log(...)))` trick, it only works for positive numbers.
```python
>>> ks.Series([]).prod()
1.0
>>> ks.Series([1, 2, 3, 4, 5]).prod()
120
>>> ks.Series([1, np.nan, 3, np.nan, 5]).prod()
15.0
```
> Add Series.product

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
If a parquet file is stored by pandas, there is a metadata to describe index columns.
We can read it and use as `index_col` if it's not specified.
Resolves #1645.
> Try to read pandas metadata in read_parquet if index_col is None.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
(supersedes previous #1697)
This PR attempts to address an issue I see with column selection of Koalas DataFrames. Pandas allows use of a Pandas Index object for selecting columns, e.g.
```
column_mask = entity.df.columns.isin([variable.id for variable in entity.variables])
index_cols = entity.df.columns[column_mask] 
dtypes = entity.df[index_cols].dtypes.astype(str).to_dict() 
```
will work fine in Pandas but fail with Koalas as the type check in the DataFrame's getitem method does not include the Pandas Index type.
The changes here extend column indexing to all list like objects.
I've added to the test_dataframe test to reflect.
> include pandas Index object in dataframe indexing options

- databricks/koalas/frame.py
There was an outdated description in `DataFrame.pivot_table` doc.
Resolves #1710
> Remove out-of-date description in pivot_table doc.

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
Here is an example of the implementation in analogy of the one from [the pandas docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.cumcount.html):
```python
>>> df = ks.DataFrame(
...     [['a'], ['a'], ['a'], ['b'], ['b'], ['a']],
...     columns=list('A'))
>>> df
A
0  a
1  a
2  a
3  b
4  b
5  a
>>> df.groupby('A').cumcount(ascending=False).sort_index()
0    3
1    2
2    1
3    1
4    0
5    0
Name: A, dtype: int64
>>> df.groupby('A').cumcount().sort_index()
0    0
1    1
2    2
3    0
4    1
5    3
Name: A, dtype: int64
```
The tests are the same like for the other `cumxxx` tests for now.
Nevertheless, it so far does not work the case of nulls and multiple columns within the groupby (thank you for finding this @itholic):
```python
>>> df = …
```
> Implement DataFrame.groupby.cumcount

- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
Modifies `test_cumcount` to address comments https://github.com/databricks/koalas/pull/1702#discussion_r471079743, and also added some more tests in `OpsOnDiffFramesGroupByTest`.
> Modify test_cumcount to address comments.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
When `SeriesGroupBy.nsmallest`/`nlargest` doesn't follow the Series changes:
```py
>>> kdf = ks.DataFrame({'a': [1, 1, 1, 2, 2, 2, 3, 3, 3], 'b': [1, 2, 2, 2, 3, 3, 3, 4, 4]})
>>> (kdf.b * 10).groupby(kdf.a).nsmallest()
a
1  0    1
1    2
2    2
3  6    3
7    4
8    4
2  3    2
4    3
5    3
Name: b, dtype: int64
```
Also, for the renamed Series raises an `AnalysisException`:
```py
>>> kdf.b.rename('x').groupby(kdf.a).nsmallest()
...
pyspark.sql.utils.AnalysisException: Cannot resolve column name "`x`" among (__index_level_0__, a, b, __natural_order__, rank);
```
> Fix SeriesGroupBy.nsmallest/nlargest.

- databricks/koalas/generic.py
- databricks/koalas/indexes.py
`DataFrame.size` should consider its number of columns:
```py
>>> ks.Series({'a': 1, 'b': 2, 'c': None}).size
3
>>> ks.DataFrame({'col1': [1, 2, None], 'col2': [3, 4, None]}).size
3
>>> ks.DataFrame(index=[1, 2, None]).size
3
```
```py
>>> pd.Series({'a': 1, 'b': 2, 'c': None}).size
3
>>> pd.DataFrame({'col1': [1, 2, None], 'col2': [3, 4, None]}).size
6
>>> pd.DataFrame(index=[1, 2, None]).size
0
```
> Fix DataFrame.size to consider its number of columns.

- databricks/koalas/generic.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
`Series.first_valid_index()` and `DataFrame.first_valid_index()` raise Exception for Empty set - but it supposed to return None, not raise Error. -
```python
>>> ks.Series([]).first_valid_index()  # It should return `None`.
...
TypeError: 'NoneType' object is not subscriptable
```
This PR fixed this and added related tests.
```python
>>> ks.Series([]).first_valid_index() is None
True
```
> Fix first_valid_index() for Empty object

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/series.py
- databricks/koalas/window.py
Refactors to use `Series._column_label` instead of `._internal.column_labels[0]`.
> Use Series._column_label instead of ._internal.column_labels[0].

- databricks/koalas/base.py
- databricks/koalas/tests/test_series_datetime.py
This PR allows subtraction of date/timestamp with literals.
```py
>>> date1 = pd.Series(pd.date_range("2012-1-1 12:45:31", periods=3, freq="M"))
>>> date2 = pd.Series(pd.date_range("2013-3-11 21:45:00", periods=3, freq="W"))
>>> kdf = ks.DataFrame(dict(start_date=date1, end_date=date2))
>>> kdf
start_date            end_date
0 2012-01-31 12:45:31 2013-03-17 21:45:00
1 2012-02-29 12:45:31 2013-03-24 21:45:00
2 2012-03-31 12:45:31 2013-03-31 21:45:00
>>> kdf['end_date'] - kdf['start_date']
0    35539169
1    33638369
2    31568369
Name: end_date, dtype: int64
>>> kdf['end_date'] - datetime(2012, 1, 31, 12, 45, 31)
0    35539169
1    36143969
2    36748769
Name: end_date, dtype: int64
>>> datetime(2013, 3, 17, 21, 45, 0) - kdf['start_date']
0    35539169
1    33033569
2    30358769
Name: …
```
> Support subtraction of date/timestamp with literals.

- databricks/koalas/accessors.py
- databricks/koalas/base.py
- databricks/koalas/datetimes.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/strings.py
- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_numpy_compat.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_series_datetime.py
- databricks/koalas/tests/test_series_plot.py
- databricks/koalas/tests/test_series_string.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
- docs/source/getting_started/10min.ipynb
- docs/source/user_guide/best_practices.rst
Adding support non-named Series.
Currently Koalas Series must have its name, but this PR allows it.
```py
>>> ks.Series([1, 2, 3])
0    1
1    2
2    3
dtype: int64
>>> ks.Series([1, 2, 3], name='x')
0    1
1    2
2    3
Name: x, dtype: int64
```
> Support non-named Series.

- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
This PR proposes an implementation of `DataFrame.last_valid_index` and `Series.last_valid_index`
```python
>>> kdf = ks.DataFrame({'a': [1, 2, 3, None],
...                     'b': [1.0, 2.0, 3.0, None],
...                     'c': [100, 200, 400, None]},
...                     index=['Q', 'W', 'E', 'R'])
>>> kdf
a    b      c
Q  1.0  1.0  100.0
W  2.0  2.0  200.0
E  3.0  3.0  400.0
R  NaN  NaN    NaN
>>> kdf.last_valid_index()
'E'
>>> s = ks.Series([1, 2, 3, None, None], index=[100, 200, 300, 400, 500])
>>> s
100    1.0
200    2.0
300    3.0
400    NaN
500    NaN
>>> s.last_valid_index()
300
```
> Implemented last_valid_index for DataFrame and Series

- databricks/koalas/generic.py
Quick fix for build failure. The PR #1705 have failed since It made conflicts with #1712 .
`Series` has no more default name `0`,  we should not include it to the result.
- previous behaviour
```python
>>> s = ks.Series([1, 2, 3, None, None], index=[100, 200, 300, 400, 500])
>>> s
100    1.0
200    2.0
300    3.0
400    NaN
500    NaN
name: 0, dtype: float64
```
- current behaviour
```python
>>> s = ks.Series([1, 2, 3, None, None], index=[100, 200, 300, 400, 500])
>>> s
100    1.0
200    2.0
300    3.0
400    NaN
500    NaN
dtype: float64
```
> Fixed doctest for last_valid_index

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This PR would close #1717.
I used float as fill value in tests in order to avoid clash bewteen int64 (from pandas) and int32 (from spark).
> DataFrame.reindex(fill_value) does not fill existing NaN values

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_expanding.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby_expanding.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby_rolling.py
- databricks/koalas/tests/test_reshape.py
- databricks/koalas/tests/test_rolling.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_series_datetime.py
- databricks/koalas/tests/test_series_plot.py
- databricks/koalas/tests/test_series_string.py
- databricks/koalas/tests/test_stats.py
Changes the testing infrastructure for exact cases to pandas' testing library.
> Use pandas testing utils for exact cases.

- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_stats.py
Introduces `check_exact` parameter for assertions to use pandas testing utils for more cases instead of `almost=True`.
> Introduce `check_exact` parameter for assertions.

- databricks/koalas/plot.py
The plot functions don't refer the option `plotting.backend` when the backend is not specified as a parameter but always shows `"matplotlib"` plots.
```py
>>> ks.options.plotting.backend = "plotly"
>>> kdf = ks.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8]], columns=["A", "B", "C", "D"])
>>> kdf.plot(kind="line")
<matplotlib.axes._subplots.AxesSubplot object at 0x121be2bb0>
```
After the fix:
```py
>>> kdf.plot(kind="line")
Figure({
...
})
```
> Fix plotting backend to refer the option.

- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_csv.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_dataframe_spark_io.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
1. Use `ks.from_pandas` instead of `to_pandas()` to avoid unnecessary copy internally.
2. Use `to_pandas()` instead of `toPandas()` since we've explicitly exposed the former in our official document.
3. Deprecate `toPandas()`
> Cleanup to_pandas() from tests and deprecate toPandas()

- setup.py
We set upper bounds for `numpy` and `matplotlib` in `requirements-dev.txt`, so we should set them in `setup.py` as well.
> Set some upper bounds in setup.py file.

- databricks/koalas/__init__.py
- databricks/koalas/accessors.py
- databricks/koalas/base.py
- databricks/koalas/datetimes.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/internal.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_extension.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/typedef/string_typehints.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
- dev/lint-python
Let us take advantage of a flake8 rule `F401` to detect unused imports.
> Set a flake8 rule for unused imports.

- .github/workflows/master.yml
Upgrades PyArrow for CI to `1.0.1`.
> Upgrade PyArrow for CI.

- dev/lint-python
Since we use F401 rule for flake8 from #1736 ,
The local linter is failed in build directory as shown below.
I think we can just exclude `build` directory from flake8 rule.
> Excluded build directory from flake8

- databricks/koalas/tests/test_dataframe.py
Since now we support non-named Series (#1712)
We don't need to specify the default name as "0" from pandas Series.
> Remove default Series name from test

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/test_indexes.py
- docs/source/reference/indexing.rst
Since Index.mixed is deprecated in pandas, and they recommend use `inferred_type`.
- Anyway in Koalas, `is_mixed()` is not that useful because we don't support the mixed type though.
```python
>>> pd.Index([1, 2, 3]).is_mixed()
<stdin>:1: FutureWarning: Index.is_mixed is deprecated and will be removed in a future version. Check index.inferred_type directly instead.
```
```python
>>> ks.Index([1, 2, 3]).inferred_type
'integer'
>>> ks.Index([1.0, 2.0, 3.0]).inferred_type
'floating'
>>> ks.Index(['a', 'b', 'c']).inferred_type
'string'
>>> ks.Index([True, False, True, False]).inferred_type
'boolean'
```
> Add property inferred_type for Index & MultiIndex

- databricks/koalas/frame.py
Fix typo: `Dataframe.notnull` -> `DataFrame.notnull`.
It's currently unclickable due to a typo:
https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.isnull.html#databricks.koalas.DataFrame.isnull
> Fix typo: `Dataframe.notnull` -> `DataFrame.notnull`

- databricks/koalas/tests/test_csv.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_dataframe_conversion.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
Removes most of `repr` comparison as now that we don't need to use it for most cases.
> Remove most of repr comparison.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
`DataFrame.mad()` has not been working properly as shown below.
```python
>>> pdf
A  B  C
0  3  3  a
1  4  4  b
2  5  5  c
3  6  6  d
4  7  7  e
>>> pdf.mad()
A    1.2
B    1.2
dtype: float64
>>> ks.from_pandas(pdf).mad()
A    1.2
B    1.2
C    NaN  # It should've not been here
dtype: float64
```
This PR fixed it and also fixed related tests.
```python
>>> pdf.mad()
A    1.2
B    1.2
dtype: float64
>>> ks.from_pandas(pdf).mad()
A    1.2
B    1.2
dtype: float64
```
> Fix DataFrame.mad to work properly

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
This PR would close  #881.
It includes moving the method `DataFrame._reindex_index` to the generic `Frame` class.
> Implement Series.reindex

- databricks/koalas/__init__.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/__init__.py
- dev/lint-python
Let us take advantage of a flake8 rule `F405` to detect missing imports.
> Set a flake8 rule for missing imports.

- databricks/koalas/base.py
- databricks/koalas/datetimes.py
- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/strings.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_numpy_compat.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_series_datetime.py
- databricks/koalas/tests/test_series_string.py
Fix `Series` name after binary operations.
When binary operations, if the name of the second operand is different from the first one, the name of the result Series becomes `None`.
```py
>>> pd.Series([1, 2, 3], name="x") + pd.Series([1, 2, 3], name="x")
0    2
1    4
2    6
Name: x, dtype: int64
>>> pd.Series([1, 2, 3], name="x") + pd.Series([1, 2, 3])
0    2
1    4
2    6
dtype: int64
>>> pd.Series([1, 2, 3], name="x") + pd.Series([1, 2, 3], name="y")
0    2
1    4
2    6
dtype: int64
>>> pd.Series([1, 2, 3]) + pd.Series([1, 2, 3])
0    2
1    4
2    6
dtype: int64
>>> pd.Series([1, 2, 3]) + pd.Series([1, 2, 3], name="x")
0    2
1    4
2    6
dtype: int64
```
> Fix Series name after binary operations.

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/test_indexes.py
- docs/source/reference/indexing.rst
Since `Index.item()` is un-deprecated from pandas 1.0.0 (https://github.com/pandas-dev/pandas/issues/29250), this PR proposes `Index.item()` and `MultiIndex.item()`.
```python
>>> kidx = ks.Index([10])
>>> kidx.item()
10
>>> kmidx = ks.MultiIndex.from_tuples([('a', 'x')])
>>> kmidx.item()
('a', 'x')
```
> Implemented item for Index & MultiIndex

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
This PR introduces `DataFrame.product` for Koalas.
```python
>>> kdf = ks.DataFrame({'A': [1, 2, 3, 4, 5],
...                     'B': [10, 20, 30, 40, 50],
...                     'C': ['a', 'b', 'c', 'd', 'e']})
>>> kdf
A   B  C
0  1  10  a
1  2  20  b
2  3  30  c
3  4  40  d
4  5  50  e
>>> kdf.prod()
A         120
B    12000000
dtype: int64
>>> ks.DataFrame({"key": ['a', 'b', 'c'], "val": ['x', 'y', 'z']}).prod()
Series([], dtype: float64)
```
> Implemented DataFrame.product

- databricks/koalas/frame.py
- databricks/koalas/series.py
To avoid overhead of copy, use `_to_internal_pandas` rather than `to_pandas()` if possible.
> Use _to_internal_pandas to avoid copy

- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
`Series.alias` doesn't exist in pandas but was added by a historical reason. We should deprecate it now.
> Deprecate Series.alias.

- databricks/koalas/exceptions.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/plot.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_default_index.py
- databricks/koalas/tests/test_frame_plot.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby_expanding.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby_rolling.py
- databricks/koalas/tests/test_repr.py
- databricks/koalas/tests/test_series_plot.py
- databricks/koalas/window.py
Since the syntax for `super()` changed in [Python 3.0](https://docs.python.org/3/library/functions.html#super),
I think we can make the code more simpler and get more readability.
```diff
class OpsOnDiffFramesEnabledTest(ReusedSQLTestCase, SQLTestUtils):
@classmethod
def setUpClass(cls):
-       super(OpsOnDiffFramesEnabledTest, cls).setUpClass()
+       super().setUpClass()
```
> Remove arguments from super()

- requirements-dev.txt
Read the Docs build is being failed after `nbconvert` 6.0.1 release https://github.com/jupyter/nbconvert/releases.
This PR temporarily exclude 6.0 in the dependency to recover Read the Docs build.
```
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/latest/lib/python3.6/site-packages/sphinx/cmd/build.py", line 279, in build_main
args.tags, args.verbosity, args.jobs, args.keep_going)
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 244, in __init__
self.setup_extension(extension)
File "/home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/latest/lib/python3.6/site-packages/sphinx/application.py", line 398, in setup_extension …
```
> Exclude nbconvert 6.0 temporarily to recover Read the Docs build

- databricks/conftest.py
- databricks/koalas/__init__.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_default_index.py
- databricks/koalas/tests/test_groupby.py
`DefaultIndexTest`s reset the config `compute.default_index_type`, so the following tests are not working under the default index type given by the test environment.
Then found out some tests failed and fixed them (https://github.com/databricks/koalas/runs/1093753632):
- `GroupByTest.test_apply_with_side_effect`
- `NamespaceTest.test_concat_index_axis`
> Fix tests to avoid resetting "compute.default_index_type" and related test failures.

- .github/workflows/master.yml
- databricks/koalas/internal.py
- databricks/koalas/utils.py
As PySpark 3.0.1 was released, this upgrades PySpark version to 3.0.1 for CI.
Also set a config `spark.executor.allowSparkContext` to `"false"` to check Koalas don't create `SparkContext` in executors unexpectedly.
> Upgrade PySpark version to 3.0.1 for CI.

- .github/workflows/master.yml
To make it less confused. This is actually matched with Apache Spark side.
> Rename GitHub Actions workflow build to prevent confusion with branch name

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
- docs/source/reference/indexing.rst
This PR proposes `is_unique` for `Index` & `MultiIndex`.
Basically it's opposite to `has_duplicates`
```python
>>> idx = ks.Index([1, 5, 7, 7])
>>> idx.is_unique
False
>>> idx = ks.Index([1, 5, 7])
>>> idx.is_unique
True
>>> idx = ks.Index(["Watermelon", "Orange", "Apple",
...                 "Watermelon"])
>>> idx.is_unique
False
>>> idx = ks.Index(["Orange", "Apple",
...                 "Watermelon"])
>>> idx.is_unique
True
```
And fixed some tests to sync with pandas'.
> Add is_unique for Index & MultiIndex

- databricks/koalas/exceptions.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
In pandas, `GroupBy.cum~` raise `DataError` - A custom exception of pandas - when the `DataFrame` has not numeric type columns except group keys.
```python
>>> pdf = pd.DataFrame([[1, 'a'], [2, 'b'], [3, 'c'], [4, 'd'], [5, 'e'], [6, 'f']], columns=['A', 'B'])
>>> pdf
A  B
0  1  a
1  2  b
2  3  c
3  4  d
4  5  e
5  6  f
>>> pdf.groupby("A").cumsum()
...
pandas.core.base.DataError: No numeric types to aggregate
```
But in Koalas, It has been returning empty `DataFrame` rather than raise any Exceptions.
```python
>>> kdf.groupby("A").cumsum()
B
5 NaN
4 NaN
0 NaN
2 NaN
1 NaN
3 NaN
```
So, added custom exception `DataError` and managed the logic for matching the behavior with pandas'.
> Fix GroupBy.cum~ for matching with pandas' behavior

- docs/source/reference/indexing.rst
In pandas' doc, they uses `Index objects` for `Index` whereas Koalas uses `Indexing` and I'm not sure If it is intended.
If it's not intended, this PR suggests just match the name same as pandas'.
> [MINOR][DOC] Rename Indexing to Index objects in the doc

- databricks/koalas/frame.py
- databricks/koalas/series.py
Refactor `DataFrame.aggregate` to:
- support multi-index columns
- avoid attaching possibly heavy default index
- avoid falling back to pandas
> Refactor DataFrame.aggregate

- databricks/koalas/groupby.py
For using more general name for the argument.
It's suggested by @ueshin at https://github.com/databricks/koalas/pull/1708#discussion_r488108888
> Rename parameter: is_cum_func -> numeric_only

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This PR proposes `ks.DataFrame.from_dict`.
Basically it just reuse the `DataFrame` constructor.
```python
>>> data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
>>> ks.DataFrame.from_dict(data)
col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d
```
> Add ks.DataFrame.from_dict

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
The PR proposes asi8 for Index & MultiIndex
```python
>>> ks.Index([1, 2, 3]).asi8
array([1, 2, 3])
>>> ks.Index(['a', 'b', 'c']).asi8 is None
True
```
> Add asi8 for Index & MultiIndex

- databricks/koalas/frame.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_namespace.py
Adds a check for `DataFrame.columns.names` when `almost=True`, and fixes test failures caused by the check.
> Check DataFrame.columns.names when almost=True.

- .github/workflows/master.yml
As PySpark 2.4.7 was released, this upgrades PySpark version to 2.4.7 for CI.
> Upgrade PySpark version to 2.4.7 for CI.

- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_stats.py
When tests with Spark<3.0 fail, a lot of the following warnings appear:
```
WARN SQLConf: The SQL config 'spark.sql.execution.arrow.enabled' has been deprecated in Spark v3.0 and may be removed in the future. Use 'spark.sql.execution.arrow.pyspark.enabled' instead of it.
```
> Suppress warnings in tests with Spark<3.0.

- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
Basically, this PR addressed https://github.com/databricks/koalas/pull/1739#pullrequestreview-482833894
`cumprod` for `DataFrame` & `Series` & `GroupBy` isn't working properly with integer columns.
```python
>>> pdf
A    B  C
0  2.0  1.0  1
1  5.0  NaN  2
2  1.0  1.0  3
3  2.0  4.0  4
4  4.0  9.0  5
>>> pdf.cumprod()
A     B    C
0   2.0   1.0    1
1  10.0   NaN    2
2  10.0   1.0    6
3  20.0   4.0   24
4  80.0  36.0  120
>>> ks.from_pandas(pdf).cumprod()
A     B      C
0   2.0   1.0    1.0
1  10.0   NaN    2.0
2  10.0   1.0    6.0
3  20.0   4.0   24.0
4  80.0  36.0  120.0
```
This PR addressed it and also addressed the related tests.
```python
>>> pdf.cumprod()
A     B    C
0.986323   2.0   1.0    1
0.297507  10.0   NaN    2
0.617855  10.0   1.0    6
0.711719  20.0   4.0   24
0.290114 …
```
> Fix cumprod to work properly with Integer columns.

- .github/workflows/master.yml
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_series.py
- requirements-dev.txt
- setup.py
> Matching behavior with pandas 1.1.2

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This should resolve #1770 
```python
>>> toy_pd = pd.DataFrame(columns = ['day','item','size'], data = [[5, 0, 500],[5, 0, 550],[5, 1, 1500],[5, 1, 700],[5, 1, 900],
... [6, 0, 400],[6, 0, 300],[6, 0, 600], [6, 1, 800],[6, 1, 200],
... [7, 0, 600],[7, 1, 700],[7, 1, 700], [7, 2, 750],[7, 2, 500]])
>>> toy_ks1 = ks.from_pandas(toy_pd).groupby(['day','item']).agg({'size':'mean'})
>>> toy_ks2 = ks.from_pandas(toy_pd).groupby(['day','item']).agg({'size':'mean'})
>>> toy_ks1.join(toy_ks2, on = ['day','item'], rsuffix='r')
size        sizer
day item
5   1     1033.333333  1033.333333
7   1      700.000000   700.000000
2      625.000000   625.000000
6   1      500.000000   500.000000
7   0      600.000000   600.000000
6   0      433.333333   433.333333
5   0      525.000000   525.000000
```
> Fix DataFrame.join for MultiIndex

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
`MultiIndex.from_frame` doesn't raise exception properly when given parameter is not a `DataFrame`.
```python
>>> pd.MultiIndex.from_frame(10)
...
TypeError: Input must be a DataFrame
>>> ks.MultiIndex.from_frame(10)
...
AttributeError: 'int' object has no attribute 'to_spark'
```
This PR fixed it and added related tests.
> Exception handling for from_frame properly

- databricks/koalas/indexing.py
- databricks/koalas/tests/test_indexing.py
Current behavior of `iloc` seems not work properly in the case below.
```python
>>> pdf = pd.DataFrame({'A': [3, 4, 5, 6, 7],
...                     'B': [10.0, 20.0, 30.0, 40.0, 50.0],
...                     'C': ['a', 'b', 'c', 'd', 'e'],
...                     'D': [np.nan, np.nan, np.nan, np.nan, np.nan]})
>>> pdf.columns.name = "Koalas"
>>> kdf = ks.from_pandas(pdf)
>>> pdf.iloc[:0]  # same as `pdf[:0]`
Empty DataFrame
Columns: [A, B, C, D]
Index: []
>>> kdf.iloc[:0]  # should've returned `Empty DataFrame` 
Koalas  A     B  C   D
0       3  10.0  a NaN
1       4  20.0  b NaN
2       5  30.0  c NaN
3       6  40.0  d NaN
4       7  50.0  e NaN
```
This PR fixed it.
```python
>>> pdf.iloc[:0]
Empty DataFrame
Columns: [A, B, C, D]
Index: []
>>> kdf.iloc[:0]
Empty DataFrame
Columns: …
```
> Fix iloc for slice(None, 0)

- docs/source/getting_started/install.rst
Added `numpy` to the Dependencies table in the documents.
And fixed "Minimum supported version" of `pandas` properly - from `0.23` to `0.23.2` - .
> Add numpy to Dependencies table

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
This PR proposes `DataFrame.pad` and `Series.pad`
This is basically synonym for `DataFrame.fillna` and `Series.fillna` with `method='ffill'` or `ffill` function
```python
>>> df = ks.DataFrame({
...     'A': [None, 3, None, None],
...     'B': [2, 4, None, 3],
...     'C': [None, None, None, 1],
...     'D': [0, 1, 5, 4]
...     },
...     columns=['A', 'B', 'C', 'D'])
>>> df
A    B    C  D
0  NaN  2.0  NaN  0
1  3.0  4.0  NaN  1
2  NaN  NaN  NaN  5
3  NaN  3.0  1.0  4
>>> df.pad()
A    B    C  D
0  NaN  2.0  NaN  0
1  3.0  4.0  NaN  1
2  3.0  4.0  NaN  5
3  3.0  3.0  1.0  4
>>> s = ks.Series([np.nan, 2, 3, 4, np.nan, 6], name='x')
>>> s
0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
Name: x, dtype: float64
>>> s.pad()
0    NaN
1    2.0
2    3.0
3    4.0
4    4.0
5    6.0
Name: x, …
```
> Implemented DataFrame.pad & Series.pad

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
This PR proposes `Series.argmin` & `Series.argmax`.
```python
>>> kser = ks.Series(
...     {
...         "Corn Flakes": 100.0,
...         "Almond Delight": 110.0,
...         "Cinnamon Toast Crunch": 120.0,
...         "Cocoa Puff": 110.0,
...         "Expensive Flakes": 120.0,
...         "Cheap Flakes": 100.0,
...     }
... )
>>> kser.argmin()
0
>>> kser.argmax()
2
```
> Implemented argmin & argmax for Series

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
This proposes `get_group` for `DataFrameGroupBy` & `SeriesGroupBy`.
```python
>>> kdf = ks.DataFrame([('falcon', 'bird', 389.0),
...                     ('parrot', 'bird', 24.0),
...                     ('lion', 'mammal', 80.5),
...                     ('monkey', 'mammal', np.nan)],
...                    columns=['name', 'class', 'max_speed'],
...                    index=[0, 2, 3, 1])
>>> kdf
name   class  max_speed
0  falcon    bird      389.0
2  parrot    bird       24.0
3    lion  mammal       80.5
1  monkey  mammal        NaN
>>> kdf.groupby("class").get_group("bird").sort_index()
name class  max_speed
0  falcon  bird      389.0
2  parrot  bird       24.0
>>> kdf.groupby("class")["name"].get_group("bird").sort_index()
0    falcon
2    parrot
Name: name, dtype: object
```
> Implemented get_group for DataFrameGroupBy & SeriesGroupBy.

- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_dataframe_conversion.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_series.py
This PR proposes integration of `assert_array_eq` and `assert_list_eq` into `assert_eq` for avoiding confusion when tests.
> Integrated 'assert_array_eq' and 'assert_list_eq' into 'assert_eq'

- databricks/koalas/series.py
- databricks/koalas/tests/test_repr.py
- databricks/koalas/typedef/typehints.py
Fix `Series.__repr__` when `Series.name` is `None` and the length is longer than a config `display.max_rows`.
Additional added some more test cases.
> Fix Series.__repr__ when Series.name is None.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
> DataFrame.reindex supports koalas Index parameter

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
`Series.fillna` with `inplace=True` drops other columns from the original `DataFrame` if the columns is not nullable because it uses a shortcut path by just returning its copy when the column is not nullable, but the `Series.copy` renews the anchor DataFrame without other columns.
Resolves #1807
> Fix Series.fillna with inplace=True on non-nullable column.

- databricks/koalas/frame.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/utils.py
Enables column indexing for non-string column names as currently it is not available. 
```py
>>> kdf = ks.DataFrame({0: [1, 2, 3, 4, 5, 6, 7, 8, 9], 1: [4, 5, 6, 3, 2, 1, 0, 0, 0]}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> kdf.loc[:, 0]
...
AssertionError
>>> kdf[0]
...
NotImplementedError: 0
```
> Modify input check for indexers to support non-string column names.

- databricks/koalas/tests/test_groupby.py
Previously there was a behavior we suspected a bug in pandas, but seems like it's working since pandas 1.0.4:
```py
>>> pdf = pd.DataFrame({("x", "a"): [1, 2, 6, 4, 4, 6, 4, 3, 7], ("x", "b"): [4, 2, 7, 3, 3, 1, 1, 1, 2], ("y", "c"): [4, 2, 7, 3, None, 1, 1, 1, 2], ("z", "d"): list("abcdefght")}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> pdf
x       y  z
a  b    c  d
0  1  4  4.0  a
1  2  2  2.0  b
3  6  7  7.0  c
5  4  3  3.0  d
6  4  3  NaN  e
8  6  1  1.0  f
9  4  1  1.0  g
9  3  1  1.0  h
9  7  2  2.0  t
>>> pdf[("x", "a")].groupby(pdf[("x", "b")]).sum().sort_index()
(x, b)
1    13
2     9
3     8
4     1
7     6
Name: (x, a), dtype: int64
```
We should use the pandas result.
> The test in test_groupby is working after pandas 1.0.4.

- .github/workflows/master.yml
pandas 1.1.3 has been released on October 5, 2020.
- https://pandas.pydata.org/docs/whatsnew/v1.1.3.html
> Upgrade pandas to 1.1.3 for CI.

- databricks/koalas/tests/test_groupby.py
There is a bug introduced in pandas 1.1.3.
```py
>>> pdf = pd.DataFrame({("x", "a"): [1, 2, 6, 4, 4, 6, 4, 3, 7], ("x", "b"): [4, 2, 7, 3, 3, 1, 1, 1, 2], ("y", "c"): [4, 2, 7, 3, None, 1, 1, 1, 2], ("z", "d"): list("abcdefght")}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> pdf
x       y  z
a  b    c  d
0  1  4  4.0  a
1  2  2  2.0  b
3  6  7  7.0  c
5  4  3  3.0  d
6  4  3  NaN  e
8  6  1  1.0  f
9  4  1  1.0  g
9  3  1  1.0  h
9  7  2  2.0  t
>>> pdf[("x", "a")].groupby(pdf[("x", "b")]).sum().sort_index()
...
TypeError: only integer scalar arrays can be converted to a scalar index
```
> Fix a test caused by a bug introduced in pandas 1.1.3.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
`Koalas` doesn't support `to_list` in `pandas<0.24` because `pandas<0.24` doesn't support `to_list` as an alias for `tolist`.
```python
>>> pd.__version__
'0.23.2'
>>> pser.to_list()
File "/Users/haejoon.lee/opt/miniconda3/envs/koalas-dev-3.6/lib/python3.6/site-packages/pandas/core/generic.py", line 4372, in __getattr__
return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'to_list'
>>> pser.tolist()
[1, 2, 3]
```
This PR fix it to make working `to_list` properly in pandas<0.24.
> Fix to_list work properly in pandas==0.23

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Fixes the input check in `groupby`.
> Fix the input check in groupby.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
This should fix #1806 
```python
>>> data = ks.Series(['a', 'b', 'c', None])
>>> sorted(data.astype(str).tolist())
['None', 'a', 'b', 'c']
```
For `DataFrame.astype` also works.
```python
>>> kdf
A     B     C
0  3  10.0     a
1  4  20.0     b
2  5  30.0     c
3  6  40.0     d
4  7  50.0  None
>>> sorted(kdf.astype(str).C.tolist())
['None', 'a', 'b', 'c', 'd']
```
> Fix Series.astype to work properly

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Support `DataFrame.groupby` and `Series.groupby` with `dropna` parameter introduced in pandas 1.1.0.
It would also fix  #1007.
> Frame.groupby supports dropna

- databricks/koalas/base.py
- databricks/koalas/spark/functions.py
- databricks/koalas/tests/test_dataframe.py
- New test cases related to **Pandas only** are added for PR reviewers to visualize Pandas' behavior.
They are commented out and will be removed before the PR merge (after PR review).
- This PR doesn't aim to cover all binary operations: only `+`, `-`, `*`, `/`, `//`, `%` are concerned.
Make behaviors of binary operations (`+`, `-`, `*`, `/`, `//`, `%`) between **int** and **str** columns consistent with respective pandas behaviors.
- Standardize binary operations as follows:
`+`: raise TypeError between int column and str column (or string literal)
`*`: act as spark SQL `repeat` between int column(or int literal) and str columns; raise TypeError if a string literal is involved
`-`, `/`, `//`, `%(modulo)`: raise TypeError if a str column (or string literal) is involved
- Add `def …
> Standardize binary operations between int and str columns

- docs/source/getting_started/videos_blogs.rst
Add blog post link https://databricks.com/blog/2020/08/11/interoperability-between-koalas-and-apache-spark.html under **Koalas Talks and Blogs**
> Add blog post link "Interoperability between Koalas and Apache Spark"

- databricks/koalas/base.py
- databricks/koalas/tests/test_dataframe.py
Multiplication involves a string column can only be applied to an int column or literal; otherwise, a TypeError should be raised.
> Standardize multiplication involving string column

- README.md
The installation guide for Databricks users is out-dated. Let's just refer the official guide.
> Update the installation guide for Databricks users.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This PR implements `__neg__`:
```python
>>> from databricks import koalas as ks
>>> -kdf
id
0   0
1  -1
2  -2
3  -3
4  -4
5  -5
6  -6
7  -7
8  -8
9  -9
```
```python
>>> pdf = kdf.to_pandas()
>>> -pdf
id
0   0
1  -1
2  -2
3  -3
4  -4
5  -5
6  -6
7  -7
8  -8
9  -9
```
> Implement DataFrame.__neg__

- databricks/koalas/frame.py
When use `CachedDataFrame` in the context manager, It raises `FutureWarning` as below.
```python
>>> with kdf.spark.cache() as cached:
...     cached.spark.storage_level
...
StorageLevel(True, True, False, True, 1)
.../koalas/databricks/koalas/frame.py:10593: FutureWarning: DataFrame.unpersist is deprecated as of DataFrame.spark.unpersist. Please use the API instead.
```
This warning is unavoidable since It's fixed in the code, so this PR proposes removing this.
```python
>>> with kdf.spark.cache() as cached:
...     cached.spark.storage_level
...
StorageLevel(True, True, False, True, 1)
```
> Remove FutureWarning when use cache in the context manager

- databricks/koalas/plot.py
- databricks/koalas/tests/test_series_plot.py
This PR fixes `Series.boxplot` to support non-string name in Series's boxplot.
```python
ks.Series([1, 2, 3]).plot.box()
```
**Before:**
```python
<matplotlib.axes._subplots.AxesSubplot object at 0x12251a340>
```
**After:**
```
File "/.../koalas/databricks/koalas/plot.py", line 1654, in box
return self(kind="box", **kwds)
File "/.../koalas/databricks/koalas/plot.py", line 1340, in __call__
return plot_series(data=self.data, kind=kind, **kwds)
File "/.../koalas/databricks/koalas/plot.py", line 892, in plot_series
return _plot(
File "/.../koalas/databricks/koalas/plot.py", line 1117, in _plot
plot_obj.generate()
File "/usr/local/lib/python3.8/site-packages/pandas/plotting/_matplotlib/co …
```
> Support a non-string name in Series' boxplot

- databricks/koalas/plot.py
- databricks/koalas/tests/test_series_plot.py
Koalas:
```python
from matplotlib import pyplot as plt
pdf = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
ks.from_pandas(-pdf).a.plot.box()
plt.savefig('koalas_series_box.png')
```
pandas:
```python
from matplotlib import pyplot as plt
pdf = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
(-pdf).a.plot.box()
plt.savefig('pandas_series_box.png')
```
**Before:**
**After:**
Resolves #1827
> Calculate fliers correctly in Series.plot.box

- databricks/koalas/plot.py
- docs/source/getting_started/install.rst
- requirements-dev.txt
- setup.py
This PR removes the upper bound of matplotlib in the dependency.
The test failures because of `manage_xticks`. This was [deprecated at 3.1.0](https://matplotlib.org/3.1.1/api/api_changes.html#boxplot-tick-methods) and [removed at 3.3.0](https://matplotlib.org/api/api_changes.html#arguments).
> Remove the upper bound of matplotlib

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/sql.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_namespace.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_sql.py
Use `type(...).__name__` rather than `type(...)` in error messages.
> Show type name rather than type class in error messages

- databricks/koalas/generic.py
This PR adds the type hints for its return type at `Series.groupby` and `DataFrame.groupby`.
> Add return type of groupby

- .github/workflows/master.yml
Python 3.5 installation is being failed with:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/18.04/prod/dists/bionic/main/binary-amd64/Packages.bz2  File has unexpected size (141364 != 141252). Mirror sync in progress? [IP: 13.90.56.68 443]
Hashes of expected file:
- Filesize:141252 [weak]
- SHA512:dffbaf15f537ae643df110b279248993b2828e99352dff51a5df9648cf39531ffb7022ec2f0d9e553287c9889addcb5e734d9df95f749c456db04fd328a67ef4
- SHA256:6757f7f09fb2a0491657aac899faa29bd67fe7b9dfd849844f7fafca9afcc33e
- SHA1:37be76673db70e808db91294af54fddf476aae7f [weak]
- MD5Sum:ecc0d5d8d9373eee7aeceda58d7be8f9 [weak]
Release file created at: Tue, 13 Oct 2020 22:35:00 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
This PR adds apt-get update …
> Add apt-get update to refresh the repo

- databricks/koalas/frame.py
- databricks/koalas/series.py
Add return type of to_koalas and to_pandas
> Add return type of to_koalas and to_pandas

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
This PR is follow-up for comments of #1839 .
- Just raise the IndexError when out of bounds.
- Fixed bug and added related tests
> [FOLLOW-UP] Modify Index.delete for doing not rely on numpy version

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Hi, this PR implements `DataFrame.rename_axis` and `Series.rename_axis`.
I did not add `copy` parameter as a copy is performed anyway.
> Implement DataFrame/Series rename_axis

- databricks/koalas/base.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_indexops_spark.py
Separates `SparkIndexOpsMethods` into `SparkSeriesMethods` and `SparkIndexMethods` and adds type annotations.
> Refactor Spark accessor and add type annotations.

- docs/source/getting_started/install.rst
This PR proposes:
- Fix supported Python version from `Python 3.5 and above` to `Python 3.5 to 3.8` since we doesn't support Python 3.9 yet.
- Fix Koalas version in installation guide from `0.19.0` to `1.3.0` since it's too old.
> Fix Python version and Koalas version in installation docs

- databricks/koalas/internal.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_frame_spark.py
Fixes `DataFrame.spark.hint` to reflect internal changes.
E.g.,:
```py
>>> kdf1 = ks.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'], 'value': [1, 2, 3, 5]}).set_index('lkey')
>>> kdf2 = ks.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'], 'value': [5, 6, 7, 8]}).set_index('rkey')
>>> kdf1.merge((kdf2 + 1).spark.hint("broadcast"), left_index=True, right_index=True).sort_values(['value_x', 'value_y'])
value_x  value_y
lkey
foo         1        5
foo         1        8
bar         2        6
baz         3        7
foo         5        5
foo         5        8
```
This is different from the result without the hint:
```py
>>> kdf1.merge(kdf2 + 1, left_index=True, right_index=True).sort_values(['value_x', 'value_y'])
value_x  value_y
lkey
foo         1        6
foo         1        9
bar …
```
> Fix DataFrame.spark.hint to reflect internal changes.

- databricks/koalas/series.py
- databricks/koalas/typedef/typehints.py
Add type annotations (mostly return types) to functions in Series.py. This helps autocompletion in various editors.
> Add type annotations to Series 

- .gitignore
Currently `docs/mlruns` directory can be generated during documentation generation for some reasons. This PR adds it to the `.gitignore`.
> Ignore docs/mlruns directory generated during doc creation

- databricks/koalas/namespace.py
- requirements-dev.txt
This PR proposes to set the lower bound of numpydoc. The main reason to set the bound to 0.8.0 was that `self` argument appeared in the API references (see https://github.com/databricks/koalas/issues/439). This seems fixed now from 1.1.0+
There are a couple of methods not being found in "See Also" via numpydoc but I think they are trivial issues.
> Set the lowerbound of numpydoc

- .gitignore
Looks like mlflow creates that directory when it imports:
```python
>>> import mlflow
```
```bash
ls -al mlruns
```
```
total 0
drwxr-xr-x   4 hyukjin.kwon  staff  128 Oct 27 11:42 .
drwxr-xr-x@ 30 hyukjin.kwon  staff  960 Oct 27 11:42 ..
drwxr-xr-x   2 hyukjin.kwon  staff   64 Oct 27 11:42 .trash
drwxr-xr-x   3 hyukjin.kwon  staff   96 Oct 27 11:42 0
```
> Ignore mlruns directory globally

- databricks/koalas/frame.py
Add type annotations to frame. This is helpful to Autocompletion and Static Error Check in various editors. 
A few type comments are added in order to pass mypy check.
Most type comments `# type: ignore` are related to Optional type. We are considering enabling `--no-strict-optional` option of mypy in order to discard these type comments. However, this is not the scope of this PR.
> Type annotations to frame

- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_frame_spark.py
- docs/source/reference/frame.rst
> Introduce df.spark.coalesce()

- databricks/koalas/frame.py
- databricks/koalas/series.py
- dev/lint-python
Enable no-strict-optional of mypy
For methods with inplace parameter, their return types are mostly of Optional type. For example:
def sort_values(
self,
by: Union[Any, List[Any], Tuple, List[Tuple]],
ascending: Union[bool, List[bool]] = True,
inplace: bool = False,
na_position: str = "last",
) -> Optional["DataFrame"]:
Even if we call these methods with inplace as False, i.e., we are promised to get a new DataFrame, mypy will still complain about None. For example, in 
def nsmallest(self, n: int, columns: "Any") -> "DataFrame":
return self.sort_values(by=columns, ascending=True).head(n=n) 
Mypy checks will fail:
databricks/koalas/frame.py: note: In member "nlargest" of class "DataFrame":
databricks/koalas/frame.py:6408: error: Item "None" of "Optional[DataFrame[Any]]" has no attribute …
> Enable no-strict-optional of mypy

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Hi, this PR implements both `DataFrame.reindex_like` and `Series.reindex_like`.
I did not add a test about reindexing MultiIndex columns on single Index columns because it is currently not supported in koalas. Also, as for `DataFrame.reindex`, there is no test for reindexing single Index columns/index on MultiIndex columns/index, as it is not supported in pandas.
> Implement DataFrame/Series reindex_like

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
`#type: ignore`'s in b20a3b1 are mostly because mypy cannot identify `_attributes` of `self`.
We are considering adding abstract methods to `GroupBy` to help mypy identify. However, this should be a separate task.
> Add type annotations to GroupBy objects

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Fixes `DataFrame.xs` to handle internal changes properly.
Also fixes:
- the return type and type annotation.
- a bug when `level` is out of range.
- a bug when the result is duplicated with the key whose length is the same as index level.
> Fix DataFrame.xs to handle internal changes properly.

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_dataframe.py
When an empty list is passed to `IndexFrame.index_spark_column_names` or `.index_names`, currently it passes without any errors and it will cause an unexpected error in other places.
We should handle the empty list the same as `None`.
> Explicitly disallow empty list as index_spark_colum_names and index_names.

- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/spark/utils.py
This PR proposes to use nullable schema in when to apply a function. We take some to infer the schema. Usually types are matched but null or NaN is sparse often. This behaviour is batch with Spark's JSON schema inference as well.
```python
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
data = list()
for i in range(1, 10000):
data.append((str(i % 100), np.nan if i % 9999 == 0 else float(i),))
sdf = spark.createDataFrame(data, 'a string, b float').repartition(10)
kdf = sdf.to_koalas()
def f(df):
return df
df = kdf\
.groupby('a')\
.apply(f)
df.to_spark().printSchema()
df[df['b'] == -1]
```
**Before:**
```
root
|-- a: string (nullable = false)
|-- b: float (nullable = false)
java.lang.IllegalStateException: …
```
> Use nullable inferred schema in function apply

- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/series.py
Currently there are different ways to check the number of the index columns. We should introduce `InternalFrame.index_level` and use it.
> Introduce InternalFrame.index_level.

- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/internal.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_internal.py
- databricks/koalas/utils.py
Removes `InternalFrame.index_map` which is not suitable in many cases or can easily be replaced with `zip(column_names, index_names)`.
> Remove InternalFrame.index_map.

- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/namespace.py
- databricks/koalas/spark/utils.py
The return type inference sometimes fails when the inferred type contains `DecimalType` to infer the precision or the scale smaller.
```py
>>> from decimal import Decimal
>>> kdf = ks.DataFrame({'a': [Decimal('1.1'), Decimal('2.2'), Decimal('10.01')]})
>>> kdf
a
0   1.10
1   2.20
2  10.01
>>> kdf.spark.print_schema()
root
|-- a: decimal(4,2) (nullable = false)
>>> with ks.option_context("compute.shortcut_limit", 1):
...   kdf.transform(lambda x: x).spark.print_schema()
...
root
|-- a: decimal(3,2) (nullable = true)
>>> with ks.option_context("compute.shortcut_limit", 1):
...   kdf.transform(lambda x: x)
...
...
pyarrow.lib.ArrowInvalid: Decimal type with precision 4 does not fit into precision inferred from first array element: 3
...
```
We should use …
> Force to use the Spark's system default precision and scale when inferred data type contains DecimalType.

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
Fixes `read_excel` to support squeeze argument.
Currently it always return `DataFrame` when there are multiple Excel files.
> Fix read_excel to support squeeze argument.

- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
Until now, only arrays of string type could be used as type hints with np.array.
This PR proposes to support many other child types, too.
This should resolve #1133
> Support typehints for various of ArrayType.

- docs/source/development/design.rst
- docs/source/getting_started/install.rst
In some cases such as `apply`, `transform`, `apply_batch`, or `tranform_batch`, Koalas still requires to be installed in worker nodes, see https://github.com/databricks/koalas/issues/1826.
This PR removes some wordings about the installation in workers for now, and makes it deferred to future work.
> Move the words about Koalas in workers

- docs/source/user_guide/index.rst
- docs/source/user_guide/types.rst
Added documents "Type Support In Koalas" to describe which type is supported in Koalas and which type is not.
> Add docs: Type Support In Koalas

- databricks/koalas/generic.py
Spark doesn't allow duplicated option `path` when `DataFrameWriter.save()` since Spark 3.1. (apache/spark#29543)
> Fix to_csv to avoid duplicated option 'path' for DataFrameWriter.

- databricks/koalas/base.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_indexes.py
For some cases, `Index.astype` is not working properly unlike `Series.astype`.
```python
>>> pser = pd.Index(['a', 'b', None], name="x")
>>> kser = ks.Index(pser)
>>> pser.astype(bool)
Index([True, True, False], dtype='object', name='x')
>>> kser.astype(bool)
Index([None, None, None], dtype='object', name='x')
```
This PR would suggest sharing the implementation of `Series.astype` for `Index.astype`, and adding tests for `Index.astype`.
> Moved Series.astype to base.py for sharing implementation with Index

- databricks/koalas/groupby.py
Add a constructor to GroupBy for attribute type hints. This proposal can save a lot of "# type: ignore" comments.
> Add a constructor to GroupBy for attribute type hints

- databricks/koalas/frame.py
- databricks/koalas/indexes.py
Use `typing.cast` in return statements that call functions with union return types. This saves us from `# type: ignore` comments.
> Use typing.cast in return statements that call functions with union return types

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
Since `hasnans` is not implemented for `MultiIndex`, we should raise `NotImplementedError` like pandas.
> NotImplementedError for MultiIndex.hasnans

- databricks/koalas/namespace.py
The type annotations for `from_pandas` don't need to be forward references.
> Fix type annotations for from_pandas.

- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_groupby.py
Fixes `GroupBy.describe` for multi-index columns.
```py
>>> kdf = ks.DataFrame({("x", "a"): [1, 1, 3], ("x", "b"): [4, 5, 6], ("y", "c"): [7, 8, 9]})
>>> kdf.groupby(("x", "a")).describe()
...
pyspark.sql.utils.AnalysisException: cannot resolve '`(('x', 'b'), 'quartiles')`' given input columns: ...
```
> Fix GroupBy.descirbe for multi-index columns.

- databricks/koalas/generic.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
Fixes `first/last_valid_index` to support empty column DataFrame.
E.g.,:
```py
>>> kdf = ks.DataFrame({"a": [None, 2, 3, 2], "b": [None, 2.0, 3.0, 1.0], "c": [None, 200, 400, 200]}, index=["Q", "W", "E", "R"])
>>> kdf
a    b      c
Q  NaN  NaN    NaN
W  2.0  2.0  200.0
E  3.0  3.0  400.0
R  2.0  1.0  200.0
>>> kdf.first_valid_index()
'W'
>>> kdf[[]].first_valid_index()
...
TypeError: reduce() of empty sequence with no initial value
```
, which should return `None`:
```py
>>> kdf[[]].to_pandas().first_valid_index()
```
This PR also includes:
- small optimizations
- explicitly raise an error in last_valid_index for PySpark<3.0
- explicitly make tests skip for PySpark<3.0
> Fix first/last_valid_index to support empty column DataFrame.

- docs/source/reference/groupby.rst
The document for `DataFrameGroupBy.describe` is missing in https://koalas.readthedocs.io/en/latest/reference/groupby.html.
> Add a doc for DataFrameGroupBy.describe.

- databricks/koalas/frame.py
- databricks/koalas/series.py
As per the discussion https://github.com/databricks/koalas/issues/1927#issuecomment-733943694, we should just use pandas' transpose when the expected data size is small enough.
> Use pandas' transpose when the data is expected to be small.

- databricks/koalas/plot.py
`kdf.plot(kind="area")` works but `kdf.plot.area()` fails due to unexpected argument being passed when the plot backend is `plotly`: 
```python
>>>
>>> ks.options.plotting.backend = "plotly"
...     np.random.randn(1000, 4),
...     index=pd.date_range('1/1/2000', periods=1000),
...     columns=['A', 'B', 'C', 'D'])
kdf = kdf.cummax()
pdf = kdf.to_pandas()
>>> kdf.plot.area()
```
**Before:**
```
File "/.../koalas/databricks/koalas/plot.py", line 1866, in area
return self(kind="area", x=x, y=y, stacked=stacked, **kwds)
File "/.../koalas/databricks/koalas/plot.py", line 1350, in __call__
return plot_backend.plot(plot_data, kind=kind, **kwds)
File …
```
> Don't pass stacked in plotly area chart

- databricks/koalas/plot/__init__.py
- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
- databricks/koalas/tests/plot/test_series_plot.py
- setup.py
This PR propose to separate matplotlib specific codes and plot core in Koalas:
- `databricks.koalas.plot.core`: other plot backends, the entry point of plotting, shared codes, etc.
- `databricks.koalas.plot.matplotlib`:  `matplotlib` specific codes
> Separate matplotlib specific codes and plot core in main codes

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
When use `tail()`, the result is not correct after modifying the data.
```python
>>> kdf = ks.DataFrame({"A": [1, 2, 3]})
>>> kdf.tail(2)
A
1  2
2  3
>>> (kdf + 1).tail(2)
A
1  2
2  3
>>> (kdf.to_pandas() + 1).tail(2)
A
1  3
2  4
```
This should resolve #1941
> Fix tail to use the resolved copy

- databricks/koalas/tests/plot/__init__.py
- databricks/koalas/tests/plot/test_frame_plot_plotly.py
- databricks/koalas/tests/plot/test_series_plot_plotly.py
This PR adds the basic test cases for ploting with plotly backends.
> Add plotly backend test cases

- databricks/koalas/accessors.py
- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_namespace.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
Manages index spark columns instead of index spark column names as the same as data spark columns.
> Manage index spark columns instead of index spark column names.

- databricks/koalas/groupby.py
`DataFrameGroupBy.describe` uses `reset_index()` internally, but we can avoid using it and so unnecessary default index attachment.
> Avoid unneeded reset_index in DataFrameGroupBy.describe.

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
Implement DataFrame.swapaxes
```
...     [[1, 2, 3], [4, 5, 6], [7, 8, 9]], index=['x', 'y', 'z'], columns=['a', 'b', 'c']
... )
>>> kdf
a  b  c
x  1  2  3
y  4  5  6
z  7  8  9
>>> kdf.swapaxes()
x  y  z
a  1  4  7
b  2  5  8
c  3  6  9
>>> kdf.swapaxes(i=1, j=0)
x  y  z
a  1  4  7
b  2  5  8
c  3  6  9
>>> kdf.swapaxes(i=1, j=1)
a  b  c
x  1  2  3
y  4  5  6
z  7  8  9
```
> Implement DataFrame.swapaxes

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/indexing.rst
Added `to_list` - `tolist` as an alias - to the Index and MultiIndex.
This implementation idea is basically inspired from `Series.to_list`.
```python
>>> idx = ks.Index([1, 2, 3, 4, 5])
>>> idx.to_list()
[1, 2, 3, 4, 5]
>>> tuples = [(1, 'red'), (1, 'blue'), (2, 'red'), (2, 'green')]
>>> midx = ks.MultiIndex.from_tuples(tuples)
>>> midx.to_list()
[(1, 'red'), (1, 'blue'), (2, 'red'), (2, 'green')]
```
> Implemented to_list to Index/MultiIndex

- databricks/koalas/indexes.py
- databricks/koalas/series.py
Fix `Series._to_internal_pandas` to reuse the previous result, and introduce `Index._to_internal_pandas`.
> Fix Series._to_internal_pandas and introduce Index._to_internal_pandas.

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- docs/source/reference/frame.rst
Compute the matrix multiplication between the DataFrame and other **series only**.
```
>>> kdf = ks.DataFrame([[0, 1, -2, -1], [1, 1, 1, 1]])
>>> kser = ks.Series([1, 1, 2, 1])
>>> kdf.dot(kser)
0   -4
1    5
dtype: int64
Note how shuffling of the objects does not change the result.
>>> kser2 = kser.reindex([1, 0, 2, 3])
>>> kdf.dot(kser2)
0   -4
1    5
dtype: int64
```
> Implement DataFrame.dot supporting Series parameter

- docs/source/getting_started/install.rst
- requirements-dev.txt
- setup.py
This was caused from https://github.com/databricks/koalas/commit/c7b69799ea3b03343d85bceb4008bc1915b7decb. On Ubuntu 18, seems like there's a problem about packaging PIL (Pillow) somewhere, see also `https://github.com/spotify/dh-virtualenv/issues/273`.
From matplotlib 3.3.0, they started to use Pillow dependency (matplotlib/matplotlib@370e9a2#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7)
This PR simply works around for now by setting uppberbound of matplotlib.
Resolves #1958
> Set upperbound of matplotlib to avoid failure on Ubuntu

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
This PR proposes `GroupBy.tail()` for `DataFrameGroupBy` and `SeriesGroupBy`.
```python
>>> df = ks.DataFrame({'a': [1, 1, 1, 1, 2, 2, 2, 3, 3, 3],
...                    'b': [2, 3, 1, 4, 6, 9, 8, 10, 7, 5],
...                    'c': [3, 5, 2, 5, 1, 2, 6, 4, 3, 6]},
...                   columns=['a', 'b', 'c'],
...                   index=[7, 2, 4, 1, 3, 4, 9, 10, 5, 6])
>>> df
a   b  c
7   1   2  3
2   1   3  5
4   1   1  2
1   1   4  5
3   2   6  1
4   2   9  2
9   2   8  6
10  3  10  4
5   3   7  3
6   3   5  6
>>> df.groupby('a').tail(2).sort_index()
a  b  c
1  1  4  5
4  1  1  2
4  2  9  2
5  3  7  3
6  3  5  6
9  2  8  6
>>> df.groupby('a')['b'].tail(2).sort_index()
1    4
4    1
4    9
5    7
6    5
9    8
Name: b, dtype: int64
```
> Implemented GroupBy.tail

- .github/workflows/master.yml
Since pandas 1.1.5 was released, we should match the behavior to the latest version.
https://pandas.pydata.org/docs/whatsnew/v1.1.5.html
> Upgrade pandas version in CI

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
ref #1929
```
>>> df = ks.DataFrame({'num_legs': [4, 2], 'num_wings': [0, 2]},
...                   index=['dog', 'hawk'])
>>> df
num_legs  num_wings
dog          4          0
hawk         2          2
>>> for row in df.itertuples():
...     print(row)
...
Koalas(Index='dog', num_legs=4, num_wings=0)
Koalas(Index='hawk', num_legs=2, num_wings=2)
```
> Implement DataFrame.itertuples

- databricks/koalas/base.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/utils.py
Currently Koalas can't handle index operations very well.
```py
>>> kidx = ks.Index([1, 2, 3, 4, 5])
>>> kidx + kidx
Int64Index([2, 4, 6, 8, 10], dtype='int64')
>>> kidx + kidx + kidx
...
AssertionError: args should be single DataFrame or single/multiple Series
```
or
```py
>>> ks.Index([1, 2, 3, 4, 5]) + ks.Index([6, 7, 8, 9, 10])
...
AssertionError: args should be single DataFrame or single/multiple Series
```
This PR enables those operations:
```py
>>> kidx + kidx + kidx
Int64Index([3, 6, 9, 12, 15], dtype='int64')
>>> ks.Index([1, 2, 3, 4, 5]) + ks.Index([6, 7, 8, 9, 10])
Int64Index([7, 9, 13, 11, 15], dtype='int64')
```
> Enable index operations.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
Enable Series.compare to compare Series from the same anchor 
Preivous behavior:
```
>>> kser = ks.Series([1, 2])
>>> kser.compare(kser)
...
AssertionError: We don't need to combine. `this` and `that` are same.
>>> kser.compare(kser + 1)
...
AssertionError: We don't need to combine. `this` and `that` are same.
```
Current behavior:
```
>>> kser = ks.Series([1, 2])
>>> kser.compare(kser)
Empty DataFrame
Columns: [self, other]
Index: []
>>> kser.compare(kser + 1)
self  other
0     1      2
1     2      3
```
> Compare Series from the same anchor

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
This PR proposes `GroupBy.median()`.
Note: the result can be slightly different from pandas since we use an approximated median based upon approximate percentile computation because computing median across a large dataset is extremely expensive.
```python
>>> kdf = ks.DataFrame({'a': [1., 1., 1., 1., 2., 2., 2., 3., 3., 3.],
...                     'b': [2., 3., 1., 4., 6., 9., 8., 10., 7., 5.],
...                     'c': [3., 5., 2., 5., 1., 2., 6., 4., 3., 6.]},
...                    columns=['a', 'b', 'c'],
...                    index=[7, 2, 4, 1, 3, 4, 9, 10, 5, 6])
>>> kdf
a     b    c
7   1.0   2.0  3.0
2   1.0   3.0  5.0
4   1.0   1.0  2.0
1   1.0   4.0  5.0
3   2.0   6.0  1.0
4   2.0   9.0  2.0
9   2.0   8.0  6.0
10  3.0  10.0  4.0
5   3.0   7.0  3.0
6   3.0   5.0  6.0
>>> …
```
> Implemented GroupBy.median()

- databricks/koalas/tests/test_series.py
Since #1712, Koalas is able to support non-names Series.
So now we can remove the comment from related test.
> Removed comment for Series.rename test

- postBuild
We should set `PYARROW_IGNORE_TIMEZONE` environment variable for binder; otherwise it shows a warning:
> Set PYARROW_IGNORE_TIMEZONE for binder.

- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
Hi, this PR would close #1907.
> Fix DataFrame.replace with NaN/None values #1907

- databricks/koalas/frame.py
- databricks/koalas/tests/test_stats.py
Some statistic functions fail if there are no numeric columns.
```py
>>> kdf = ks.DataFrame({"A": pd.date_range("2020-01-01", periods=3), "B": pd.date_range("2021-01-01", periods=3)})
>>> kdf.mean()
...
ValueError: Current DataFrame has more then the given limit 1 rows. Please set 'compute.max_rows' by using 'databricks.koalas.config.set_option' to retrieve to retrieve more than 1 rows. Note that, before changing the 'compute.max_rows', this operation is considerably expensive.
```
The functions which allow non-numeric columns by default are:
- `count`
- `min`
- `max`
> Fix stat functions with no numeric columns.

- databricks/koalas/config.py
- databricks/koalas/plot/core.py
This PR proposes to simplify plot implementation. Current Koalas implementation attempts to map the argument between other plotting backends (e.g., matplotlib vs plotly). Keeping this map is a huge maintenance cost and it's unrealistic to track their change and keep updating this map.
Pandas itself does not keep this map either:
```python
>>> pd.DataFrame([1,2,3]).plot.line(logx=1)
<AxesSubplot:>
>>> pd.options.plotting.backend = "plotly"
>>> pd.DataFrame([1,2,3]).plot.line(logx=1)
File "/.../opt/miniconda3/envs/python3.8/lib/python3.8/site-packages/pandas/plotting/_core.py", line 1017, in line
return self(kind="line", x=x, y=y, **kwargs)
File …
```
> Simplify plot backend support

- databricks/koalas/plot/core.py
- databricks/koalas/plot/plotly.py
- databricks/koalas/tests/plot/test_frame_plot_plotly.py
- databricks/koalas/tests/plot/test_series_plot_plotly.py
This PR implements `DataFrame.plot.pie` in plotly as below:
```python
kdf = ks.DataFrame(
{'a': [1, 2, 3, 4, 5, 6],
'b': [100, 200, 300, 400, 500, 600]},
index=[10, 20, 30, 40, 50, 60])
ks.options.plotting.backend = 'plotly'
kdf.plot.pie(y="b")
```
Binder to test: https://mybinder.org/v2/gh/HyukjinKwon/koalas/plotly-pie?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb
> Implement (DataFrame|Series).plot.pie in plotly

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_stats.py
Refines `DataFrame/Series._reduce_for_stat_function` to avoid special handling based on a specific function.
Also:
- Consolidates the implementations of `count` and support `numeric_only` parameter.
- Adds argument type annotations.
> Refine Frame._reduce_for_stat_function.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_stats.py
Adds `min_count` parameter for `Frame.sum`.
> Add min_count parameter for Frame.sum.

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_series.py
Fixes `DataFrame/Series/GroupBy.cumsum` and `cumprod`.
> Fix cumsum and cumprod.

- databricks/koalas/generic.py
- databricks/koalas/tests/test_stats.py
Fixes `Frame.abs` to support bool type and disallow non-numeric types.
> Fix Frame.abs to support bool type and disallow non-numeric types.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_stats.py
Refines `DataFrame/Series.product` to:
- Consolidate and reuse `_reduce_for_stat_function`.
- Support `axis`, `numeric_only`, and `min_count` parameters.
- Enable to calculate values including negative values or zeros.
> Refine DataFrame/Series.product.

- databricks/koalas/series.py
The build failed due to conflicts between recent PRs.
```
flake8 checks failed:
./databricks/koalas/series.py:5741:45: F821 undefined name 'BooleanType'
if isinstance(kser.spark.data_type, BooleanType):
^
./databricks/koalas/series.py:5750:45: F821 undefined name 'BooleanType'
if isinstance(self.spark.data_type, BooleanType):
^
```
> Fix the build error.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_stats.py
Refines `DataFrame/Series.quantile` to:
- Reuse `_reduce_for_stat_function` when `q` is `float`.
- Consolidate the logic when `q` is `Iterable`.
Also support `numeric_only` for `DataFrame`.
> Refine DataFrame/Series.quantile.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_stats.py
Supports `ddof` parameter for `Frame.std` and `var`.
> Support ddof parameter for std and var.

- databricks/koalas/testing/utils.py
Fixed several wrong condition in `if` statement for `assertPandasAlmostEqual`.
> Fix wrong condition for assertPandasAlmostEqual in tests util.

- databricks/koalas/extensions.py
- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Support to set attributes for DataFrame.
```py
>>> kdf = ks.DataFrame({'A': [1, 2, 3, None]})
>>> kdf.A = kdf.A.fillna(kdf.A.median())
>>> kdf
A
0  1.0
1  2.0
2  3.0
3  2.0
```
> Support to set attributes for DataFrame.

- databricks/koalas/frame.py
- databricks/koalas/series.py
This is a follow-up of #1989.
There are some more places where setting attributes with the overwritten `DataFrame.__setattr__`.
> Use object.__setattr__ in Series.

- docs/source/user_guide/types.rst
Added note about missing support for mixed type to documents.
Resolves #1981
> Add note about missing mixed type support to docs

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
Added missing parameter `ddof` for `GroupBy.std()` and `GroupBy.var()`.
```python
...     {
...         "a": [1, 2, 6, 4, 4, 6, 4, 3, 7],
...         "b": [4, 2, 7, 3, 3, 1, 1, 1, 2],
...         "c": [4, 2, 7, 3, None, 1, 1, 1, 2],
...         "d": list("abcdefght"),
...     },
...     index=[0, 1, 3, 5, 6, 8, 9, 9, 9],
... )
>>> kdf
a  b    c  d
0  1  4  4.0  a
1  2  2  2.0  b
3  6  7  7.0  c
5  4  3  3.0  d
6  4  3  NaN  e
8  6  1  1.0  f
9  4  1  1.0  g
9  3  1  1.0  h
9  7  2  2.0  t
>>> kdf.groupby("a").std(ddof=1)
b         c
a
7       NaN       NaN
6  4.242641  4.242641
1       NaN       NaN
3       NaN       NaN
2       NaN       NaN
4  1.154701  1.414214
>>> kdf.groupby("a").std(ddof=0)
b    c
a
7  0.000000  0.0
6  3.000000  3.0
1  0.000000  0.0
3 …
```
> Added ddof parameter for GroupBy.std() and GroupBy.var()

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
Currently, Series.mode reserves the name of Series in the result, whereas pandas Series.mode doesn't:
```
>>> kser1
x    1
y    2
Name: z, dtype: int64
>>> kser1.mode()
0    1
1    2
Name: z, dtype: int64. # Reserve name
>>> pser1 = kser1.to_pandas()
>>> pser1.mode()
0    1
1    2
dtype: int64. # Not reserve name
```
In addition, unit tests are added.
> Adjust Series.mode to match pandas Series.mode

- requirements-dev.txt
The current test cases are being failed as below, 
```
E           xlrd.biffh.XLRDError: Excel xlsx file; not supported
```
https://github.com/databricks/koalas/pull/1997/checks?check_run_id=1675264925
I referred to https://stackoverflow.com/questions/65254535/xlrd-biffh-xlrderror-excel-xlsx-file-not-supported
> Set upperbound xlrd<2.0.0 to fix read_excel test cases

- databricks/koalas/plot/matplotlib.py
- databricks/koalas/tests/plot/test_frame_plot_matplotlib.py
- databricks/koalas/tests/plot/test_series_plot_matplotlib.py
This PR optimizes histogram plot in Koalas by unioning the transformed results and making it single pass.
Previously, when the `DataFrame.plot.hist` is called, each column had to trigger each job.
Now, we can do it in single pass even for `DataFrame`s.
I also tested that it still result same:
> Optimize histogram calculation as a single pass

- databricks/koalas/base.py
- databricks/koalas/indexes.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/utils.py
Supports operations between `Series` and `Index`.
```py
>>> kser = ks.Series([1, 2, 3, 4, 5, 6, 7])
>>> kidx = ks.Index([0, 1, 2, 3, 4, 5, 6])
>>> (kser + 1 + 10 * kidx).sort_index()
0     2
1    13
2    24
3    35
4    46
5    57
6    68
dtype: int64
>>> (kidx + 1 + 10 * kser).sort_index()
0    11
1    22
2    33
3    44
4    55
5    66
6    77
dtype: int64
```
> Support operations between Series and Index.

- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
- databricks/koalas/plot/plotly.py
- databricks/koalas/tests/plot/test_frame_plot.py
- databricks/koalas/tests/plot/test_frame_plot_plotly.py
- databricks/koalas/tests/plot/test_series_plot.py
- databricks/koalas/tests/plot/test_series_plot_plotly.py
This PR implements `(DataFrame|Series).plot.hist` in plotly:
This can be tested via: https://mybinder.org/v2/gh/HyukjinKwon/koalas/plotly-histogram?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb
Example:
```python
ks.options.plotting.backend = "plotly"
kdf = ks.DataFrame({
'a c': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
'b': [2, 3, 4, 5, 7, 9, 10, 15, 10, 20, 20]
})
(kdf + 100).plot.hist()
pd.options.plotting.backend = "plotly"
pdf = pd.DataFrame({
'a c': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
'b': [2, 3, 4, 5, 7, 9, 10, 15, 10, 20, 20]
})
(pdf + 100).plot.hist()
```
NOTE that the output is a bit different because:
- We use Spark for histogram calculation and it's a bit different from pandas'
- Histogram plot in plotly cannot be …
> Implement (DataFrame|Series).plot.hist in plotly

- databricks/koalas/internal.py
- databricks/koalas/tests/test_dataframe.py
For Spark < 3.0, when all the values in a column are nulls, it will be `None` regardless of its data type.
```py
>>> pdf = pd.DataFrame(
...             {
...                 "a": [None, None, None, "a"],
...                 "b": [None, None, None, 1],
...                 "c": [None, None, None] + list(np.arange(1, 2).astype("i1")),
...                 "d": [None, None, None, 1.0],
...                 "e": [None, None, None, True],
...                 "f": [None, None, None] + list(pd.date_range("20130101", periods=1)),
...             },
...         )
>>>
>>> kdf = ks.from_pandas(pdf)
>>> kdf.iloc[:-1]
a     b     c     d     e     f
0  None  None  None  None  None  None
1  None  None  None  None  None  None
2  None  None  None  None  None  None
```
whereas for pandas:
```py
>>> …
```
> Adjust data when all the values in a column are nulls.

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
ref #1929
```
>>> kser = ks.Series(['b', None, 'a', 'c', 'b'])
>>> codes, uniques = kser.factorize()
>>> codes
0    1
1   -1
2    0
3    2
4    1
dtype: int64
>>> uniques
Index(['a', 'b', 'c'], dtype='object')
>>> codes, uniques = kser.factorize(na_sentinel=None)
>>> codes
0    1
1    3
2    0
3    2
4    1
dtype: int64
>>> uniques
Index(['a', 'b', 'c', None], dtype='object')
>>> codes, uniques = kser.factorize(na_sentinel=-2)
>>> codes
0    1
1   -2
2    0
3    2
4    1
dtype: int64
>>> uniques
Index(['a', 'b', 'c'], dtype='object')
```
> Implement Series.factorize()

- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
- databricks/koalas/plot/plotly.py
This PR proposes:
- Remove `koalas_plotting_backends`. We don't currently have such mechanism like https://github.com/pandas-dev/pandas/commit/e9a60bbc4f70820630f12666c273d14bcf83f1a7
- Load and use plotting backend in the same way:
- If a plot module has `plot`, we use it after converting it to pandas instance.
- if a plot module has `plot_koalas` (Koalas' `matplotlib` and `plotly` modules for example), we just pass Koalas instances to plot.
Now `databricks.koalas.plot.plotly` and `databricks.koalas.plot.matplotlib` modules work like external plotting backends.
> Refactor to use one similar logic to call plot backends

- databricks/koalas/plot/plotly.py
- databricks/koalas/tests/plot/test_series_plot_plotly.py
This PR implements Series.plot.box with plotly. Note that DataFrame.plot.box is not already supported in Koalas yet.
This can be tested via the link: https://mybinder.org/v2/gh/HyukjinKwon/koalas/plot-box-ser?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb
Note that you should manually install plotly to test with mybinder above:
```
%%bash
pip install plotly
```
Example:
```python
ks.options.plotting.backend = "plotly"
kdf = ks.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
kdf.a.plot.box()
pd.options.plotting.backend = "plotly"
pdf = pd.DataFrame({"a": [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
pdf.a.plot.box()
```
For the same reason as …
> Implement Series.plot.box with plotly

- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
This PR moves core computation logic (in kde) from matplotlib module to core module in plot.
> Extract kde computing logic from matplotlib

- databricks/koalas/base.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
Fix `as_spark_type` to not support "bigint".
The string "bigint" is not recognizable by `np.dtype` and it causes an unexpected error:
```py
>>> from databricks.koalas.typedef import as_spark_type
>>> as_spark_type(np.dtype("datetime64[ns]"))
...
TypeError: data type "bigint" not understood
```
Also, it doesn't work in pandas:
```py
>>> pd.Series([1, 2, 3], dtype="bigint")
...
TypeError: data type "bigint" not understood
```
> Fix as_spark_type to not support "bigint".

- databricks/koalas/extensions.py
- databricks/koalas/tests/test_extension.py
- databricks/koalas/typedef/typehints.py
Now that `as_spark_type` is good enough for Koalas, we should reuse it in `infer_pd_series_spark_type` to avoid inconsistency.
> Reuse as_spark_type in infer_pd_series_spark_type.

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
- docs/source/reference/io.rst
This PR proposes `ks.read_orc` to support creating `DataFrame` from ORC file.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_orc.html#pandas.read_orc
```python
>>> ks.read_orc("example.orc")
i32  i64    f  bhello
0    0    0  0.0  people
>>> pd.read_orc("example.orc")
i32  i64    f  bhello
0    0    0  0.0  people
>>> ks.read_orc("example.orc", columns=["i32", "f"])
i32    f
0    0  0.0
>>> pd.read_orc("example.orc", columns=["i32", "f"])
i32    f
0    0  0.0
>>>
```
> Implemented ks.read_orc

- databricks/koalas/frame.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
- docs/source/reference/io.rst
This PR proposes `DataFrame.to_orc` to write the ORC file.
pandas doesn't support this, but we do provide it for convenience, though.
> Implemented DataFrame.to_orc

- requirements-dev.txt
- setup.py
This PR is for quickly fix the `mypy` test failure to unblock other PRs caused by NumPy 1.20.0 release.
This upper bound should be removed again when finishing & merging #2026
> Set upperbounds numpy to fix CI failure

- databricks/koalas/__init__.py
- databricks/koalas/frame.py
- databricks/koalas/indexes/__init__.py
- databricks/koalas/indexes/base.py
- databricks/koalas/indexes/datetimes.py
- databricks/koalas/indexes/multi.py
- databricks/koalas/indexes/numeric.py
- databricks/koalas/internal.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/usage_logging/__init__.py
- docs/source/reference/indexing.rst
- setup.py
Adds `Int64Index`, `Float64Index`, and `DatetimeIndex` as a placeholder.
We should still add specific attributes and methods in the following PRs.
Before:
```py
>>> kdf = ks.DataFrame([1,2,3])
>>> type(kdf.index)
<class 'databricks.koalas.indexes.Index'>
```
After:
```py
>>> type(kdf.index)
<class 'databricks.koalas.indexes.numeric.Int64Index'>
```
> Add Int64Index, Float64Index, DatetimeIndex.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_stats.py
Preserves `index` for statistical functions with `axis==1`.
```py
...     {
...         "A": [1, -2, 3, -4, 5],
...         "B": [1.0, -2, 3, -4, 5],
...         "C": [-6.0, -7, -8, -9, 10],
...         "D": [True, False, True, False, False],
...     },
...     index=[10, 20, 30, 40, 50]
... )
>>> kdf.count(axis=1)
10    4
20    4
30    4
40    4
50    4
dtype: int64
```
whereas:
```py
>>> ks.set_option("compute.shortcut_limit", 2)
>>> kdf.count(axis=1)
0    4
1    4
2    4
3    4
4    4
dtype: int64
```
After:
```py
>>> ks.set_option("compute.shortcut_limit", 2)
>>> kdf.count(axis=1)
10    4
20    4
30    4
40    4
50    4
dtype: int64
```
> Preserve index for statistical functions with axis==1.

- databricks/koalas/typedef/typehints.py
Use `iloc` in `infer_pd_series_spark_type` to make sure it retrieves the first element.
Before:
```py
>>> infer_pd_series_spark_type(pd.Series(['a','b','c'], index=[10,20,30]))
...
KeyError: 0
```
After:
```py
>>> infer_pd_series_spark_type(pd.Series(['a','b','c'], index=[10,20,30]))
StringType
```
Note that currently the function in only called from `InternalFrame.from_pandas` which always resets index before calling it.
> Use iloc to make sure it retrieves the first element.

- databricks/koalas/generic.py
- databricks/koalas/tests/test_stats.py
Fix the `numeric_only` parameter for statistical functions to follow pandas.
> Fix numeric_only to follow pandas.

- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
- databricks/koalas/plot/plotly.py
- databricks/koalas/tests/plot/test_frame_plot_plotly.py
- databricks/koalas/tests/plot/test_series_plot_plotly.py
This PR implements (DataFrame|Series).plot.kde with Plotly:
Can be tested here:
http://mybinder.org/v2/gh/hyukjinkwon/koalas/plotly-kde?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb
**matplotlib**:
```python
ks.options.plotting.backend = "matplotlib"
kdf = ks.DataFrame({
'a': [1, 2, 2.5, 3, 3.5, 4, 5],
'b': [1, 2, 3, 4, 5, 6, 7],
'c': [0.5, 1, 1.5, 2, 2.5, 3, 3.5]})
kdf.plot.kde(bw_method=3).figure.savefig("fig1_mat.png")
kdf.a.plot.kde(bw_method=3).figure.savefig("fig2_mat.png")
```
**plotly**
```python
ks.options.plotting.backend = "plotly"
kdf = ks.DataFrame({
'a': [1, 2, 2.5, 3, 3.5, 4, 5],
'b': [1, 2, 3, 4, 5, 6, 7],
'c': [0.5, 1, 1.5, 2, 2.5, 3, 3.5]})
kdf.plot.kde(bw_method=3).write_image("fig1.png") …
```
> Implement (DataFrame|Series).plot.kde with Plotly

- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_stats.py
The package `pd.util.testing` is deprecated. We should use `pd.testing` instead.
> Avoid deprecated testing APIs.

- databricks/koalas/base.py
- databricks/koalas/tests/test_series.py
Fixes `Series.astype(str)` for some data types.
```py
>>> ks.Series([1,2,None,4]).astype(str)
0     1.0
1     2.0
2    None
3     4.0
dtype: object
>>> ks.Series([True, False, None], name="x").astype(str)
0     true
1    false
2     None
Name: x, dtype: object
>>> ks.Series(["2020-10-27 00:00:01", None], name="x").astype("M").astype(str)
0    2020-10-27 00:00:01
1                   None
Name: x, dtype: object
```
whereas with pandas:
```py
>>> pd.Series([1,2,None,4]).astype(str)
0    1.0
1    2.0
2    nan
3    4.0
dtype: object
>>> pd.Series([True, False, None], name="x").astype(str)
0     True
1    False
2     None
Name: x, dtype: object
>>> pd.Series(["2020-10-27 00:00:01", None], name="x").astype("M").astype(str)
0    2020-10-27 00:00:01
1                    NaT
Name: x, dtype: object …
```
> Fix astype(str) for some data types.

- databricks/koalas/base.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
The binary operations between `Index` and `Series` raise an error when the operations are on `Index` and `Series` in this order and the `Series` has no name.
```py
>>> ks.Index([1, 2, 3]) + ks.Series([10, 20, 30])
...
TypeError: object of type 'NoneType' has no len()
>>> ks.Index([1, 2, 3]) - ks.Series([10, 20, 30])
...
TypeError: object of type 'NoneType' has no len()
>>> ks.Index([1, 2, 3]) / ks.Series([10, 20, 30])
...
TypeError: object of type 'NoneType' has no len()
>>> ks.Index([1, 2, 3]) * ks.Series([10, 20, 30])
...
TypeError: object of type 'NoneType' has no len()
```
Resolves #2045.
> Fix binary operations Index by Series.

- databricks/koalas/base.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
Fixed incompatible behavior for `pow` and `rpow`.
In pandas:
```python
>>> pd.Series([1, 2, 3]) ** np.nan
0    1.0
1    NaN
2    NaN
dtype: float64
>>> 1 ** pd.Series([np.nan, 2, 3])
0    1.0
1    1.0
2    1.0
dtype: float64
```
In Koalas:
```python
>>> ks.Series([1, 2, 3]) ** np.nan
0    NaN  # doesn't match
1    NaN
2    NaN
dtype: float64
>>> 1 ** ks.Series([np.nan, 2, 3])
0    NaN  # doesn't match
1    1.0
2    1.0
dtype: float64
```
> Fix bug on pow and rpow

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_namespace.py
Fix ks.broadcast by resolving copy before braodcast.
Before
```py
>>> kdf = ks.DataFrame({'a': [1], 'b':[2]})
>>> kdf
a  b
0  1  2
>>> kdf.columns = ['c', 'd']
>>> ks.broadcast(kdf)
...
pyspark.sql.utils.AnalysisException: Cannot resolve column name "`c`" among (__index_level_0__, a, b);
```
After
```py
>>> kdf = ks.DataFrame({'a': [1], 'b':[2]})
>>> kdf
a  b
0  1  2
>>> kdf.columns = ['c', 'd']
>>> ks.broadcast(kdf)
c  d
0  1  2
```
> Resolve copy before broadcast

- .github/workflows/master.yml
Upgrade pandas version in CI since [pandas 1.2.2 was released](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.2.html)
> Upgrade pandas in CI

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/indexes/base.py
- databricks/koalas/indexes/multi.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/strings.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
- databricks/koalas/utils.py
Adds basic extension dtypes support.
The following types are supported if the underlying pandas supports them:
- pandas >= 0.24
- `Int8Dtype`
- `Int16Dtype`
- `Int32Dtype`
- `Int64Dtype`
- pandas >= 1.0
- `BooleanDtype`
- `StringDtype`
- pandas >= 1.2
- `Float32Dtype`
- `Float64Dtype`
Internally, `index_dtypes` and `data_dtypes` are introduced in `InternalFrame`.
```py
>>> kdf = ks.DataFrame({'a': [1,2,None,3], 'b': [4,5,6,None]}).astype({'a': 'Int32', 'b': 'Int64'})
>>> kdf
a     b
0     1     4
1     2     5
2  <NA>     6
3     3  <NA>
>>> kdf.dtypes
a    Int32
b    Int64
dtype: object
>>> kdf._internal.index_dtypes
[dtype('int64')]
>>> kdf._internal.data_dtypes
[Int32Dtype(), Int64Dtype()]
```
Currently binary operations and type casting are supported:
```py
>>> kdf.a + kdf.b
0       5 …
```
> Add basic extension dtypes support.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This should resolve #2055 
Before:
```python
...     {
...         "lkey": ["foo", "bar", "baz", "foo", "bar", "l"],
...         "rkey": ["baz", "foo", "bar", "baz", "foo", "r"],
...         "value": [1, 1, 3, 5, 6, 7],
...         "x": list("abcdef"),
...         "y": list("efghij"),
...     },
...     columns=["lkey", "rkey", "value", "x", "y"],
... )
>>> left_kdf = kdf[["lkey", "value", "x"]]
>>> right_kdf = kdf[["rkey", "value", "y"]]
>>> ks.merge(left_kdf, right_kdf, on="value")
...
pyspark.sql.utils.AnalysisException: Resolved attribute(s) y#801,rkey#798 missing from lkey#797,y#842,rkey#839,value#799L,__index_level_0__#837L,__natural_order__#808L,__natural_order__#836L,x#800,__index_level_0__#796L,value#840L in operator …
```
> Fix DataFrame.merge to work properly

- databricks/koalas/indexing.py
- databricks/koalas/tests/test_indexing.py
Here bool list-like column indicates  Python array, numpy array, and pandas Series.
Before:
```py
>>> kdf = ks.DataFrame({"a": [1, 2], "b": [3, 4], "c": [5, 6]}, index=["x", "y"])
>>> kdf
a  b  c
x  1  3  5
y  2  4  6
>>> kdf.loc[:, [True, False, True]]
...
KeyError: "['True'] not in index"
>>> kdf.loc[:, np.array([True, False, True])]
...
KeyError: "['True'] not in index"
>>> kdf.loc[:, pd.Series([True, False, True], index=['a', 'b', 'c'])]
...
KeyError: "['True'] not in index"
```
After:
```py
>>> kdf = ks.DataFrame({"a": [1, 2], "b": [3, 4], "c": [5, 6]}, index=["x", "y"])
>>> kdf
a  b  c
x  1  3  5
y  2  4  6
>>> kdf.loc[:, [True, False, True]]
a  c
x  1  5
y  2  6
>>> kdf.loc[:, …
```
> Support bool list-like column selection for loc indexer

- databricks/koalas/frame.py
- databricks/koalas/indexes/base.py
- databricks/koalas/indexes/datetimes.py
- databricks/koalas/indexes/multi.py
- databricks/koalas/indexes/numeric.py
Makes `Index` constructors follow pandas to create `Index` with the same signature as pandas'.
```py
>>> ks.Index([1, 2, 3])
Int64Index([1, 2, 3], dtype='int64')
>>> ks.Int64Index([1, 2, 3])
Int64Index([1, 2, 3], dtype='int64')
>>> ks.Float64Index([1.0, 2.0, 3.0])
Float64Index([1.0, 2.0, 3.0], dtype='float64')
>>> ks.DatetimeIndex(['1970-01-01', '1970-01-01', '1970-01-01'])
DatetimeIndex(['1970-01-01', '1970-01-01', '1970-01-01'], dtype='datetime64[ns]', freq=None)
```
> Make Index constructors follow pandas.

- databricks/koalas/base.py
- databricks/koalas/indexes/base.py
- databricks/koalas/indexes/datetimes.py
- databricks/koalas/indexes/numeric.py
- databricks/koalas/tests/test_indexes.py
Makes `Index `constructor take `Series` or `Index` objects.
```py
>>> kser = ks.Series([1, 2, 3], name="a", index=[10, 20, 30])
>>> ks.Index(kser)
Int64Index([1, 2, 3], dtype='int64', name='a')
>>> ks.Int64Index(kser)
Int64Index([1, 2, 3], dtype='int64', name='a')
>>> ks.Float64Index(kser)
Float64Index([1.0, 2.0, 3.0], dtype='float64', name='a')
>>> kser = ks.Series([datetime(2021, 3, 1), datetime(2021, 3, 2)], index=[10, 20])
>>> ks.Index(kser)
DatetimeIndex(['2021-03-01', '2021-03-02'], dtype='datetime64[ns]', freq=None)
>>> ks.DatetimeIndex(kser)
DatetimeIndex(['2021-03-01', '2021-03-02'], dtype='datetime64[ns]', freq=None)
```
> Make Index constructor take Series or Index objects.

- .github/workflows/master.yml
pandas 1.2.3 is released yesterday, so we should test this in CI.
[What's new in 1.2.3](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.3.html)
> Upgrade pandas to 1.2.3 for CI

- .github/workflows/master.yml
- databricks/conftest.py
- databricks/koalas/config.py
- databricks/koalas/plot/core.py
- databricks/koalas/tests/plot/test_frame_plot_matplotlib.py
- databricks/koalas/tests/plot/test_series_plot_matplotlib.py
- databricks/koalas/tests/test_series.py
- dev/gendoc.py
- dev/lint-python
- docs/source/conf.py
- docs/source/development/contributing.rst
- docs/source/user_guide/options.rst
- requirements-dev.txt
This PR proposes to switch the default plotly backend from matplotlib to plotly.
Resolves #1933
> Switch the default plotly backend from matplotlib to plotly

- databricks/koalas/accessors.py
- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes/base.py
- databricks/koalas/indexes/multi.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/mlflow.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/strings.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
Fixes to delegate dtypes properly.
The parameter `preserve_dtypes` for the workaround was removed.
Also maked as `TODO` where the dtypes are unknown.
> Fix to delegate dtypes.

- databricks/koalas/tests/indexes/__init__.py
- databricks/koalas/tests/indexes/test_base.py
- databricks/koalas/tests/indexes/test_datetime.py
Proposal: 
`databricks/koalas/tests/test_indexes.py` -> `databricks/koalas/tests/indexes/test_base.py`
Create `databricks/koalas/tests/indexes/test_datetime.py`
> Restructure the hierarchy of Index unit tests

- databricks/koalas/__init__.py
- databricks/koalas/indexes/datetimes.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/indexes/test_datetime.py
- databricks/koalas/tests/test_namespace.py
- docs/source/reference/general_functions.rst
```py
>>> ks.date_range(start='1/1/2018', end='1/08/2018')
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
'2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
dtype='datetime64[ns]', freq=None)
Specify `start` and `periods`, the number of periods (days).
>>> ks.date_range(start='1/1/2018', periods=8)
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
'2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
dtype='datetime64[ns]', freq=None)
```
Please note that currently, we cannot handle `freq` properly, this is a known issue.
> Implement ks.date_range()

- databricks/koalas/plot/core.py
- dev/tox.ini
Excludes docs/build from pycodestyle check; otherwise it fails with the following errors if there are documents built:
```
pycodestyle checks failed:
./docs/build/html/reference/api/databricks-koalas-DataFrame-plot-bar-4.py:9:5: E128 continuation line under-indented for visual indent
./docs/build/html/reference/api/databricks-koalas-DataFrame-plot-bar-4.py:10:5: E128 continuation line under-indented for visual indent
./docs/build/html/reference/api/databricks-koalas-DataFrame-plot-bar-4.py:11:5: E128 continuation line under-indented for visual indent
./docs/build/html/reference/api/databricks-koalas-Series-plot-bar-4.py:9:5: E128 continuation line under-indented for visual indent
./docs/build/html/reference/api/databricks-koalas-Series-plot-bar-4.py:10:5: E128 continuation line …
```
> Exclude docs/build from pycodestyle check.

- databricks/koalas/indexes/datetimes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/indexes/test_datetime.py
- docs/source/reference/indexing.rst
```py
>>> idx = ks.date_range(start='2014-08-01 10:00', freq='H', periods=3)
>>> idx.normalize()
DatetimeIndex(['2014-08-01', '2014-08-01', '2014-08-01'], dtype='datetime64[ns]', freq=None)
>>> idx = ks.date_range(pd.Timestamp("2018-03-10 09:00"), periods=3, freq='s')
>>> idx.strftime('%B %d, %Y, %r')  # doctest: +NORMALIZE_WHITESPACE
Index(['March 10, 2018, 09:00:00 AM', 'March 10, 2018, 09:00:01 AM',
'March 10, 2018, 09:00:02 AM'],
dtype='object')
```
> Implement DatetimeIndex.normalize() and DatetimeIndex.strftime()

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/tests/test_series.py
After the window functions, we should always resolve the `InternalFrame`; otherwise the window will be applied later, causing a weird behavior:
```py
>>> kdf = ks.DataFrame({"Col1": [10, 20, 15, 30, 45], "Col2": [13, 23, 18, 33, 48], "Col3": [17, 27, 22, 37, 52]})
>>> kdf
Col1  Col2  Col3
0    10    13    17
1    20    23    27
2    15    18    22
3    30    33    37
4    45    48    52
>>> kdf['Col1'].shift().loc[kdf['Col1'] == 20]
1   NaN
Name: Col1, dtype: float64
```
```py
>>> pdf = kdf.to_pandas()
>>> pdf['Col1'].shift().loc[pdf['Col1'] == 20]
1    10.0
Name: Col1, dtype: float64
```
Resolves #2078.
> Fix window functions to resolve.

- databricks/koalas/base.py
`MultiIndex.is_monotonic_increasing` and `MultiIndex.is_monotonic_decreasing` won't work in Koalas < 1.7.0 with PySpark 3.1.1 without disabling the `spark.sql.optimizer.nestedSchemaPruning.enabled`.
We should mention this to the docs.
> Add note to MultiIndex.is_monotonic*

- databricks/koalas/indexes/datetimes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/indexes/test_datetime.py
- docs/source/reference/indexing.rst
```py
>>> idx = ks.date_range(start='2018-01', freq='M', periods=3)
>>> idx.month_name()
Index(['January', 'February', 'March'], dtype='object')
>>> idx = ks.date_range(start='2018-01-01', freq='D', periods=3)
>>> idx.day_name()
Index(['Monday', 'Tuesday', 'Wednesday'], dtype='object')
```
> Implement DatetimeIndex.month_name() and DatetimeIndex.day_name()

- databricks/koalas/indexes/datetimes.py
Correction the type in docstring for `DatetimeIndex.month_names` from `Series` to `Index`.
> Fix type in docstring for DatatimeIndex.month_names

- databricks/koalas/config.py
- dev/gendoc.py
- docs/source/user_guide/options.rst
This clarifies a question raised in #2072 regarding the impact of max_rows on the size of dataframes/series received by function when using, e.g., `groupby` and `apply`, where the groups can exceed `compute.max_rows` rows.
> Add a note for GroupBy and compute.max_rows

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
pandas support `tuple` to `(DataFrame|Series).replace()` for parameter `to_replace` and `value` whereas Koalas doesn't.
We should follow pandas'
```python
>>> df_ks = ks.DataFrame([
...   [1,2,3],
...   [4,5,6],
...   [np.inf, 0, -np.inf]
... ])
>>> df_ks.replace((1, 2), np.nan)
0    1    2
0  NaN  NaN  3.0
1  4.0  5.0  6.0
2  inf  0.0 -inf
```
> Support tuple to (DataFrame|Series).replace()

- databricks/koalas/internal.py
Checks explicitly `index_dtype` and `data_dtypes` are the instance of `np.dtype` or `ExtensionDtype`.
> Check index_dtype and data_dtypes more strictly.

- databricks/koalas/indexes/datetimes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/indexes/test_datetime.py
- docs/source/reference/indexing.rst
Implement DatetimeIndex.indexer_between_time()
```py
>>> kidx = ks.date_range("2000-01-01", periods=3, freq="T")
>>> kidx 
DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 00:01:00',
'2000-01-01 00:02:00'],
dtype='datetime64[ns]', freq=None)
>>> kidx.indexer_between_time("00:01", "00:02").sort_values()
Int64Index([1, 2], dtype='int64')
>>> kidx.indexer_between_time("00:01", "00:02", include_end=False).sort_values()
Int64Index([1], dtype='int64')
>>> kidx.indexer_between_time("00:01", "00:02", include_start=False).sort_values()
Int64Index([2], dtype='int64')
```
> Implement DatetimeIndex.indexer_between_time()

- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- docs/source/user_guide/transform_apply.rst
Improve documentations of transform/apply functions.
Some transform/apply functions will add a default index when the given UDF has return type annotated. This PR raises users' attention on that.
> Improve documentations of transform/apply functions

- databricks/koalas/indexes/datetimes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/indexes/test_datetime.py
- docs/source/reference/indexing.rst
```py
>>> kidx = ks.date_range("2000-01-01", periods=3, freq="T")
>>> kidx
DatetimeIndex(['2000-01-01 00:00:00', '2000-01-01 00:01:00',
'2000-01-01 00:02:00'],
dtype='datetime64[ns]', freq=None)
>>> kidx.indexer_at_time("00:00")
Int64Index([0], dtype='int64')
>>> kidx.indexer_at_time("00:01")
Int64Index([1], dtype='int64')
```
> Implement DatetimeIndex.indexer_at_time()

- databricks/koalas/testing/utils.py
- databricks/koalas/tests/test_dataframe.py
We'd disable `check_freq` for checking the `freq` in `DatetimeIndex` because so far we don't provide `freq` in `DatetimeIndex`.
> Disable check_freq in testing util.

- databricks/koalas/generic.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_conversion.py
The current behaviour of Koalas is:
```python
pd.read_json(lines=True)
df.to_json(orient='records', lines=True)
```
This PR adds the arguments with pretty error messages.
> Add lines and orient to read_json and to_json to improve error message

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
`(Series|DataFrame).isin` don't work properly when passing numpy array as a parameter.
```python
>>> df = pd.DataFrame({'a': [1, 2, 3], 'b': [2, 3, 4]})
>>> numpy_arr = np.array([3, 4, 5])
>>> df['a'].isin(numpy_arr)
0    False
1    False
2     True
Name: a, dtype: bool
>>> kdf = ks.from_pandas(df)
>>> kdf[kdf['a'].isin(numpy_arr)]
...
AttributeError: 'numpy.int64' object has no attribute '_get_object_id'
```
This should resolve #2098
> Fix (DataFrame|Series).isin to pass numpy array

- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
Allow multi-index column names for inferring return type schema with names.
- Before
```py
>>> pdf = pd.DataFrame({("x", "a"): [1, 2, 3], ("y", "b"): [3, 4, 5]})
>>> def func() -> ks.DataFrame[zip(pdf.columns, pdf.dtypes)]:
...     pass
>>> infer_return_type(func).tpe
...
TypeError: not all arguments converted during string formatting
```
- After
```py
>>> pdf = pd.DataFrame({("x", "a"): [1, 2, 3], ("y", "b"): [3, 4, 5]})
>>> def func() -> ks.DataFrame[zip(pdf.columns, pdf.dtypes)]:
...     pass
>>> infer_return_type(func).tpe
StructType(List(StructField((x, a),LongType,true),StructField((y, b),LongType,true)))
```
> Allow multi-index column names for inferring return type schema with names.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
The UDF in DataFrame.between_time() was without return type hint, so the pandas shortcut was required to infer the return type. The PR is proposed to add type hint to the UDF in DataFrame.between_time().
> Save pandas shortcut of DataFrame.between_time()

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
Support `ExtensionDtype`s as type arguments by reusing `NameTypeHolder` for DataFrame's type annotation.
Also support to infer Spark DataType from the return type annotation with `ExtensionDtype`s.
Before:
```py
>>> ks.Series[pd.Int32Dtype()]
...
TypeError: Parameters to generic types must be types. Got Int32Dtype().
```
After:
```py
>>> ks.Series[pd.Int32Dtype()]
databricks.koalas.typedef.typehints.SeriesType[databricks.koalas.series.NameType]
>>> def a() -> ks.Series[pd.Int32Dtype()]:
...   pass
...
>>> infer_return_type(a)
SeriesType[IntegerType]
```
> Support ExtensionDtypes as type arguments.

- databricks/koalas/base.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
Introduce `koalas_dtype` to consolidate the logic to convert to dtype and Spark DataType.
> Introduce koalas_dtype to consolidate the logic to convert to dtype and Spark DataType.

- databricks/koalas/utils.py
Now that `as_spark_type` takes an argument `raise_error`, we don't need to use try-catch.
> Use raise_error=False instead of try-catch.

- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_typedef.py
- databricks/koalas/typedef/typehints.py
After the return type inference, `SeriesType`, `DataFrameType`, and `ScalarType` hold the dtypes as well as Spark DataTypes.
> Make SeriesType, DataFrameType, and ScalarType hold the dtypes as well.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_categorical.py
Fix groupby-apply and transform to support additional dtypes.
After this, additional dtypes can be specified in the return type annotation of the UDFs for groupby-apply and transform.
```py
...     {
...         "a": pd.Categorical([1, 2, 3, 1, 2, 3]),
...         "b": pd.Categorical(
...             ["b", "a", "c", "c", "b", "a"], categories=["c", "b", "d", "a"]
...         ),
...     },
... )
>>> def identity(df) -> ks.DataFrame[zip(kdf.columns, kdf.dtypes)]:
...     return df
...
>>> applied = kdf.groupby("a").apply(identity)
>>> applied
a  b
0  2  a
1  2  b
2  3  c
3  3  a
4  1  b
5  1  c
>>> applied.dtypes
a    category
b    category
dtype: object
```
FYI: without the fix:
```py
>>> applied
a  b
0  1  3
1  1  1
2  2  0
3  2  3
4  0  1
5  0  0
>>> …
```
> Fix groupby-apply and transform to support additional dtypes.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_categorical.py
Fix `DataFrame.apply` to support additional dtypes.
After this, additional dtypes can be specified in the return type annotation of the UDFs for `DataFrame.apply`.
```py
...     {"a": ["a", "b", "c", "a", "b", "c"], "b": ["b", "a", "c", "c", "b", "a"]}
... )
>>> dtype = pd.CategoricalDtype(categories=["a", "b", "c"])
>>> def categorize(ser) -> ks.Series[dtype]:
...     return ser.astype(dtype)
...
>>> applied = kdf.apply(categorize)
>>> applied
a  b
0  a  b
1  b  a
2  c  c
3  a  c
4  b  b
5  c  a
>>> applied.dtypes
a    category
b    category
```
FYI: without the fix:
```py
>>> applied
a  b
0  0  1
1  1  0
2  2  2
3  0  2
4  1  1
5  2  0
>>> applied.dtypes
a    int64
b    int64
dtype: object
```
> Fix DataFrame.apply to support additional dtypes.

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Please see change to implement `DataFrame.last` and `Series.last` functionality similar to that available in pandas. Requirement raised in issue: https://github.com/databricks/koalas/issues/1929
```python
>>> index = pd.date_range('2018-04-09', periods=4, freq='2D')
>>> ks_series = ks.Series([1, 2, 3, 4], index=index)
2018-04-09  1
2018-04-11  2
2018-04-13  3
2018-04-15  4
dtype: int64
>>> ks_series.last('3D')
2018-04-13  3
2018-04-15  4
dtype: int64
```
```python
>>> index = pd.date_range('2018-04-09', periods=4, freq='2D')
>>> pdf = pd.DataFrame({'A': [1, 2, 3, 4]}, index=i)
>>> kdf = fs.from_pandas(pdf)
A
2018-04-09  1
2018-04-11  2
2018-04-13  3
2018-04-15  4
>>> kdf.last('3D')
A
2018-04-13  3
2018-04-15  4      
```
> Implement `DataFrame.last` and `Series.last` functionality

- databricks/koalas/accessors.py
- databricks/koalas/tests/test_categorical.py
Fix `DataFrame.koalas.apply_batch` to support additional dtypes.
After this, additional dtypes can be specified in the return type annotation of the UDFs for `DataFrame.koalas.apply_batch`.
```py
...     {"a": ["a", "b", "c", "a", "b", "c"], "b": ["b", "a", "c", "c", "b", "a"]}
... )
>>> dtype = pd.CategoricalDtype(categories=["a", "b", "c", "d"])
>>> def to_category(pdf) -> ks.DataFrame["a": dtype, "b": dtype]:
...     return pdf.astype(dtype)
...
>>> applied = kdf.koalas.apply_batch(to_category)
>>> applied
a  b
0  a  b
1  b  a
2  c  c
3  a  c
4  b  b
5  c  a
>>> applied.dtypes
a    category
b    category
dtype: object
```
FYI: without the fix:
```py
>>> applied
a  b
0  0  1
1  1  0
2  2  2
3  0  2
4  1  1
5  2  0
>>> applied.dtypes
a    int64
b    int64
dtype: …
```
> Fix DataFrame.koalas.apply_batch to support additional dtypes.

- databricks/koalas/base.py
- databricks/koalas/tests/indexes/test_datetime.py
- databricks/koalas/tests/test_series_datetime.py
Standardize exceptions of arithmetic operations on Datetime-like data
> Standardize exceptions of arithmetic operations on Datetime-like data

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
```py
>>> idx = pd.date_range('2018-04-09', periods=4, freq='1D20min')
>>> kser = ks.Series([1, 2, 3, 4], index=idx)
>>> kser
2018-04-09 00:00:00    1
2018-04-10 00:20:00    2
2018-04-11 00:40:00    3
2018-04-12 01:00:00    4
dtype: int64
>>> kser.between_time('0:15', '0:45')
2018-04-10 00:20:00    2
2018-04-11 00:40:00    3
dtype: int64
```
> Implement Series.between_time()

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Please see change to implement DataFrame.first and Series.first functionality similar to that available in pandas. Requirement raised in issue: #1929
```python
>>> index = pd.date_range('2018-04-09', periods=4, freq='2D')
>>> ks_series = ks.Series([1, 2, 3, 4], index=index)
2018-04-09  1
2018-04-11  2
2018-04-13  3
2018-04-15  4
dtype: int64
>>> ks_series.first('3D')
2018-04-09  1
2018-04-11  2
dtype: int64
```
> Implement `DataFrame.first` and `Series.first` functionality

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
```py
>>> idx = pd.date_range('2018-04-09', periods=4, freq='12H')
>>> kser = ks.Series([1, 2, 3, 4], index=idx)
>>> kser
2018-04-09 00:00:00    1
2018-04-09 12:00:00    2
2018-04-10 00:00:00    3
2018-04-10 12:00:00    4
dtype: int64
>>> kser.at_time('12:00')
2018-04-09 12:00:00    2
2018-04-10 12:00:00    4
dtype: int64
```
> Implement Series.at_time()

- requirements-dev.txt
The `docutils==0.17` released on Apr 3 has a bug which cause the sphinx build failure.
- https://sourceforge.net/p/docutils/bugs/416/
> Pin docutils to 0.16.

- README.md
Since Koalas will be ported into Apache Spark, added note on `README.md` to notify this.
> Add note about the porting to README.md

- databricks/koalas/indexing.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- requirements-dev.txt
- setup.py
Fix several incompatible behavior with pandas in `iLocIndexer` to remove upperbound pandas 1.2.
> Remove upperbound pandas 1.2

- .github/workflows/master.yml
Try to fix unstable build by explicitly setting `SPARK_LOCAL_IP` env var.
https://github.com/databricks/koalas/runs/2297499540
```
java.net.BindException: Cannot assign requested address: Service 'sparkDriver' failed after 16 retries (on a random free port)! Consider explicitly setting the appropriate binding address for the service 'sparkDriver' (for example spark.driver.bindAddress for SparkDriver) to the correct binding address.
```
> Set SPARK_LOCAL_IP env var.

- databricks/koalas/__init__.py
Show a warning message to encourage to use `pyspark.pandas` when the underlying PySpark is 3.2 or above.
> Show a warning message to encourage to use pyspark.pandas.

- docs/source/user_guide/from_to_dbms.rst
- docs/source/user_guide/index.rst
> Add a short JDBC user guide

- .github/workflows/master.yml
pandas 1.2.4 has been released, so we should test this in CI.
- https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.2.4.html
> Upgrade pandas in CI to 1.2.4.

- databricks/koalas/tests/indexes/test_datetime.py
Removes duplicated test cases in `test_datetime.py`. https://github.com/apache/spark/pull/32139#discussion_r614125401
> Remove duplicated test cases in test_datetime.py

- docs/source/reference/indexing.rst
Remove the duplicated section title "Compatibility with MultiIndex" in the indexing document.
> Remove the duplicated section title in the indexing document

- .github/workflows/master.yml
- databricks/koalas/__init__.py
- databricks/koalas/tests/test_stats.py
- requirements-dev.txt
- setup.py
Removed the upperbound for `numpy`.
`numpy>=1.20` only works with `pyspark>=3.1`, so show a warning when `numpy>=1.20` with `pyspark<3.1` together.
> Remove the upperbound for numpy.

- .github/workflows/master.yml
- setup.py
`PySpark` 3.1 and above now supports Python 3.9.
We should add the CI and update the upperbound for Python.
> Allow Python 3.9 when the underlying PySpark is 3.1 and above.

- databricks/koalas/plot/plotly.py
- databricks/koalas/tests/plot/test_frame_plot_matplotlib.py
```python
ks.DataFrame({'a': [1, 2, 3], 'b':["a", "b", "c"], 'c': [4, 5, 6]}).plot(kind="hist", x="a", y="c", bins=200)
```
**Before:**
```
pyspark.sql.utils.AnalysisException: cannot resolve 'least(min(a), min(b), min(c))' due to data type mismatch: The expressions should all have the same type, got LEAST(bigint, string, bigint).;
'Aggregate [unresolvedalias(least(min(a#1L), min(b#2), min(c#3L)), Some(org.apache.spark.sql.Column$$Lambda$1556/0x0000000800d94840@42fb0cc1)), unresolvedalias(greatest(max(a#1L), max(b#2), max(c#3L)), Some(org.apache.spark.sql.Column$$Lambda$1556/0x0000000800d94840@42fb0cc1))]
+- Project [a#1L, b#2, c#3L]
+- Project [__index_level_0__#0L, a#1L, b#2, c#3L, monotonically_increasing_id() AS __natural_order__#8L]
+- LogicalRDD [__index_level_0__#0L, a#1L, b#2, …
```
> Support y properly in DataFrame with non-numeric columns with plots

- databricks/koalas/indexes/base.py
- databricks/koalas/tests/indexes/test_base.py
This PR basically came from [SPARK-35683](https://issues.apache.org/jira/browse/SPARK-35683).
This PR fix the wrong behavior of `Index.difference` in Koalas, based on the comment https://github.com/databricks/koalas/pull/1325#discussion_r647889901 and https://github.com/databricks/koalas/pull/1325#discussion_r647890007
- it couldn't handle the case properly when `self` is `Index` or `MultiIndex` and `other` is `MultiIndex` or `Index`.
```python
>>> midx1 = ks.MultiIndex.from_tuples([('a', 'x', 1), ('b', 'z', 2), ('k', 'z', 3)])
>>> idx1 = ks.Index([1, 2, 3])
>>> midx1 = ks.MultiIndex.from_tuples([('a', 'x', 1), ('b', 'z', 2), ('k', 'z', 3)])
>>> midx1.difference(idx1)
databricks.koalas.exceptions.PandasNotImplementedError: The method `pd.Index.__iter__()` is not implemented. If you want …
```
> Fix Index.difference to avoid collect 'other' to driver side

- databricks/koalas/internal.py
- databricks/koalas/typedef/typehints.py
In Python 3.5.2, errors as below are raised for `Dtype.__args__`. 
```py
databricks/koalas/internal.py
543             isinstance(dtype, Dtype.__args__)  # type: ignore
544             and (dtype == np.dtype("object") or as_spark_type(dtype, raise_error=False) is not None)
--> 545             for dtype in index_dtypes
546         ), index_dtypes
547 
AttributeError: type object 'Union' has no attribute '__args__'
```
We fix backward compatibility for Python version 3.5.* by introducing `DtypeDataTypes` with `__union_params__` for 3.5.0~3.5.2.
> Fix backward compatibility for Python version 3.5.*
