databricks/koala/__init__.py, setup.py
Spark is installed in many different ways in an environment.
Sometimes using Cloudera parcels, homebrew, binary zips, etc.
Getting the pypi spark package can make it complicated
as it is pulled during a pip install and can cause multiple
sparks to be installed by mistake, and even confuse the configs
to use - potentially breaking a system.
Move spark dependency in an extra in case a user needs us to
use pip to install spark for them. But in general avoid that.
=> setup: Make spark an extra-dependency

databricks/koala/selection.py, databricks/koala/tests/test_dataframe.py, databricks/koala/tests/test_indexing.py
Even if no index is provided, if there is no slice selection
provided in the Locator - it should work. As the index
is not required and can be anything.
Fixes https://github.com/databricks/spark-pandas/issues/55
=> [55] SparkDataFrameLocator: Allow locator with no index

databricks/koala/structures.py, databricks/koala/tests/test_dataframe.py
A DataFrame.abs() will go through all columns and apply abs()
on all the columns.
Minor differences:
- pd.DataFrame.abs() on int,float converts both columns to float
Here it retains the int type.
- pd.DataFrame.abs() on str or array throws error.
Here it will return a None for string. But throw an error for array.
=> _Frame: Add abs() for Series and DataFrame

.gitignore, databricks/koala/__init__.py, databricks/koala/groups.py, databricks/koala/metadata.py, databricks/koala/utils.py, dev/tox.ini
This PR fixes:
1. Duplicated `.idea/...` in `.gitignore`. That's covered by `.idea/`
2. `logging.warn` is deprecated from Python 3.3 as of `logging.warning`
3. Avoid wildcard imports
4. Remove `exclude` in `tox.ini` (that looks copied from Apache Spark side)
5. Remove unused imports.
=> Miscellaneous cleanups (avoid deprecated method, unused lines, styles)

databricks/koala/structures.py, databricks/koala/tests/test_dataframe.py
This pr adds `index` property for `DataFrame` and `Column`, which returns a `Column` representing the index column, whereas pandas returns `pd.Index` instead of `pd.Series`.
=> Add index property.

databricks/koala/structures.py, databricks/koala/tests/test_dataframe.py
The name of the result of `value_count` should be the column name, but was always `"count"`.
=> Fix value_count.

dev/run-tests.sh
Prior to #86, make `run-tests.sh` easier to use.
Currently we always need to define `SPARK_HOME` but it's not needed if the package is installed with `conda` or `pip`.
=> Make run-tests.sh easier to use.

databricks/koalas/tests/test_etl.py
This PR proposes to make `sample_stocks` data accessed by the path based on the Python script.
This is useful when to run tests via PyCharm:
Before:
After:
=> Fix EtlTest test able to run everywhere

.travis.yml
The PySpark `2.4.0` package is no longer available on the download mirrors.
=> Upgrade PySpark version for travis-ci.

.gitignore, .travis.yml, README.md, databricks/koalas/__init__.py, databricks/koalas/version.py, dev/lint-python, docs/Makefile, docs/conf.py, docs/databricks.koalas.rst, docs/index.rst, docs/make.bat, requirements-dev.txt, setup.py
This PR proposes to add a foundation for the documentation and API list for databricks.koalas (a.k.a Spark Pandas). This PR
1. Add `Makefile` and Sphinx configuration files to generate the documentation from docstrings.
2. Fix `.travis.xml` and `dev/lint-python` to test documentation generation.
3. Add `__version__` to `databricks.koalas.version` that is shared for `setup.py`, `conf.py` (for doc generation) and `databricks.koalas.__version__`. This hack is borrowed from PySpark approach.
4. Add `requirements-dev.txt` file so that it can be used in CI and dev guide.
5. Add some extra additional packages to generate docs that need to be installed:
- `nbsphinx` to allow Jupyter note books. Seems needing some more works to actually use it.
- `numpydoc` to allow `numpy` style docs (from Pandas …
=> Add Sphinx documentation generation foundation

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/namespace.py, databricks/koalas/selection.py, databricks/koalas/series.py
- Make `Series` not forget to take `index_info` over.
- currently `DataFrame.index` will remove the index info, but they are not taken over.
- Remove `_pandas_metadata` from `DataFrame`.
=> Refine metadata management.

README.md, docs/api.rst, docs/index.rst, docs/quickstart.rst
This PR add a simple quickstart that's almost copied from `README.md`.
Yes, we should deduplicate them eventually but I would like to propose to put them first.
=> Add a simple quickstart in Koalas documentation

requirements-dev.txt
I found this via readthedocs failure. I forgot to add this fix. It was tested against my fork:
https://github.com/HyukjinKwon/spark-pandas/commit/6969d7d87436d96b9039d852c6e4e7ff62965c98
https://databricks-koalas.readthedocs.io/en/latest/
=> Fix requirements-dev.txt to be compatible with both PIP and Conda

README.md
Reference:
- https://github.com/apache/arrow/issues/1125
- https://www.pyimagesearch.com/2019/01/30/macos-mojave-install-tensorflow-and-keras-for-deep-learning/
=> add cmake as dependency and note that `pip install arrow` does not work in python 3.7

README.md, databricks/koalas/dask/utils.py, docs/source/quickstart.rst
This partially addresses #158, just uses "ks" instead of "koalas" in `@derived_from` for docs.
The doctests issue mentioned in #158 will be addressed in the separate PR.
Also updated README and quickstart doc to use "ks".
=> Use "ks" for "koalas".

docs/source/themes/nature_with_gtoc/static/nature.css_t
This PR proposes to add a CSS property to allow word breaking when it's overlapped as below:
Before:
After:
Partially address #156
=> Add a CSS property for breakable words to avoid table text overlapped

README.md
The installation on Databricks is handled through installing the library from PyPi, not pip
=> Reference PyPi instead of pip

databricks/koalas/series.py, databricks/koalas/testing/doctest_main.py, dev/run-tests.sh
Enable doctests in `series.py` and make `run-tests.sh` handle doctest failures properly.
=> Enable more doctests in Series

databricks/koalas/series.py
This PR fixes a test failure in my local. I didn't investigate closely but I just suspect it's basically Python's float limitation https://docs.python.org/3/tutorial/floatingpoint.html _or_ some changes from Spark upstream (I was testing it with Apache Spark master)
```
**********************************************************************
File "/.../koalas/databricks/koalas/series.py", line 367, in series.Series.corr
Failed example:
s1.corr(s2, method='pearson')
Expected:
-0.8510644963469898
Got:
-0.8510644963469901
Failure
<Click to see difference>
**********************************************************************
File "/.../koalas/databricks/koalas/series.py", line 370, in series.Series.corr
Failed example:
s1.corr(s2, method='spearman')
Expected:
-0.9486832980505125
Got: …
```
=> Loosen DataFrame.corr test assertion for floats

databricks/koalas/frame.py, databricks/koalas/testing/utils.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_indexing.py
This PR resolves #192 by falling back to literal when it's not a column
```python
>>> pdf = pd.DataFrame([{'a': 1}, {'a': 1}, {'b': 2}])
>>> pdf
a    b
0  1.0  NaN
1  1.0  NaN
2  NaN  2.0
>>> pdf['w'] = 1
>>> pdf
a    b  w
0  1.0  NaN  1
1  1.0  NaN  1
2  NaN  2.0  1
>>> pdf['b'] = 1
>>> pdf
a  b  w
0  1.0  1  1
1  1.0  1  1
2  NaN  1  1
```
Before:
```python
>>> kdf = ks.DataFrame([{'a': 1}, {'a': 1}, {'b': 2}])
>>> kdf
a    b
0  1.0  NaN
1  1.0  NaN
2  NaN  2.0
IndentationError: unexpected indent
>>> kdf['w'] = 1
File "/.../koalas/databricks/koalas/frame.py", line 656, in __setitem__
kdf = self.assign(**{key: value})
File "/.../koalas/databricks/koalas/frame.py", line 335, in assign
sdf = sdf.withColumn(name, c)
File …
```
=> Allow the direct assignment for scalar value

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/typedef.py, databricks/koalas/typing.py
PySpark without arrow execution sometimes fails to infer data type.
This PR uses pyarrow infer prior to create DataFrame.
Closes #167.
=> Use pyarrow to infer data type.

databricks/koalas/frame.py, databricks/koalas/tests/test_stats.py
This patch implements DataFrame.count based on Pandas' syntax. In this PR, DataFrame.count returns a pd.Series, rather than a ks.Series.
In the future, we should look into what we do with Inf and -Inf values, and Series.count.
Resolves #184
=> DataFrame.count()

databricks/koalas/__init__.py, databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
Introduces a new method to_koalas that can be used to convert a Spark DataFrame into a Koalas DataFrame. This method is monkey patched into Spark dynamically when the koalas package is imported.
Resolves #175
=> spark.DataFrame.to_koalas()

.readthedocs.yml
Somehow type hint isn't recognized in readthedocs build with Python 3.5. This PR simply bumps up the Python version to 3.6.
https://github.com/databricks/koalas/commit/0470b24b895c7e80fa1dd300837c9d2d234252e4
It was tested in readthedocs.
Resolves #198
=> Use Python 3.6 in readthedocs build

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe_conversion.py
This patch inlines to_html docs from pandas, and supports limit push down when max_rows is specified, so we don't need to pull in all the data.
=> Support limit push down in to_html

databricks/koalas/frame.py, databricks/koalas/tests/test_utils.py, databricks/koalas/utils.py
This patch adds validate_arguments_and_invoke_function for compatibility with older pandas versions. It is currently used in to_html, but I think we can apply that to a lot of other functions too.
=> validate_arguments_and_invoke_function

databricks/koalas/frame.py
Mistakenly used Pandas DF in doctests. Spark converts `np.nan` into `None`. This is a general issue so it's avoided in the doctest, for now.
=> Fix doctest in sort_values to use Koalas DF and avoid NaN

databricks/koalas/frame.py, databricks/koalas/tests/test_stats.py
In pandas it is possible to sum over boolean values which are implicitly converted to integers. For example, the following code can be used to compute to number of NA values per column.
```python
>>> df = pd.DataFrame({'A': [0, np.nan, np.nan], 'B': [0, 0, np.nan]})
>>> df.isna().sum()
A    2
B    1
dtype: int64
```
When trying to run the same code with a Koalas DataFrame, the following exception is thrown: `org.apache.spark.sql.AnalysisException: cannot resolve 'sum(`A`)' due to data type mismatch: function sum requires numeric types, not boolean`
To fix this, the PR casts boolean values to integers as required when using statistical functions. Furthermore, the unit tests have been extended to cover the following statistics with boolean values:
- min
- max
- sum
- mean
- var
- std
=> Enable statistics for boolean values

databricks/koalas/series.py, databricks/koalas/tests/test_stats.py
As requested in #218 by @rxin, this PR now also supports statistics for *Series* with boolean values. Like before,  all relevant functionality is covered with unit tests.
=> Support statistical functions for Series with boolean values

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, docs/source/reference/frame.rst, docs/source/reference/series.rst
This PR adds to_dict in DataFrame and Series.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html#pandas.DataFrame.to_dict
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.to_dict.html#pandas.Series.to_dict
=> Add to_dict in DataFrame and Series

databricks/koalas/series.py, databricks/koalas/tests/test_series_string.py
This PR updates `__add__` and `__radd__` functions to handle string concatenation. Before this patch, when adding two string columns or string column and literal, you get `None`, because the library would use Spark columns addition.
I updated the function to use `concat` Spark SQL function instead, this applies for cases of two columns or column and literal. Added unit tests to verify the intended behaviour.
Pandas does not support 'str' + 'int' or 'int' + 'str', or other cross types additions; so I only added handling for strings.
> `__add__` function became a bit messy, because of that check. Also I found that error messages are not consistent between Koalas and Pandas when it comes to adding columns of different types.
Fixes #219
=> Fix string addition for Koalas Series

databricks/koalas/frame.py, databricks/koalas/metadata.py, databricks/koalas/series.py, requirements-dev.txt
Currently Python 3.5 build in travis-ci is not working properly since the Python is upgraded while setting up the environment because the dev dependency is strictly versioned but some of them depends only Python 3.6 or upper.
E.g., this (https://travis-ci.com/databricks/koalas/jobs/197751790) is the 3.5 build, but we can see:
=> Fix python 3.5 build.

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
We should preserve group keys as indices of the result `DataFrame` when `groupby(...).agg(...)`.
=> Preserve group keys as indices when `groupby(...).agg(...)`.

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/typedef.py, requirements-dev.txt
Looks we can remove `decorator` dependency. This library looks not that much popular (https://github.com/micheles/decorator) and also every usecase seems able to be rewritten Python-natively.
=> Remove decorator dependency

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
This PR adds a `columns` parameter to the DataFrame's `drop()` method that behaves exactly like the corresponding parameter in pandas. While it is certainly a matter of taste, I prefer writing `df.drop(columns=['y', 'z'])` over `df.drop(['y', 'z'], axis=1)` and appreciate having compatible APIs between pandas and Koalas. Apart from implementing the described functionality, the PR adds docstests and makes sure no existing tests fail.
=> Add 'columns' parameter to DataFrame's drop method

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series.py, databricks/koalas/tests/test_utils.py, databricks/koalas/utils.py
1. Fixed the bug that `DataFrame. __repr__` was turning the entire DataFrame into pandas DataFrame, rather than simply taking the top 1000 rows.
2. Added a cache so repeated calls of repr and repr_html don't trigger multiple Spark actions. But then I undid that because cache invalidation is difficult. I did leave some of the infrastructure still in place and added test cases to make sure repr and repr_html are correct when it comes to cache invalidation, if we ever implement any form of caching.
=> repr and repr_html improvements

requirements-dev.txt, setup.py
Although `pyarrow==0.10` says numpy minimum version is `1.10.0`, it does not work properly with `numpy<0.14`, so we should explicitly specify the numpy minimum version. This is related to #252.
=> Explicitly specify numpy minimum version.

databricks/koalas/frame.py, databricks/koalas/series.py
This PR targets to inline Series.unique to Pandas'. After this PR:
**Pandas**
```python
>>> pd.DataFrame({"Person": ['a', 'b', 'b', 'c']})
Person
0      a
1      b
2      b
3      c
>>> df = pd.DataFrame({"Person": ['a', 'b', 'b', 'c']})
>>> df.unique()
File "/usr/local/lib/python3.7/site-packages/pandas/core/generic.py", line 4376, in __getattr__
return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'unique'
>>> df.Person.unique()
array(['a', 'b', 'c'], dtype=object)
```
**Koalas**
```python
>>> ks.DataFrame({"Person": ['a', 'b', 'b', 'c']})
Person
0      a
1      b
2      b
3      c
>>> df = ks.DataFrame({"Person": …
```
=> Inline Series.unique to Pandas'

databricks/koalas/__init__.py, databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/tests/test_stats.py, databricks/koalas/typedef.py, docs/source/reference/general_functions.rst
This revamps and significantly improves / simplifies the pandas wrapper (which is a much more flexible pandas udf wrapper). The exact naming of some of the content like `pandas_wrap` or `Col` can be debated. See the docstring examples for usage and motivation.
=> Revamp the UDF wrapper to make it more usable

requirements-dev.txt, setup.py
This is a follow-up of #260.
The minimum version should've been `1.14`.
=> Fix minimum numpy version.

databricks/koalas/exceptions.py, databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py
This PR adds the basic [merge](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html) functionality from pandas to Koalas DataFrames as requested in #232. While the PR does not cover 100% of pandas' functionality, it covers the basic use cases to be useful enough to start with.
Resolves #232
=> Add basic merge functionality to DataFrame

databricks/koalas/__init__.py, databricks/koalas/missing/series.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/typedef.py, docs/source/reference/general_functions.rst
This PR adds `apply` to Series. It works identically with Pandas except that Koalas requires to add a type hint to the input `func`'s return type.
```python
>>>
>>> pser = pd.Series([20, 21, 12], index=['London', 'New York', 'Helsinki'])
>>> kser = ks.Series(pser)
>>> def square(x) -> np.int64:
...     return x ** 2
...
```
```
>>> kser.apply(square)
London      400
New York    441
Helsinki    144
Name: square(0), dtype: int64
```
```
>>> pser.apply(square)
London      400
New York    441
Helsinki    144
dtype: int64
```
While I am here,
- I renamed `pandas_wrap` -> `pandas_wraps` just to match with `functools.wraps`.
- Addressed few nits.
=> Add Series.apply

CONTRIBUTING.md
Let's add sdist in the PyPI distribution.
Seems like sdist will be needed for conda-forge repository.
=> Add sdist in the PyPI distribution.

.travis.yml, requirements-dev.txt, setup.py
After new version of Spark 2.4 was released, we might be able to remove maximum pyarrow version boundary.
This PR is to add a new env for travis-ci to see whether it works or not.
=> Add a new env for travis-ci.

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/metadata.py, databricks/koalas/ml.py, databricks/koalas/selection.py, databricks/koalas/series.py, databricks/koalas/typedef.py
This PR:
- adds documentation at `Metadata` with some doctests.
- renames:
- `all_fields` -> `columns`
- `index_fields` -> `index_columns`
- `column_fields` -> `data_columns`
- `index_names` -> `index_names` (no change)
- `index_info` -> `index_map`
I tried to keep the original intention and avoid name conflict between field and column.
Also, `index_info` -> `index_map`, for now (see https://github.com/databricks/koalas/pull/290#issuecomment-491450583)
- fixes a bug (one line fix) at `set_index`:
```python
kdf = ks.DataFrame({
'A': [1, 2, 3, 4],
'B': [5, 6, 7, 8],
'C': [9, 10, 11, 12],
'D': [13, 14, 15, 16],
'E': [17, 18, 19, 20]})
kdf1 = kdf.set_index("A")
kdf1.to_spark().show()
```
```
Failed example:
kdf1.to_spark().show()  # doctest: +NORMALIZE_WHITESPACE
Expected: …
```
=> Cleanup metadata and add documentations for it

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe_conversion.py, docs/source/reference/frame.rst
=> DataFrame.to_json

.travis.yml, databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe_conversion.py, databricks/koalas/tests/test_series_conversion.py, databricks/koalas/tests/test_utils.py, databricks/koalas/utils.py, docs/source/reference/frame.rst, docs/source/reference/series.rst
Add `DataFrame.to_clipboard` and `Series.to_clipboard`. Part of #169.
Improve `validate_arguments_and_invoke_function()`  when receiving argument `**kwargs`
+ actual args : `{'kwargs': {'index': False}, 'sep': ',', 'excel': True}`
+ expected args : `{'sep': ',', 'excel': True, 'index': False}`
=> DataFrame.to_clipboard & Series.to_clipboard

databricks/koalas/frame.py
These two methods were previously missing examples and were also using the old doc style.
=> Improve docs for DataFrame.reset_index / set_index

databricks/koalas/frame.py, databricks/koalas/series.py
Avoid defining them twice by just setting `Series.to_clipboard.__doc__ = DataFrame.to_clipboard.__doc__`.
Also added skip doctest since those tests are not verified anyway.
=> Define to_clipboard doc only once

databricks/koalas/exceptions.py, databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
As requested in #264, this PR removes the specific `SparkPandasMergeError` and replaces its usage with the more generic `ValueError`.
=> Remove SparkPandasMergeError

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_repr.py, databricks/koalas/tests/test_series.py
This PR uses regular expressions at `repr` and `_repr_html_` to show "showing only the first ..."
**`repr`**:
DataFrame:
```python
>>> ks.range(2000)
```
```
id
0      0
1      1
...
998  998
999  999
[Showing only the first 1000 rows x 1 columns]
```
```python
>>> ks.range(500)
```
```
...
499  499
[500 rows x 1 columns]
```
Series:
```python
>>> ks.DataFrame({'a': [1] * 1000}).a
```
```
998    1
999    1
Name: a, Length: 1000, dtype: int64
```
```python
>>> ks.DataFrame({'a': [1] * 1001}).a
```
```
...
998    1
999    1
Name: a, Length: 1000, dtype: int64
Showing only the first 1000
```
**`_repr_html_`**:
DataFrame
```python
>>> print(ks.range(2000)._repr_html_())
```
```
<div>
<style scoped>
...
</style>
<table …
```
=> Show "showing only the first ..." at repr and _repr_html_

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series.py
This PR adds pandas' `clip()` method to Koalas Series and DataFrames.
For reference:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.clip.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip.html
=> Add clip method to Koalas Series and DataFrames

databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
+ Implementation of `Series.fillna()` #308 
+ Docstring with examples
=> Series.fillna

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/indexing.py, databricks/koalas/series.py, databricks/koalas/tests/test_indexing.py, docs/source/reference/series.rst
Basic things in this PR is to add docstring, but additionally some refinement around `.loc`:
- move `selection.SparkDataFrameLocator` to `indexing.LogIndexer` to follow pandas style.
- refactor variable names.
Resolves #320.
=> Add docs for `.loc` and refine.

databricks/koalas/namespace.py
If we use `ks` namespace, it fails for unknown reason. Since the release is close, I am proposing to fix it first.
```
AttributeError: module 'databricks.koalas' has no attribute 'DataFrame'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-3464524554752451> in <module>()
----> 1 import databricks.koalas
/databricks/python/lib/python3.5/site-packages/databricks/koalas/__init__.py in <module>()
36 assert_pyspark_version()
37 
---> 38 from databricks.koalas.namespace import *
39 from databricks.koalas.frame import DataFrame
40 from databricks.koalas.series import Series
/databricks/python/lib/python3.5/site-packages/databricks/koalas/namespace.py in <module>()
34 
35 
---> 36 def …
```
=> Use imported Series and DataFrame directly in namespace.py

databricks/koalas/frame.py, docs/source/reference/frame.rst
Resolves #319.
The current implementation is going to blow up on large data, and for now we should just remove it. We can add it back when we have a better way to do this. One way to do this is through toLocalIterator, but it's still a bad practice in general.
=> Remove DataFrame.__iter__

dev/lint-python
Seems like previously generated rst files (under api) matters in doc generation when new entry is added.
```
reading sources... [100%] reference/series
Warning, treated as error:
autodoc: failed to import method 'DataFrame.__iter__' from module 'databricks.koalas'; the following exception was raised:
File "/usr/local/lib/python3.7/site-packages/sphinx/util/inspect.py", line 177, in safe_getattr
return getattr(obj, name, *defargs)
AttributeError: type object 'DataFrame' has no attribute '__iter__'
During handling of the above exception, another exception occurred:
File "/usr/local/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 271, in import_object
obj = attrgetter(obj, attrname)
File …
```
=> Cleanup previously generated rst files

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/series.py, docs/source/reference/frame.rst
This PR adds `DataFrame.astype`.
Resolves #339
=> Add DataFrame.astype

databricks/koalas/__init__.py, databricks/koalas/namespace.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_namespace.py, docs/source/reference/general_functions.rst
This PR adds base of ks.concat. There are still many parameters to implement existent in Pandas'
Resolves #231
=> Add koalas.concat

databricks/koalas/missing/series.py, databricks/koalas/series.py, docs/source/reference/series.rst
This is an alias of Series.dtype.
=> Add Series.dtypes

README.md
Now that Koalas is listed on the conda-forge repository.
This PR adds the instruction to install Koalas by conda.
=> Add conda instruction.

databricks/koalas/datetimes.py, databricks/koalas/generic.py, databricks/koalas/series.py, databricks/koalas/tests/test_series_datetime.py, databricks/koalas/typedef.py, docs/source/reference/series.rst
1. rename `datetime.py` to `datetimes.py` to match with Pandas'
2. Add some missing docstrings that has some examples
3. `lazy_property` -> `property`. I don't feel strongly but let's use `lazy_property` when it's really needed .. :-)..
4. Add the original name of the returned series.
5. Add a couple of minor tests and type hints.
=> Cleanup and inline documentation of dt functions to Pandas'

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, docs/source/reference/frame.rst, docs/source/reference/series.rst
This PR adds `DataFrame.describe()` and `Series.describe()` with basic stats for numeric types.
Resolves #334.
=> Add basic describe() function.

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
This PR improves `merge` function:
- add `left_on` and `right_on`
- fix index management
but still have some TODOs:
- in some case, indexes can be retained
- when `left_index=True` and `right_index=True` for multi-index, the behavior is not the same as pandas'
I'd leave them to the future work.
Resolves #354.
=> Improve merge function.

dev/lint-python
This PR simply modifies the *lint-python* script to run mypy before sphinx. My rationale behind this is that the mypy check fails much more often than sphinx, while the latter takes comparably long to run. Running mypy first thus leads to faster feedback and therefore increased development speed.
=> Run mypy before sphinx test

docs/source/reference/frame.rst
I've just seen that both #264 and #381 missed adding `DataFrame.merge` to the .rst doc files. Therefore, this PR simply adds the missing entry.
=> Add DataFrame.merge to frame.rst

.travis.yml, CONTRIBUTING.md, requirements-dev.txt
This PR proposes to test `pip` at Python 3.5. We provide a `requirement-dev.txt` file that can be used at both `pip` and `conda`.
This is because:
**1. We should test `pip` compatibility of `requirement-dev.txt` file:**
We met the compatibility issue before at https://github.com/databricks/koalas/pull/154. We can prevent this via running it in Travis CI.
**2. One of the dependency in Koalas, `mlflow` requires Python 3.6 specifically in Conda:**
mlflow requires Python 3.6+ if we use conda
```
conda install -c conda-forge --yes mlflow
Collecting package metadata: done
Solving environment: failed
SpecsConfigurationConflictError: Requested specs conflict with configured specs.
requested specs:
- mlflow
pinned specs:
- python=3.5
Use 'conda config --show-sources' to look for 'pinned_specs' and …
```
=> Test requirement-dev.txt against pip as well in CI

databricks/koalas/frame.py, databricks/koalas/series.py
This PR adds to the existing `Dataframe.describe` method the `percentiles` optional parameter.
=> Add percentiles to describe

databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
This PR adds `Series.map`.  If the function is given as an argument, seems we can just reuse `apply`.
```python
>>> pdf = pd.DataFrame({'a': [1,2,3,4,5,6]})
>>> pdf.a.apply(lambda x: x+  1)
0    2
1    3
2    4
3    5
4    6
5    7
Name: a, dtype: int64
>>> pdf.a.map(lambda x: x+  1)
0    2
1    3
2    4
3    5
4    6
5    7
Name: a, dtype: int64
```
=> Add Series.map

docs/source/reference/ml.rst
I think we can put the api doc for mlflow related APIs in the same api directory, otherwise we need to add the directory to `.gitignore`.
Also we can remove the package prefix because `currentmodule` is specified.
I checked the generated docs in my local.
=> Modify ml module doc.

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, docs/source/reference/frame.rst
This PR adds DataFrame.`applymap`.
We can reuse `Series.apply`:
```python
>>> pd.DataFrame({'a': [1,2,3], 'b': [1.0, 2.0, 3.0]})
a    b
0  1  1.0
1  2  2.0
2  3  3.0
>>> pdf = pd.DataFrame({'a': [1,2,3], 'b': [1.0, 2.0, 3.0]})
>>> pdf.applymap(lambda x: x + 1)
a    b
0  2  2.0
1  3  3.0
2  4  4.0
```
=> Add DataFrame.applymap

databricks/koalas/generic.py, databricks/koalas/indexing.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/series.py, databricks/koalas/tests/test_indexing.py, docs/source/reference/frame.rst, docs/source/reference/series.rst
As requested in #382, this PR implements pandas' `.at` property for Koalas DataFrames and Series.
=> Implement .at property for Koalas DataFrames and Series

databricks/koalas/datetimes.py, databricks/koalas/series.py, docs/source/reference/series.rst, docs/source/themes/nature_with_gtoc/static/nature.css_t
This PR targets to inline Datetimelike accessor documentation to Pandas'
The problem was that it seems like we can't access property's property (`Series.dt.date` for instance).
I mimicked Pandas' approach (class attribute -> property). Plus, it will cache once it's called. 
Another problem was that the table is located in the center. I don't know why there's difference so I just edited CSS to make the tables alined left like Pandas'. I think it's hacky way to fix.
**Pandas:**
**After this PR:**
=> Inline Datetimelike accessor documentation to Pandas'

requirements-dev.txt
Now that Sphinx on PyPI was upgraded to `2.1.0`, but it raises unknown warnings.
I'd fix the Sphinx version to `2.0.1` for now to unblock PRs.
=> Fix Sphinx version to `2.0.1`.

databricks/koalas/base.py, databricks/koalas/tests/test_series.py
This PR keep original names from isna, isnull, notnull, notna. Keeping expression name as is can cause analysis exceptions due to nested `` ` `` in the name for instance.
Resolves #406
=> Keep column name from isna, isnull, notnull, notna

requirements-dev.txt
Now that MLflow on PyPI was upgraded to 1.0.0, but it has API breaking changes.
I'd fix the MLflow version to 0.9.1 for now to unblock PRs.
=> Fix MLflow version to `0.9.1`.

databricks/koalas/missing/series.py, databricks/koalas/series.py
This seems virtually an alias of `Series.apply` (if it's in Series). I revised the doc a bit so that it can be used in DataFrames too in the future.
Also, `transform` can take a list of functions that return a dataframe.
=> Add Series.transform

databricks/koalas/namespace.py, docs/source/reference/io.rst
This PR adds a couple of basic read function wrappers of pandas' corresponding to `to_xxx()` wrappers:
- `read_clipboard()`
- `read_excel()`
- `read_html()`
=> Add basic read function wrappers.

.travis.yml, requirements-dev.txt
Currently travis ignores the pip/conda installation error.
=> Modify `.travis.yml` to notify the installation error.

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
This is a follow-up of #388.
We can skip index level check and integrity verification when `ignore_index` is True.
=> Skip index check when `ignore_index` is True.

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe_conversion.py, docs/source/reference/frame.rst
As discussed in #415, this PR adds pandas' `DataFrame.from_records()` method to Koalas.
=> Add from_records()

docs/source/reference/frame.rst, docs/source/reference/general_functions.rst, docs/source/reference/io.rst, docs/source/reference/ml.rst, docs/source/reference/series.rst
I changed all top level headers to use `-` rather than a mixture of `-` and `~`, which was error prone and had a few mistakes. As part of this, I also up-leveled Series.dt and Series.str, to make them show up in the table of contents on the left side so it is easier to find.
=> Make reference doc header consistent

databricks/koalas/frame.py, databricks/koalas/namespace.py, databricks/koalas/tests/test_dataframe_conversion.py, databricks/koalas/tests/test_dataframe_spark_io.py, docs/source/reference/frame.rst, docs/source/reference/io.rst
=> ks.read_spark_io / DataFrame.to_spark_io

databricks/koalas/tests/test_dataframe_spark_io.py
This is a follow-up of #449.
The test `DataFrameSparkIOTest.test_table()` needs a clean-up.
=> Clean up after test_table.

requirements-dev.txt
This PR sets the numpydoc version to 0.8. Seems like NumPy 0.9.x has a bug about documentation generation.
It took me a while .. so I would like to leave three notes I learnt while debugging this:
- readthedoc caches installed package and we don't specify the version. So, once 0.8.0 is installed, it can be unable to reproduce in the same code base.
- readthedoc uses different command to build sphinx (not like ours). We use `make clean` but sphinx uses `python sphinx-build`:
```
python /home/docs/checkouts/readthedocs.org/user_builds/koalas/envs/stable/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```
this ignores our `-W` option and `PYTHONPATH` in Makefile. There might be some more diff.
- v0.2.0 doc is fine …
=> Set numpydoc to 0.8

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/tests/test_stats.py
Solves #280 
Ensure stats functions other than min/max/count are applied on numeric/boolean columns only by default.
=> Stats on numeric columns

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
As discussed in #438, this PR correctly retains the indices of the merged DataFrames.
Resolves #438.
=> Correctly retain indices for DataFrame.merge()

databricks/conftest.py
I use Spark upstream (3.0.0) in dev to pre-test and find any issue. This PR makes Koalas testing working with Spark upstream (3.0.0).
Currently, it fails even when I test other APIs like:
```
./dev/pytest -k read_parquet --doctest-modules databricks
```
=> Make tests runnable with Spark 3.0 (changing Detla Scala version for Spark 3.0.0+)

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/mlflow.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/typedef.py
This is part of #322.
This PR removes setters for old metadata structures and refine constructors for `DataFrame` and `Series` to avoid using old metadata structures.
Closes #468.
=> Remove setters for old metadata.

databricks/koalas/missing/series.py
```python
>>> pd.Series([1,2,3]).itemsize
__main__:1: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
8
```
```python
>>> pd.Series([1,2,3]).argmax
<bound method Series.idxmax of 0    1
1    2
2    3
dtype: int64>
>>> pd.Series([1,2,3]).argmax()
2
```
```python
>>> pd.Series([1,2,3]).data
__main__:1: FutureWarning: Series.data is deprecated and will be removed in a future version
<memory at 0x1191d8288>
```
=> Minor fixes about deprecation and properties in _MissingPandasLikeSeries

databricks/koalas/datetimes.py
This is a followup for #478. Inline the documentation and doctests.
=> Add docstring and doctests for new dt APIs

databricks/koalas/strings.py, databricks/koalas/tests/test_series_string.py, databricks/koalas/typedef.py, docs/source/reference/series.rst
As discussed in #281, this PR completes most of the remaining Series.str functions for manipulating strings in Koalas Series.
Functions not implemented:
* `cat()` - returns scalar string, not a Koalas series
* `decode()`, `encode()` - BinaryType not supported in pyspark < 2.4
* `extract()`, `extractall()` - returns dataframe of varying dimensions
* `partition()`, `rpartition()`- returns dataframe of varying dimensions
* `get_dummies()` - returns dataframe of varying dimensions
=> Remaining Koalas Series.str functions

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
+ Initial implementation of `DataFrame.pivot_table()`
+ Ignored parameters : `margins`, `dropna` and `margins_name`
+ Resolves #382
=> DataFrame.pivot_table

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
This PR adds nunique in groupby.agg:
```
df.groupby('x').agg({'y': 'nunique'})
```
Resolves #506
=> Support nunique in groupby.agg

databricks/koalas/exceptions.py, databricks/koalas/generic.py, databricks/koalas/missing/__init__.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/groupby.py, databricks/koalas/missing/indexes.py, databricks/koalas/missing/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_groupby.py, databricks/koalas/tests/test_indexes.py, databricks/koalas/tests/test_series.py
This PR proposes to add a reason for unsupported functions.
While I am here,
- `values` at Series, Index, DataFrame were moved into missing package with the reason.
- `to_pickle` at DataFrame
=> Add reason for unsupported functions

databricks/koalas/__init__.py, databricks/koalas/frame.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, databricks/koalas/typedef.py
This PR proposes an alternative take for https://github.com/databricks/koalas/pull/437. The main diff is that:
- In python 3.7, hacks `__class_getitem__` from `Generic` at `DataFrame`. Here, it just wraps the given types into a tuple type, which is existing variadic generic.
- In python 3.6 and python 3.5, similarly it wraps by a tuple type too; however, the logic is defined in metaclass. So, it should be wrapped in a different way from python 3.7's
<br/>
<br/>
<br/>
Looks we need a way to specify type hint in order for them to be set when we run Python native functions via, for instance, `apply(func)`. For `DataFrame`, `groupby(..).apply(func)` needs it if we implement it. Consider this example:
```python
def func(pdf) -> DataFrame[...]
return pdf
df.groupby.apply(func)
```
We already …
=> Add Series[T] and DataFrame[T, ...] type hint

.travis.yml
This PR merges the codecov results from different runs caused by the Travis matrix.
See https://docs.codecov.io/docs/merging-reports
=> Merge codecov reports

.travis.yml, databricks/conftest.py, databricks/koalas/frame.py, databricks/koalas/mlflow.py, databricks/koalas/plot.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series_plot.py
Currently only the travis build with Python 3.5 is supposed to use the older versions of pandas and pyarrow, but the 3.5 build doesn't work with the older versions because the libraries are not pinned and the newest versions are used since the 3.5 build uses `pip` instead of `conda`.
As as result, we missed the failures with pandas 0.23.
Resolves #525.
=> Fix build with pandas 0.23.

databricks/koalas/tests/test_series_plot.py
When we use Pandas 0.23.x, seems it sets the color for each bar as below:
whereas Koalas' creates as below:
Seems it creates the same color as Koalas' from Pandas 0.24.x. So seems we're fine here since we follow higher versions of Pandas.
In order to make the tests passed with Pandas 0.23.X too, it explicitly sets the color so that image binary comparison can be done. After this PR:
Can be checked via:
```python
pdf = ks.range(1002).to_pandas()
from matplotlib import pyplot as plt
kdf = ks.range(1002)
pdf = ks.range(1002).to_pandas()
_, ax1 = plt.subplots(1, 1)
ax1 = pdf['id'][:1000].plot.bar(colormap='Paired')
ax1.text(1, 1, 'showing top 1,000 elements only', size=6, ha='right', va='bottom',
transform=ax1.transAxes)
_, ax2 = …
```
=> Set the color explicitly in plot.bar tests

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Fix for replace to add support for the mapping case as referenced in #495 :
`kdf.replace({0: 10, 1: 100})`
=> Updated frame.replace()

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
This PR adds `DataFrame.pivot`.
This is basically same as `pivot_table(aggfunc='first', ...)`.
There are two differences between pandas' `pivot` and `pivot` proposed here to Koalas.
- `values` is required due to support multi index as columns unlike pandas'. This is followup work.
```python
>>> import as pd
>>> df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
...                            'two'],
...                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
...                     'baz': [1, 2, 3, 4, 5, 6],
...                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
>>> df.pivot(index="foo", columns="bar")
baz       zoo
bar   A  B  C   A  B  C
foo
one   1  2  3   x  y  z
two   4  5  6   q  w  t
>>> df.pivot(index="foo", columns="bar").columns
MultiIndex(levels=[['baz', …
```
=> Add DataFrame.pivot

databricks/koalas/missing/series.py
This PR adds a reason for to_pickle not being supported. We won't add to_pickle.
=> Add a reason for unsupported to_pickle in Series as well

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/series.py, docs/source/reference/frame.rst, docs/source/reference/series.rst
This PR adds all and any in DataFrame
Also, this PR fixes `Series.quantile` working with Spark 2.3 by avoiding to use `arrays_zip` expression.
=> Add all and any in DataFrame

databricks/koalas/missing/common.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/indexes.py, databricks/koalas/missing/series.py, databricks/koalas/tests/test_indexes.py
This PR proposes:
1. Mark deprecated APIs (per https://pandas.pydata.org/pandas-docs/stable/search.html?q=&check_keywords=yes&area=default# )
2. Don't explicitly support some APIs virtually similar with what we don't support.
=> Triage Series/DataFrame/Index/GroupBy APIs not to support

databricks/koalas/frame.py, databricks/koalas/series.py
This PR proposes to avoid to use to_dataframe in Series.rank to keep anchor. Currently. `Series.rank` has https://github.com/databricks/koalas/issues/405 issue as well because it converts Spark column into DataFrame within Series API.
=> Avoid to use to_dataframe in Series.rank to keep anchor

.travis.yml
Seems like conda is trying to deploy 4.7.10 as a default.
It's time to revisit the conda 4.7 build.
Resolves #508.
=> Try conda 4.7.

databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
This PR adds `Series.idxmax()` and `Series.idxmin()` and mark deprecated equivalent APIs `Series.argmax()` and `Series.argmin()`.
=> Add Series.idxmax() and Series.idxmin()

databricks/koalas/typedef.py
With Python 3.5.2, Koalas DataFrame type hint is being failed:
```python
df = ks.DataFrame({'A': 'a a b'.split(),
'B': [1, 2, 3],
'C': [4, 6, 5]}, columns=['A', 'B', 'C'])
g = df.groupby('A')
def pandas_div_sum(x) -> ks.DataFrame[float, float]:
return x[['B', 'C']] / x[['B', 'C']].sum()
g.apply(pandas_div_sum)
```
```
Traceback (most recent call last)
<command-3464524554752451> in <module>()
8 def pandas_div_sum(x) -> ks.DataFrame[float, float]:
9    return x[['B', 'C']] / x[['B', 'C']].sum()
---> 10 g.apply(pandas_div_sum)
/databricks/python/lib/python3.5/site-packages/databricks/koalas/usage_logging/__init__.py in wrapper(*args, **kwargs)
129             start = time.perf_counter()
130             try:
--> 131                 res = …
```
=> Use __tuple_params__ instead of __args__ for Python 3.5.2

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Fix complex multi-index column access for something like:
```py
>>> pdf
a  c  e              i
g
d  f
b              h
0  1  a  x  10  100  1000
1  2  b  y  20  200  2000
2  3  c  z  30  300  3000
>>> pdf['a']
b
0  1
1  2
2  3
>>> pdf['c']
d
0  a
1  b
2  c
>>> pdf['e']
g
f
0  x  10
1  y  20
2  z  30
>>> pdf['']
h
0  100
1  200
2  300
>>> pdf['i']
0    1000
1    2000
2    3000
Name: i, dtype: int64
```
=> Fix multi-index column access.

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/series.py, databricks/koalas/tests/test_stats.py
This PR proposes to suppose axis=columns or 1 to count, var, std, max, sum, min, kurtosis, skew and mean in DataFrame. It was implemented via using pandas UDF.
Note that, to infer the return type, it executes the first 1000 and get the return type from it.
- If the results is less then 1000, it just uses pandas API as a shortcut
- Otherwise, it is executed via pandas UDF.
Resolves #599
=> Add axis=columns to count, var, std, max, sum, min, kurtosis, skew and mean in DataFrame

databricks/koalas/namespace.py, databricks/koalas/tests/test_csv.py
This PR adds Spark DDL formatted string support in `read_csv(names=...)`
```python
>>> print(ks.read_csv("input_file.csv", names="A string, B string, C long, D long, E long"))
A  B    C    D    E
0      A  B  NaN  NaN  NaN
1  item1  1  NaN  NaN  NaN
2  item2  1  2.0  NaN  NaN
3  item3  1  2.0  3.0  4.0
4  item4  1  NaN  NaN  NaN
```
Resolves #598
=> Add Spark DDL formatted string support in read_csv(names=...)

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py
=> Fix sort_index with multi-index columns.

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
This PR proposes to allow to omit type hint.
1. If type hint is not given, Koalas collects data as pandas DataFrame.
1.1. If it returns less than 1000, it returns `ks.DataFrame(pdf)`.
1.2. if it returns more than 1000, it just infers schema from `pdf`.
2. If type hint is found, uses that as return type directly.
- When the schema is inferred without type hint, index is cleanly kept.
- When the schema is given via type hint, index is lost - this is because pandas sometimes keeps the index and sometimes not. Koalas does not know without executing the given `func` once.
Please see the example below:
```python
pdf = pd.DataFrame({"timestamp":[0.0, 0.5, 1.0, 0.0, 0.5], "car_id": ['A','A','A','B','B']})
print(pdf.groupby('car_id').apply(lambda _: pd.DataFrame({"column": [0.0]})))
```
```
column …
```
=> Allow to omit type hint in GroupBy.transform, filter, apply

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/utils.py
This PR proposes to add an environment variable, `OPS_ON_DIFF_FRAMES`, to enable operations on different DataFrames.
To use this feature, set `OPS_ON_DIFF_FRAMES` environment variable to `true` and run Koalas codes.
The changes here are a bit big to match the behaviours with pandas, and to generalize them. However, how it works is pretty straightforward. Basically, it joins in index columns and do the operations. See the rough Spark examples below:
```python
>>> df1.show()
```
```
+-----------------+---+
|__index_level_0__|  a|
+-----------------+---+
|                0|  1|
|                1|  2|
|                2|  3|
+-----------------+---+
```
```python
>>> df2.show()
```
```
+-----------------+---+
|__index_level_0__|  a|
+-----------------+---+
|                0|  1|
| …
```
=> Add an option to enable operations on different DataFrames

databricks/koalas/frame.py, databricks/koalas/internal.py, databricks/koalas/namespace.py, databricks/koalas/sql.py, databricks/koalas/tests/test_default_index.py
This PR proposes a default index so that we can now forget about the case when index is missing in Koalas DataFrame  - when Koalas DataFrame is directly created from Spark DataFrame.
There are three types of default index that can be controlled by `DEFAULT_INDEX` environment variable.
- **one-by-one**: It implements an one-by-one sequence by Window function without
specifying partition. Therefore, it ends up with whole partition in single node.
This index type should be avoided when the data is large. This is default.
**TL;DR:** `Window` with `row_number` without partitioning spec
- **distributed-one-by-one**: It implements an one-by-one sequence by group-by and
group-map approach. It still generates a one-by-one sequential index globally.
If the default index must be an one-by-one …
=> Introduce default index with new three index types

databricks/koalas/tests/test_ops_on_diff_frames.py
Currently the master build is failing.
Seems like there are the conflict changes between #633 and #639.
I'd skip the test for now to unblock other PRs.
=> Skip a test `OpsOnDiffFramesEnabledTest.test_no_index`.

databricks/koalas/frame.py, databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/internal.py, databricks/koalas/series.py, databricks/koalas/utils.py
Now that we introduced multi-index columns, we should use `column_index` rather than `data_columns` to be consistent access between single and multi index.
We still have a ways to go, so this includes a workaround to work with the `data_columns`-based approach.
I will address them in the separate PRs.
=> Always use `column_index`.

databricks/koalas/base.py, databricks/koalas/tests/test_series.py
This PR fixes `IndexOpsMixin.all()` and `any()` to work the chain of operations, e.g.,:
```py
>>> (ks.Series([1,2,3]) % 2 == 0).all()
```
This fails with the following error.
```
File "/Users/ueshin/workspace/databricks-koalas/miniconda/envs/databricks-koalas_3.6/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
return f(*a, **kw)
File "/Users/ueshin/workspace/databricks-koalas/miniconda/envs/databricks-koalas_3.6/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o143.select.
: org.apache.spark.sql.AnalysisException: Resolved attribute(s) 0#14L missing from ((0 % 2) = 0)#22 in operator !Aggregate …
```
=> Fix IndexOpsMixin.all/any.

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/indexing.py, databricks/koalas/internal.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/sql.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_dataframe_spark_io.py, databricks/koalas/tests/test_indexing.py, databricks/koalas/tests/test_namespace.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/tests/test_series.py
This PR is a followup of  and proposes two things:
- Exclude Index columns for exposed Spark DataFrame
- Disallow Koalas DataFrame with no index
So, for instance, `to_spark()`  now shows:
```diff
-       __index_level_0__  x
-    0                  0  0
-    1                  1  1
+       x
+    0  0
+    1  1
```
and `index_map` is not expected to be empty in Koalas DataFrame, always. It sets the default index explicitly per https://github.com/databricks/koalas/pull/639
=> Exclude Index columns for exposed Spark DataFrame and disallow Koalas DataFrame with no index

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/series.rst
This PR adds documentation and test for `Series.plot(...)` usage. See https://pandas.pydata.org/pandas-docs/stable/reference/series.html#plotting
```python
pdf_1 = pd.DataFrame({
'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
kdf_1 = ks.DataFrame(pdf_1)
pdf_1['a'].plot("bar", colormap='Paired').figure.savefig("output3.png")
kdf_1['a'].plot("bar", colormap='Paired').figure.savefig("output4.png")
```
=> Document and test Series.plot(...) usage

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/series.rst
This PR add series.plot.pie in Series.
```python
ks.range(10).to_pandas().id.plot.pie().figure.savefig("image.png")
ks.range(10).id.plot.pie().figure.savefig("image.png")
```
If there are more than 1000 rows, it shows as below:
```
ks.range(1001).id.plot.pie().figure.savefig("image.png")
```
Most of people will use, for instance `df.x.value_counts().plot.pie()`.  This case is similar as bar plot.
=> Add plot.pie in Series

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/series.rst
This PR add series.plot.pie in Series.
```python
pdf = pd.DataFrame({
'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
kdf = ks.DataFrame(pdf)
pdf['a'].plot.area(colormap='Paired').figure.savefig("image1.png")
kdf['a'].plot.area(colormap='Paired').figure.savefig("image2.png")
```
In case of this plot, we sample and match the row numbers around 1000.
```python
pdf = pd.DataFrame({'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50, 100] * 100})
kdf = ks.DataFrame(pdf)
kdf['a'].plot.area(colormap='Paired').figure.savefig("image4.png")
```
=> Add plot.area in Series

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/series.rst
This PR add series.plot.pie in Series.
```python
pdf = pd.DataFrame({
'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
}, index=[0, 1, 3, 5, 6, 8, 9, 9, 9, 10, 10])
kdf = ks.DataFrame(pdf)
pdf['a'].plot.line(colormap='Paired').figure.savefig("image1.png")
kdf['a'].plot.line(colormap='Paired').figure.savefig("image2.png")
```
In case of this plot, we sample and match the row numbers around 1000.
```python
pdf = pd.DataFrame({'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50, 100] * 100})
kdf = ks.DataFrame(pdf)
kdf['a'].plot.line(colormap='Paired').figure.savefig("image4.png")
```
=> Add plot.line in Series

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/series.rst
This PR add series.plot.barh in Series.
```python
kdf = ks.range(10)
kdf.to_pandas()['id'].plot.barh(colormap='Paired').figure.savefig("image1.png")
kdf['id'].plot.barh(colormap='Paired').figure.savefig("image2.png")
```
In case of this plot, we sample and match the row numbers around 1000.
```python
ks.range(1001)['id'].plot.barh(colormap='Paired').figure.savefig("image3.png")
```
=> Add plot.barh in Series

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/indexes.py, databricks/koalas/series.py
Currently we use a copy of cached pandas DataFrame/Series when calling `to_pandas()` because the cached pandas DataFrame/Series might be modified by a user and it breaks immutability of `InternalFrame`.
However, for internal use, we can know whether the DataFrame/Series will be modified or not and we don't need to use the copy when the DataFrame/Series will not be modified.
=> Avoid copying pandas_df for internal use.

CONTRIBUTING.md, README.md
It's nothing special, but I found a few typos, so please check it out.
- mailling -> mailing
- princples -> principles
- seperation -> separation
- interpretor -> interpreter
Thanks.
=> Fix some typos in README.md & CONTRIBUTING.md

databricks/koalas/internal.py, databricks/koalas/tests/test_default_index.py
There was a concern about the naming 'one-by-one' since it's confusing (see https://groups.google.com/forum/m/#!topic/koalas-dev/xzZ0VvXFsGM)
This PR proposes to rename the default index 'one-by-one' to 'sequence'.
=> Rename the default index 'one-by-one' to 'sequence'

databricks/koalas/tests/test_indexes.py, databricks/koalas/tests/test_repr.py
I found that there was not enough exception testing for the names property.
So I added tests for those exceptions,
And also added tests for some other code that isn't being tested yet.
It's very appreciate it if someone check it out when available. :)
Thanks.
=> Add missing tests for indexes

databricks/koalas/frame.py, databricks/koalas/plot.py, databricks/koalas/tests/test_frame_plot.py, docs/source/reference/frame.rst
This PR is mainly creating frame plot which is kind of base method, now, only line plot is added.
koalas plot:
pandas plot:
=> ENH: Implement frame plot

databricks/koalas/series.py
Added missing parts for the reverse operator at Series.
such as radd, rsub, and rdiv and so on.
And to make the result different from the reverse operator,
I made some changes to the data in the existing example.
=> Add test for reverse operator at Series

databricks/koalas/plot.py, databricks/koalas/tests/test_frame_plot.py, docs/source/reference/frame.rst
kdf and pdf with specified x and y:
kdf and pdf without specified x and y:
=> ENH: Add barh plot for DataFrame

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py
There seems a little bug in SamplePlot that failed area plot. It is due to after sampling, since `scol` is not assigned, it will return a full DataFrame instead of Series. And looks like area plot turns good as well after fixing it.
Before the bug fixing, the area plot looks like:
=> BUG&TST: Fix area plot for Series and add test

databricks/koalas/plot.py, databricks/koalas/tests/test_frame_plot.py, docs/source/reference/frame.rst
=> ENH: Add area plot for DataFrame

databricks/koalas/tests/test_groupby.py
Added missing tests or tests that weren't running properly for groupby.
I would be grateful if someone could check when possible.
Thanks.
=> Add missing tests for groupby

databricks/koalas/tests/test_csv.py, databricks/koalas/tests/test_namespace.py
I found some untested codes in namespace.py like:
so i added tests for cover them.
I would appreciate it if someone available.
=> Add some missing tests for namespace

databricks/koalas/__init__.py, databricks/koalas/config.py, databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/indexes.py, databricks/koalas/series.py, databricks/koalas/tests/test_config.py, databricks/koalas/tests/test_indexes.py, databricks/koalas/tests/test_repr.py
This PR:
1. Expose `get_option`, `set_option`, `reset_option` to koalas namespace
2. Add typed values supported by JSON ser/de
3. Convert `max_display_count` variable to `display.max_rows` option.
=> Add a 'display.max_rows' configuration with typed configuration support

databricks/koalas/plot.py, databricks/koalas/tests/test_frame_plot.py, docs/source/reference/frame.rst
=> ENH: Add scatter plot for Frame

databricks/koalas/config.py, databricks/koalas/internal.py, databricks/koalas/tests/test_default_index.py
related with #722  i added compute.default_index_type
=> Add configuration value: compute.default_index_type

databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_groupby.py
Found some missing & TODO tests in generic.py
Could someone check this changes If available?
Have a good weekend, Thanks.
=> Add missing & TODO tests for generic.py

databricks/koalas/datetimes.py, databricks/koalas/tests/test_series_datetime.py, docs/source/reference/series.rst
Add missing test for `weekday`
Remove unsupported property `millisecond` for Series Datetime Properties.
=> Add missing tests for datetime & Remove unsupported property

databricks/koalas/groupby.py
It should return Koalas DataFrame always. it was a mistake. Seems this is the only one to fix.
=> GroupBy.apply should return Koalas DataFrame instead of pandas DataFrame

databricks/koalas/config.py, databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
related with #718  i added compute.max_rows
=> Add configuration value: compute.max_rows

databricks/koalas/base.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series.py, databricks/koalas/tests/test_series_datetime.py
Found some missing exception tests in base.py
i added them some for doctest,
one for pytest 
(but this test is currently being skipped for some reason 
so maybe does not directly affect coverage.)
could someone check this when if available.
Thanks.
=> Add some missing exception tests for base.py

databricks/koalas/frame.py
Realated with issue #715 , 
changed above part to use configuration option rather fixed value.
=> Add 'compute.max_rows' option to style property in Series

databricks/koalas/missing/series.py, databricks/koalas/series.py
While checking the series.py file,
there was an incorrectly implemented operator.
(I think maybe someone forgot to change the code in the process of copy & paste by mistake)
could someone check this changes if available.
Thanks :)
=> Fix rpow and rfloordiv to use proper operators in Series

databricks/koalas/frame.py
It is very similar to #735 , 
Same problem that rpow and rfloordiv do not use proper operator in DataFrame.
+ In addition, Found such untested(not a few) operation functions,
so i've fixed them, could someone check this change maybe when available.
Thanks.
=> Fix rpow and rfloordiv to use proper operators in DataFrame

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
This PR adds the support for schema inference support at DataFrame.transform.
Now, `DataFrame.transform` can be used as below:
```python
ks.range(10).transform(lambda x: x ** 2)
```
=> Add schema inference support at DataFrame.transform

databricks/koalas/config.py, databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py, databricks/koalas/tests/test_stats.py
related with #715 i added compute.shorcut_limit
Resolves #715
=> Add configuration value: compute.shortcut_limit

databricks/koalas/config.py, databricks/koalas/frame.py, databricks/koalas/plot.py, databricks/koalas/tests/test_config.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_frame_plot.py, databricks/koalas/tests/test_groupby.py
This PR takes over https://github.com/databricks/koalas/pull/738, and this fix was inspired by the PR. So the commit credits to, and is authored by @charlesdong1991.
This PR adds `Option` class to allow various cases such as type checking, value checking, etc.
See the usage below as a example
```python
Option(
key='compute.default_index_type',
doc=(
"This sets the default index type: sequence, distributed and distributed-sequence."),
default='sequence',
types=str,
check_func=(
lambda v: v in ('sequence', 'distributed', 'distributed-sequence'),
"Index type should be one of 'sequence', 'distributed', 'distributed-sequence'."))
```
While I am here, I also fixed `plotting.sample_ratio` respects `plotting.max_rows` by default if this is not set.
Also, let `DataFrame.transform` respect …
=> Add 'Option` class to support type check and value check in options

databricks/koalas/config.py, databricks/koalas/frame.py, databricks/koalas/indexes.py, databricks/koalas/series.py, databricks/koalas/tests/test_frame_plot.py, databricks/koalas/tests/test_repr.py
This PR adds the support to unlimit the number of rows at 'display.max_rows'.
```python
>>> ks.set_option("display.max_rows", None)
>>> ks.range(1001)
id
0        0
1        1
...
1018  1018
1019  1019
[1020 rows x 1 columns]
```
=> Support None to unlimit 'display.max_rows'

databricks/koalas/config.py, databricks/koalas/internal.py, docs/source/index.rst, docs/source/reference/general_functions.rst, docs/source/user_guide/index.rst, docs/source/user_guide/options.rst
This PR adds 'User Guide' with available options.
Can be verified as below:
```bash
./dev/lint-python
open docs/build/html/index.html
```
Resolves #715
=> Add documentation for 'User Guide' with available options

databricks/koalas/tests/test_default_index.py, databricks/koalas/tests/test_frame_plot.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/tests/test_repr.py, databricks/koalas/tests/test_series_plot.py
We should place `reset_option()` before `tearDownClass()`, otherwise another `SparkSession` will start.
=> Place `reset_option()` before `tearDownClass()`.

.travis.yml
Spark 2.4.4 is released and Apache mirror only contains latest versions.
See, for instance:
https://dist.apache.org/repos/dist/release//spark/spark-2.4.3/spark-2.4.3-bin-hadoop2.7.tgz
https://dist.apache.org/repos/dist/release//spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
=> Use Spark 2.4.4 in Travis CI

databricks/koalas/tests/test_groupby.py
Found A missing exception test for groupby
could someone check this out when available?
have a great weekend, Thanks :)
=> Add a missing exception test for groupby

.travis.yml
Spark 2.3.4 is released and Apache mirror only contains latest versions.
=> Use Spark 2.3.4 in Travis CI.

databricks/koalas/plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/series.rst
This PR takes over https://github.com/databricks/koalas/pull/710
KDE, unlike other plots like line or area, it needs to calculates values via Spark so that we can compute it in a distributed manner.
This PR uses MLlib's KernelDensity API to calculate KDE. Since Spark only support scalar bandwidth, unlike SciPy that pandas' uses, Koalas will currently only support fixed scalar bandwidth only.
Implementation is different so the values are slightly different but seems good enough:
```python
pd.Series([1, 2, 2.5, 3, 3.5, 4, 5]).plot.kde(bw_method=0.3).figure.savefig("image.png")
```
```python
ks.Series([1, 2, 2.5, 3, 3.5, 4, 5]).plot.kde(bw_method=0.3).figure.savefig("image.png")
```
```python
pd.Series([1, 2, 2.5, 3, 3.5, …
```
=> Implement Series.plot.kde

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Since pandas dataframe support axis parameter in dataframe.diff.
I think we need to support it either. (And it was already commented as TODO)
In addition, now the nunique function only support the axis parameter as 0 (without 'index'), also fix it.
And currently we only support axis 0, or axis 1 for some functions, so i plan to implement it soon.
=> Add axis parameter to dataframe.diff

databricks/koalas/namespace.py, databricks/koalas/tests/test_csv.py
=> Add "sep" parameter for read_csv

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_groupby.py
Found some missing doctest & unittests for DataFrame as shown below.
- test for operator truediv & truediv
- test for nunique
- test for dropna
=> Add missing tests for DataFrame

databricks/koalas/generic.py, databricks/koalas/namespace.py, databricks/koalas/tests/test_dataframe_conversion.py, docs/source/reference/io.rst
This PR proposes to use `spark.write.json` API to enable distributed computation when `path` is specified. If `path` is not specified, it just calls pandas' `to_json` as was.
Also, this PR adds `read_json` API.
=> Add read_json and let to_json use spark.write.json

databricks/koalas/namespace.py, databricks/koalas/tests/test_csv.py, databricks/koalas/tests/test_dataframe_spark_io.py
Resolves #765 ,
I applied the same logic(as worked on #769) to all of the functions mentioned in above issue.
So when we work with spark IO read, and also know about index column name,
now we can use these functions with index_col like below and avoid creation of default index:
```python
>>> ks.read_parquet(path, index_col=['i32', 'i64'])
f  bhello
i32 i64
0   1    6.0  people
1   2    7.0      yo
```
=> Add index_col for spark IO reads

dev/_make_missing_functions.py, dev/env_setup.sh
This PR fixes typos at  '_make_missing_functions.py' and 'env_setup.sh'
=> Fix minor typos at '_make_missing_functions.py' and 'env_setup.sh'

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/plot.py, databricks/koalas/tests/test_frame_plot.py, databricks/koalas/tests/test_series_plot.py, docs/source/reference/frame.rst
This PR implements histogram in DataFrame. It reuses Series' implementation.
Also, it contains minor refactoring to match with KDE implementation. Basically it mimics pandas implementation.
```python
pdf = pd.DataFrame({
'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
'b': [2, 3, 4, 5, 7, 9, 10, 15, 10, 20, 20]
})
pdf.plot.hist().figure.savefig("image_pd.png")
```
```python
kdf = ks.DataFrame({
'a': [1, 2, 3, 4, 5, 6, 7, 8, 9, 15, 50],
'b': [2, 3, 4, 5, 7, 9, 10, 15, 10, 20, 20]
})
kdf.plot.hist().figure.savefig("image_ks.png")
```
=> Add DataFrame.plot.hist()

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_repr.py
Currently, Koalas `display.max_rows` has a weird relationship with pandas' `display.max_rows` because Koalas directly uses pandas' `repr`.
```python
ks.set_option("display.max_rows", 5)
pd.set_option("display.max_rows", 5)
ks.range(6)
```
```
id
0   0
1   1
2   2
3   3
4   4
```
```python
ks.set_option("display.max_rows", 5)
pd.set_option("display.max_rows", 4)
ks.range(6)
```
```
id
0    0
1    1
..  ..
3    3
4    4
[Showing only the first 5 rows x 1 columns]
```
**The reason** is because pandas appends footer like:
```python
>>> ks.range(6).to_pandas()
id
0    0
1    1
..  ..
4    4
5    5
[6 rows x 1 columns]
```
only when the value exceeds `display.max_rows`. 
Koalas replaces this footer `[6 rows x 1 columns]` to `[Showing only the …
=> Show consistent repr output for index, series and frame

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py
With this change, the following DataFrame APIs support multi-index columns:
- `applymap`
- `shift`
- `diff`
- `fillna`
- `rank`
=> Reduce usages of `data_columns`.

databricks/koalas/base.py, databricks/koalas/internal.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/typedef.py
When the initialization of pandas in pyarrow is not done yet, it can't convert `pa.TimestampType` to pandas' dtype. In that case, the following example raises an error:
```py
from datetime import datetime
kdf = ks.DataFrame({'t': [datetime(2019, 1, 1, 0, 0, 0), datetime(2019, 1, 2, 0, 0, 0), datetime(2019, 1, 3, 0, 0, 0)]})
kdf[kdf['t'] != kdf['t']]
```
```py
>>> kdf[kdf['t'] != kdf['t']]
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/frame.py", line 6646, in __repr__
pdf = self.head(max_display_count + 1)._to_internal_pandas()
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/frame.py", line 6639, in _to_internal_pandas
return …
```
=> Handle TimestampType separately when convert to pandas' dtype.

databricks/koalas/__init__.py, databricks/koalas/config.py, databricks/koalas/tests/test_config.py, docs/source/user_guide/options.rst
This PR adds the support for options to be set like attributes.
```python
>>> ks.options.display.max_rows
1000
>>> ks.options.display.max_rows = 10
>>> ks.options.display.max_rows
10
```
=> Add namespace support in options

databricks/koalas/frame.py
When we drop columns from dataframe with `DataFrame.drop()`,
We can get a dataframe which columns are dropped properly like below.
```python
>>> df
name   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN
>>>
>>> df = df.drop('name')
>>> df
class  max_speed
0    bird      389.0
1    bird       24.0
2  mammal       80.5
3  mammal        NaN
```
But when we try to get an internal spark dataframe after then,
it shows us original one which is not delete columns like below.
```
>>> df._sdf.show()
+-----------------+------+------+---------+
|__index_level_0__|  name| class|max_speed|
+-----------------+------+------+---------+
|                0|falcon|  bird|    389.0|
|                1|parrot|  bird|     24.0| …
```
=> Fix DataFrame.drop() to remove fields from Spark DataFrame also.

databricks/koalas/frame.py
Current `add_prefix` and `add_suffix` might cause the same issue as #782 and #804.
This explicitly adds the updated Spark DataFrame for APIs which don't support multi-index columns properly yet as a workaround.
=> Add a workaround to add_prefix/add_suffix for APIs which don't fully support multi-index columns.

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
The current columns setter doesn't rename the Spark columns and might cause issues such as #782 and #804.
This PR fixes that.
Resolves #782
Resolves #804
=> Fix columns setter to rename Spark DataFrame columns

databricks/koalas/namespace.py, databricks/koalas/tests/test_csv.py
Fix #808 
Add `squeeze` argument to `DataFrame.read_csv` so that it is more aligned with `pandas.DataFrame.read_csv` and the behavior will be the same as in `pandas`. Also add pytests for this feature.
=> add squeeze argument to read_csv

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Fix #819 
Raise an error `>>> ValueError: columns overlap but no suffix specified: ['letter']` if the duplicated column(s) is found but no suffix is specified. 
Also added the pytests.
=> Raise a more helpful error for duplicated columns in Join

databricks/koalas/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
Like pandas Series.aggregate (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.aggregate.html)
I implemented aggregate function for series.
Example:
```python
>>> s = ks.Series([1, 2, 3, 4])
>>> s
0    1
1    2
2    3
3    4
>>> s.agg('min')
1
>>> s.agg(['min', 'max'])
min    1
max    4
```
(above example is using pandas one)
=> Implement Series.aggregate and agg

databricks/koalas/frame.py
I came across the `frame.agg` when i read through code base, and based on the inline comment, I think the manipulation using pandas could be simplified a bit IIUC.
=> Clean pandas usage in frame.agg

requirements-dev.txt
Currently master brach build for `py3.7` is broken.
The conda on Travis-CI suddenly starts to use `libprotobuf==3.9.2` instead of `3.8.0` as before, then it causes downgrade of pyarrow to `0.11.1`. Seems like `libprotobuf==3.9.2` and `pyarrow==0.13.0` are not compatible and tries to remove or downgrade `pyarrow`.
```
$ conda install libprotobuf=3.9.2 pyarrow=0.13.0
Collecting package metadata: done
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in conflict:
- libprotobuf=3.9.2
- pyarrow=0.13.0 -> arrow-cpp[version='>=0.13.0,<0.14.0a0,>=0.13.0,<1.0a0'] -> libprotobuf[version='>=3.6.0,<3.6.1.0a0']
Use "conda search <package> --info" to see the dependencies for each package.
```
According to the dependency of `pyarrow==0.13.0`, it also conflicts …
=> Add upper bound for libprotobuf caused by newer pyarrow.

databricks/koalas/indexes.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_indexes.py
=> Fix `MultiIndex.to_pandas()` and `__repr__()`.

databricks/koalas/frame.py, databricks/koalas/indexes.py, databricks/koalas/missing/common.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/indexes.py, databricks/koalas/missing/series.py, databricks/koalas/namespace.py, databricks/koalas/series.py
`DataFrame.__iter__()` returns an iterator of columns.
And explicitly disable `__iter__()` with a proper error message for `Series` and `Index`.
```py
>>> list(ks.Series([1,2,3]))
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/series.py", line 3131, in __iter__
return _MissingPandasLikeSeries.__iter__(self)
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/missing/__init__.py", line 24, in unsupported_function
reason=reason)
databricks.koalas.exceptions.PandasNotImplementedError: The method `pd.Series.__iter__()` is not implemented. If you want to collect your data as an NumPy array, use 'to_numpy()' instead.
```
Resolves #555.
=> Support `__iter__()` for `DataFrame` and explicitly disable for `Series` and `Index`.

databricks/koalas/namespace.py, databricks/koalas/tests/test_namespace.py
This PR adds `unit` and `origin` options for `to_datetime` and resolves #837 .
=> Add unit and origin options for to_datetime

databricks/koalas/frame.py
https://github.com/databricks/koalas/blob/7ee2a8dff3d61f2fe66f85385bc5af20d2f154f5/databricks/koalas/frame.py#L3534
seems this line won't be touched, and the reason it still passed tests is because it triggered the `Series.fillna()` error raise mechanism in the `else` below.
=> Fix on wrong error raise in DataFrame.fillna

docs/source/reference/frame.rst
Fix duplicated function name `DataFrame.plot.hist` to `DataFrame.hist`
=> [MINOR] Fix duplicated function 'Dataframe.plot.hist'

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
right now, when I look at Groupby, it does not accept str or list, but in pandas, it's allowed. So before implementing named aggregation, i think this is a better thing to deal first.
e.g. in pandas we could have:
now koalas can also accept this:
=> Allow str and list in aggfunc in DataFrameGroupby.agg

databricks/koalas/tests/test_frame_plot.py, databricks/koalas/tests/test_series_plot.py
We should close figure or clear axis; otherwise, it draws another plot in the same window. This ends up with comparing, for instance:
However we should compare each plot:
So, previously the comparison was always correct since both plots are overlapped. `plot_to_base64` closes the plot so we should call `plot_to_base64` for each axis before calling another plot.
=> Make plot tests actually check the difference between pandas' and Koalas'

dev/lint-python, docs/source/conf.py
So, `make clean html` removes auto-generated files under `docs/source/references/api` as well. Manually tested.
=> Clean generated rst files at Sphinx instead of linter script

databricks/koalas/plot.py, dev/lint-python
Related with https://github.com/databricks/koalas/pull/847#pullrequestreview-296428735 ,
Fixed flake8 to ignore "docs/build/html/reference/api/*.py"
in my local test, it works well, and all plots visible in documentation like below:
=> Add options to ignore specific cases when flake8 test

databricks/koalas/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, docs/source/reference/series.rst
Implement Series.copy and add Examples to Frame.copy also
```python
>>> s = ks.Series([1, 2], index=["a", "b"])
>>> s
a    1
b    2
>>> s_copy = s.copy()
>>> s_copy
a    1
b    2
```
=> Implement Series.copy

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
The current `GroupBy.apply` uses a shortcut (proposed in #646) when schema inference is triggered and the number of records is less than or equal to `compute.shortcut_limit` (1000 by default), but this might cause issues such as #834.
This PR proposes to remove the shortcut and make `GroupBy.apply` only infer the schema.
Closes #834
=> Remove shortcut from GroupBy.apply

databricks/koalas/frame.py
=> Add `index_col` argument to `to_koalas()`.

databricks/koalas/frame.py, databricks/koalas/series.py
This PR adds the type inference for:
- `transform` in Series
- `apply` in Series
- `applymap` in DataFrame
Note that this PR intentionally does not implement shortcut to avoid the operations on different DataFrames. Maybe we should add different configuration to indicate the sample size for type inference.
=> Infer type for transform and apply in Series, and applymap in DataFrame

databricks/koalas/datetimes.py
Removed an unnecessary backtick in `DatetimeMethods.year`
=> [MINOR] Fix doc of DatetimeMethods.year

docs/source/getting_started/10min.ipynb
Can be reviewed here: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/HyukjinKwon/koalas/add-db-note?filepath=docs%2Fsource%2Fgetting_started%2F10min.ipynb)
This PR adds a short guide to import 10 minutes to Koalas in Databricks:
> For Databricks users, you can import [the current .ipynb file](https://raw.githubusercontent.com/databricks/koalas/master/docs/source/getting_started/10min.ipynb) and run it after [installing Koalas](https://github.com/databricks/koalas#how-do-i-use-this-on-databricks).
=> Add a short guide to import 10 minutes to Koalas in Databricks

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
This allows koalas to have nested renaming/selection:
```python
kdf = ks.DataFrame({'A': [1, 1, 2, 2],
'B': [1, 2, 3, 4],
'C': [0.362, 0.227, 1.267, -0.562]},columns=['A', 'B', 'C'])
```
WIP: still need to add some tests and docstrings
=> Implement nested renaming for groupby agg

databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/internal.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py
This PR adds `index_col` parameter to `DataFrame.to_spark`. This PR relates to https://github.com/databricks/koalas/pull/901.
After this PR, we can do a roundtrip in Koalas and Spark DataFrame easily.
```python
>>> kdf = ks.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
>>> sdf = kdf.to_spark(index_col="index").filter("a == 2")  # PySpark API
>>> kdf = sdf.to_koalas(index_col="index")
>>> kdf
a  b  c
index
1      2  5  8
```
=> Add 'index_col' parameter to DataFrame.to_spark

databricks/koalas/groupby.py, databricks/koalas/missing/groupby.py, databricks/koalas/tests/test_groupby.py, docs/source/reference/groupby.rst
=> Add GroupBy.shift.

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
Implement DataFrame.xs (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.xs.html#pandas.DataFrame.xs)
```python
>>> d = {'num_legs': [4, 4, 2, 2],
...      'num_wings': [0, 0, 2, 2],
...      'class': ['mammal', 'mammal', 'mammal', 'bird'],
...      'animal': ['cat', 'dog', 'bat', 'penguin'],
...      'locomotion': ['walks', 'walks', 'flies', 'walks']}
>>> df = ks.DataFrame(data=d)
>>> df = df.set_index(['class', 'animal', 'locomotion'])
>>> df
num_legs  num_wings
class  animal  locomotion
mammal cat     walks              4          0
dog     walks              4          0
bat     flies              2          2
bird   penguin walks              2          2
>>> df.xs('mammal')
num_legs  num_wings
animal locomotion
cat    walks              4          0
dog …
```
=> Implement DataFrame.xs

databricks/koalas/__init__.py, databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
This is equivalent to nested renaming, so like pandas, we have `koalas.NamedAgg` now for this:
```python
>>> aggregated = df.groupby('A').agg(b_max=ks.NamedAgg(column='B', aggfunc='max'))
>>> aggregated
b_max
A
1        2
2        4
```
Resolves #823
=> Add NamedAgg

requirements-dev.txt, setup.py
I'd set the upper bound for pyarrow version for now since we need to set an environment variable to work with pyarrow 0.15.
https://github.com/apache/spark/pull/26045:
> Arrow 0.15.0 introduced a change in format which requires an environment variable to maintain compatibility.
=> Set an upper bound for pyarrow version.

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py, databricks/koalas/tests/test_ops_on_diff_frames.py
Resolves #894
for below DataFrame,
```python
>>> df = ks.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df
max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
```
now we can set value for all items matching the list of labels like Pandas.
```python
>>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
>>> df
max_speed  shield
cobra               1       2
viper               4      50
sidewinder          7      50
```
=> Enable DataFrame setting value as list of labels. (Resolves #894)

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
An alias for columns.
```python
>>> df = ks.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df
max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
>>> df.keys()
Index(['max_speed', 'shield'], dtype='object')
>>> df.to_pandas().keys()
Index(['max_speed', 'shield'], dtype='object')
```
=> Impelment DataFrame.keys

databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
An alias for index.
```python
>>> midx = pd.MultiIndex([['lama', 'cow', 'falcon'],
...                       ['speed', 'weight', 'length']],
...                      [[0, 0, 0, 1, 1, 1, 2, 2, 2],
...                       [0, 1, 2, 0, 1, 2, 0, 1, 2]])
>>> kser = ks.Series([45, 200, 1.2, 30, 250, 1.5, 320, 1, 0.3], index=midx)
>>> pser = kser.to_pandas()
>>> pser.keys()
MultiIndex([(  'lama',  'speed'),
(  'lama', 'weight'),
(  'lama', 'length'),
(   'cow',  'speed'),
(   'cow', 'weight'),
(   'cow', 'length'),
('falcon',  'speed'),
('falcon', 'weight'),
('falcon', 'length')],
)
>>> kser.keys()
MultiIndex([(  'lama',  'speed'),
(  'lama', 'weight'),
(  'lama', 'length'),
(   'cow',  'speed'),
(   'cow', 'weight'),
(   'cow', 'length'),
('falcon',  'speed'),
('falcon', 'weight'),
('falcon', …
```
=> Implement Series.keys

databricks/koalas/indexes.py, databricks/koalas/missing/indexes.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
like pandas (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.copy.html#pandas.Index.copy)
implement function `copy` for Index
```python
>>> df = ks.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df
max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
>>> df.index
Index(['cobra', 'viper', 'sidewinder'], dtype='object')
>>> df.index.copy()
Index(['cobra', 'viper', 'sidewinder'], dtype='object')
>>> df.index.copy(name='snake')
Index(['cobra', 'viper', 'sidewinder'], dtype='object', name='snake')
```
=> Implement Index.copy & MultiIndex.copy

databricks/koalas/base.py
Resolve #931 (The contents below is same as the contents of this issue)
When we use `is_monotonic_decreasing` or `is_monotonic_increasing` for index,
pandas works like below:
```python
>>> s = pd.Series([7, 6, 5, 4, 3, 2, 1], index=[7, 6, 5, 4, 3, 2, 1])
>>> s.index.is_monotonic_decreasing
True
```
Since the index order is literally motononic decreasing, they return `True`
But our case,
```python
>>> s = ks.Series([7, 6, 5, 4, 3, 2, 1], index=[7, 6, 5, 4, 3, 2, 1])
>>> s.index.is_monotonic_decreasing
False
```
as seen above, it returns `False`.
because our existing logic always order by index column before calculate the each rows increasing or decreasing.
So they always calculate result based on data column, not index column. (index column is always sorted since order by)
So i think maybe …
=> Make is_monotonic~ work properly for index

README.md, docs/source/development/contributing.rst, docs/source/development/design.rst, docs/source/development/index.rst, docs/source/user_guide/faq.rst, docs/source/user_guide/index.rst, docs/source/user_guide/pandas_pyspark.rst
Current README.md is too long. this PR only adds some simple example/installation, and then move all to our official documentation.
I kept the links in README.md.
=> Move Design Principles and FAQ to the official documentation

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/indexes.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/indexes.py, databricks/koalas/series.py, docs/source/reference/frame.rst, docs/source/reference/indexing.rst
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ndim.html#pandas.DataFrame.ndim
```python
>>> df = ks.range(10)
>>> df.ndim
2
>>> df = ks.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df.ndim
2
```
=> Add property: DataFrame.ndim, Index.ndim, MultiIndex.ndim

databricks/koalas/frame.py, databricks/koalas/namespace.py
=> Fix passing options as keyword arguments

README.md
=> Remove subsection for Databricks Runtime in Getting Started

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
When `kdf.reindex()`, all the given columns are included the existing columns, the following error is raised.
```
...
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/frame.py", line 6641, in reindex
df = DataFrame(df._reindex_columns(columns))
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/frame.py", line 6709, in _reindex_columns
return self._internal.copy(sdf=sdf, data_columns=columns, column_index=idx)
UnboundLocalError: local variable 'sdf' referenced before assignment
```
=> Fix reindex when all the given columns are included the existing columns

databricks/koalas/tests/test_series.py, databricks/koalas/typedef.py
=> Add datetime as the equivalent python type to TimestampType

databricks/koalas/namespace.py, docs/source/reference/general_functions.rst
Resolves #961 
```python
>>> df1 = ks.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]},
...                    columns=['lkey', 'value'])
>>> df2 = ks.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]},
...                    columns=['rkey', 'value'])
>>> df1
lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5
>>> df2
rkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8
>>> merged = ks.merge(df1, df2, left_on='lkey', right_on='rkey')
>>> merged.sort_values(by=['lkey', 'value_x', 'rkey', 'value_y'])
lkey  value_x rkey  value_y
0  bar        2  bar        6
5  baz        3  baz        7
1  foo        1  foo        5
2  foo        1  foo        8
3  foo        5  foo …
```
=> Top-level Koalas functions - merge

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py
Resolves #971 
```python
>>> kidx
Int64Index([1, 2, 3], dtype='int64', name='a')
>>> kidx.name = None
>>> kidx
Int64Index([1, 2, 3], dtype='int64')
```
=> Fix bug when  assign None to name as Index

databricks/koalas/tests/test_dataframe.py
There is no test that tested with `inplace=True` parameter at drop_duplicates function.
So I update test case that is `drop_duplicates(inplace=True)`.
Now the `test_drop_duplicates()` check 4 stages. (`single-index columns with/without inplace`, `multi-index columns with/without inplace`)
=> Add test of drop_duplicates with inplace parameter

databricks/koalas/tests/test_expanding.py, databricks/koalas/window.py
i'm not pretty sure whether this is necessary or not,
but i think maybe is it better to have `__repr__` for `Expanding` like pandas?
```python
>>> pd.Series([1, 2, 3]).expanding(2)
Expanding [min_periods=2,center=False,axis=0]
>>> ks.Series([1, 2, 3]).expanding(2)
Expanding [min_periods=2]
```
the results slightly different since now we have only `min_periods` parameter
=> Add repr for Expanding

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
Resolves #958 
```python
>>> tuples = [(1, 'red'), (1, 'blue'),
...           (2, 'red'), (2, 'blue')]
>>> ks.MultiIndex.from_tuples(tuples, names=('number', 'color'))
MultiIndex([(1,  'red'),
(1, 'blue'),
(2,  'red'),
(2, 'blue')],
names=['number', 'color'])
```
=> Implement MultiIndex.from_tuples

databricks/koalas/indexes.py
Resolves #948
```python
>>> Index([1, 2, 3])
Int64Index([1, 2, 3], dtype='int64')
>>> Index(list('abc'))
Index(['a', 'b', 'c'], dtype='object')
```
=> Enable creating Index from list like 'Index([1, 2, 3])'

databricks/koalas/generic.py, databricks/koalas/tests/test_stats.py
This PR fixes `_Frame.median()` to:
- follow `_scol` for `Series`.
- support multi-index columns.
- avoid attaching default index for `DataFrame`.
=> Fix median to support multi-index columns.

databricks/koalas/missing/series.py, databricks/koalas/series.py
=> Implement Series.between

docs/source/reference/series.rst
I forgot to add `Series.between` to the doc in #997.
=> Add Series.between to the documentation

databricks/conftest.py
When all characters in UUID are numbers, seems it fails to create database as below:
```
E                   : org.apache.spark.sql.catalyst.parser.ParseException: 
E                   mismatched input '91605146e92645649974094704704443' expecting {'SELECT', 'FROM', 'ADD', 'AS', 'ALL', 'ANY', 'DISTINCT', 'WHERE', 'GROUP', 'BY', 'GROUPING', 'SETS', 'CUBE', 'ROLLUP', 'ORDER', 'HAVING', 'LIMIT', 'AT', 'OR', 'AND', 'IN', NOT, 'NO', 'EXISTS', 'BETWEEN', 'LIKE', RLIKE, 'IS', 'NULL', 'TRUE', 'FALSE', 'NULLS', 'ASC', 'DESC', 'FOR', 'INTERVAL', 'CASE', 'WHEN', 'THEN', 'ELSE', 'END', 'JOIN', 'CROSS', 'OUTER', 'INNER', 'LEFT', 'SEMI', 'RIGHT', 'FULL', 'NATURAL', 'ON', 'PIVOT', 'LATERAL', 'WINDOW', 'OVER', 'PARTITION', 'RANGE', 'ROWS', 'UNBOUNDED', 'PRECEDING', 'FOLLOWING', 'CURRENT', 'FIRST', …
```
=> Add string prefix for temp database name used in tests

dev/readthedocs-environment.yml
Currently Read the Docs build is being failed:
```
Collecting package metadata (repodata.json): ...working... Killed
Command killed due to excessive memory consumption
Command time: 44s Return: 1
```
This PR tries to use no-cache in `pip` to reduce memory consumption.
=> Reduce memory consumption in Read the Docs build

databricks/koalas/frame.py, databricks/koalas/series.py
=> [MINOR] Fix typos from 'Koala' to 'Koalas' in Series and DataFrame

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
Resolves #959 
```python
>>> kdf = ks.DataFrame({'a': [1, 2, 3, 4, 5], 'b': [6, 7, 8, 9, 0]})
>>> kdf
a  b
0  1  6
1  2  7
2  3  8
3  4  9
4  5  0
>>> kdf.quantile(.5)
a    3
b    7
Name: 0.5, dtype: int64
>>> kdf.quantile([.25, .5, .75])
a  b
0.25  2  6
0.5   3  7
0.75  4  8
```
=> Implement DataFrame.quantile

databricks/koalas/tests/test_expanding.py, databricks/koalas/window.py
This PR implement groupby.expanding.sum, min, max, mean in Series and DataFrame:
```python
>>> kser = ks.Series([2, 3, float("nan"), 10])
>>> kser.groupby(kser).expanding().sum()
0
3.0   1     3.0
2.0   0     2.0
10.0  3    10.0
```
```python
>>> df = kser.to_frame()
>>> df.groupby(df['0']).expanding().sum()
0
0
3.0  1   3.0
2.0  0   2.0
10.0 3  10.0
```
=> Implement groupby.expanding.sum, min, max, mean in Series and DataFrame

databricks/conftest.py, databricks/koalas/testing/utils.py
For some reasons, the tests started to suddenly fail as below:
```
databricks/koalas/tests/test_series_string.py::SeriesStringTest::test_string_wrap PASSED [ 97%]
databricks/koalas/tests/test_series_string.py::SeriesStringTest::test_string_zfill PASSED [ 97%]
databricks/koalas/tests/test_sql.py::SQLTest::test_error_bad_sql PASSED  [ 97%]
databricks/koalas/tests/test_sql.py::SQLTest::test_error_unsupported_type PASSED [ 98%]
databricks/koalas/tests/test_sql.py::SQLTest::test_error_variable_not_exist PASSED [ 98%]
databricks/koalas/tests/test_stats.py::StatsTest::test_abs FAILED        [ 98%]
databricks/koalas/tests/test_stats.py::StatsTest::test_axis_on_dataframe FAILED [ 98%]
databricks/koalas/tests/test_stats.py::StatsTest::test_corr FAILED       [ 98%] …
```
=> Use one Spark session across all tests

databricks/koalas/frame.py, databricks/koalas/internal.py, databricks/koalas/testing/utils.py
There was a conflict between https://github.com/databricks/koalas/commit/11f8f3902ff779b0786ef46f1e28adde0b20be7e and https://github.com/databricks/koalas/commit/1cb4ba04183b1f4f3d333525e8b10f6142c87d26.
=> [HOTFIX] Don't use data_columns in DataFrame.quantile

databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
This PR implement `mask` of `Series` 
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mask.html#pandas.Series.mask)
```python
>>> s1 = ks.Series([0, 1, 2, 3, 4])
>>> s2 = ks.Series([100, 200, 300, 400, 500])
>>> s1.mask(s1 > 0).sort_index()
0    0.0
1    NaN
2    NaN
3    NaN
4    NaN
>>> s1.mask(s1 > 1, 10).sort_index()
0     0
1     1
2    10
3    10
4    10
>>> s1.mask(s1 > 1, s1 + 100).sort_index()
0      0
1      1
2    102
3    103
4    104
>>> s1.mask(s1 > 1, s2).sort_index()
0      0
1      1
2    300
3    400
4    500
```
=> Implement Series.mask()

dev/readthedocs-environment.yml
Many packages seem not supported with Python 3.8 yet. This PR aims to set the Python version to 3.7 for now in Read the Docs build.
Note that we should switch back to pip once Spark 3.0 is released because we use Conda only because of JDK 8.
Current pip configuration in `.readthedocs.yml` seems being ignored due to Conda configuration.
Related to https://github.com/readthedocs/readthedocs.org/issues/6350
=> Use Python 3.7 in Read the Docs build (with Conda)

databricks/koalas/tests/test_expanding.py, databricks/koalas/window.py
the existing doctests of `Expanding.Groupby` are only for `sum()`.
so fix them to work properly for each function.
=> [MINOR] Fix doctests of Expanding.Groupy to work properly

databricks/koalas/groupby.py, databricks/koalas/tests/test_rolling.py, databricks/koalas/window.py
This PR implement groupby.rolling.count, sum, min, max, mean in Series and DataFrame:
```python
>>> s = ks.Series([2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5])
>>> s.groupby(s).rolling(3).count().sort_index()
0
2  0     1.0
1     2.0
3  2     1.0
3     2.0
4     3.0
4  5     1.0
6     2.0
7     3.0
8     3.0
5  9     1.0
10    2.0
>>> df = ks.DataFrame({"A": s.to_numpy(), "B": s.to_numpy() ** 2})
>>> df.groupby(df.A).rolling(2).count().sort_index()
A    B
A
2 0   1.0  1.0
1   2.0  2.0
3 2   1.0  1.0
3   2.0  2.0
4   2.0  2.0
4 5   1.0  1.0
6   2.0  2.0
7   2.0  2.0
8   2.0  2.0
5 9   1.0  1.0
10  2.0  2.0
>>> s.groupby(s).rolling(3).sum().sort_index()
0
2  0      NaN
1      NaN
3  2      NaN
3      NaN
4      9.0
4  5      NaN
6      NaN
7     12.0
8     12.0
5  9      NaN
10 …
```
=> Implement Groupby.Rolling.count/sum/min/max/mean

databricks/koalas/tests/test_expanding.py, databricks/koalas/tests/test_repr.py, databricks/koalas/tests/test_rolling.py, databricks/koalas/tests/test_window.py
Maybe this is not so necessary, but sometimes i got confused when i did some test.
For example, if i'd like to test `groupby.rolling.sum`, i was confused which is the correct test class name of this function `pytest tests/test_rolling.py::RollingTests::test_groupby_rolling_sum.py` or `pytest tests/test_rolling.py::RollingTest::test_groupby_rolling_sum.py`.
since some of test classes are named by `*Tests` and the others are `*Test`.
so i think it should be better to use unified rule when naming test class to keep consistency.
=> Keep consistency of Test Class Names: *Tests -> *Test

databricks/koalas/groupby.py
=> Fix GroupBy.rank documentation to render properly

databricks/koalas/tests/test_expanding.py, databricks/koalas/tests/test_rolling.py, databricks/koalas/window.py
Add test case for MultiIndex column in Rolling/ExpandingGroupby
```python
kdf = ks.DataFrame({'a': [1, 2, 3, 2], 'b': [4.0, 2.0, 3.0, 1.0]})
kdf.columns = pd.MultiIndex.from_tuples([('a', 'x'), ('a', 'y')])
pdf = kdf.to_pandas()
self.assert_eq(
repr(getattr(kdf.groupby(("a", "x")).rolling(2), f)().sort_index()),
repr(getattr(pdf.groupby(("a", "x")).rolling(2), f)()))
self.assert_eq(
repr(getattr(kdf.groupby([("a", "x"), ("a", "y")]).rolling(2), f)().sort_index()),
repr(getattr(pdf.groupby([("a", "x"), ("a", "y")]).rolling(2), f)()))
```
=> Add tests for MultiIndex column in Rolling/ExpandingGroupby

databricks/koalas/frame.py, databricks/koalas/tests/test_ops_on_diff_frames.py
```python
ks.options.compute.ops_on_diff_frames=True
pdf = pd.DataFrame({'b': [1,2,3], 'c': [4,5,6]})
columns = pd.MultiIndex.from_tuples([('a', 'b'), ('a', 'c')])
pdf.columns = columns
kdf = ks.DataFrame(pdf)
kdf['c'] = ks.Series([1,2,3])
kdf
```
Before:
```
a     c
b  c    NaN
0  1  4  1   1
1  2  5  1   2
2  3  6  1   3
```
After:
```
a     c
b  c
0  1  4  1
1  2  5  2
2  3  6  3
```
=> Fix different index level assignment when 'compute.ops_on_diff_frames' is enabled

README.md, docs/source/user_guide/best_practices.rst, docs/source/user_guide/index.rst
This PR add "Best Practices" section in the documentation to prevent confusions from new Koalas users and let them know the best practices and limitations.
Resolves #1014
=> Add "Best Practices" section in the documentation

databricks/koalas/missing/window.py, databricks/koalas/tests/test_expanding.py, databricks/koalas/tests/test_rolling.py, databricks/koalas/window.py
This PR implements std and var at rolling and expanding in Series, Frame, SeriesGroupBy, FrameGroupBy.
```python
>>> s = ks.Series([5, 5, 6, 7, 5, 5, 5])
>>> s.rolling(3).std()
0         NaN
1         NaN
2    0.577350
3    1.000000
4    1.000000
5    1.154701
6    0.000000
```
```python
>>> df = ks.DataFrame({"A": s.to_numpy(), "B": s.to_numpy() ** 2})
>>> df.rolling(2).std()
A          B
0       NaN        NaN
1  0.000000   0.000000
2  0.707107   7.778175
3  0.707107   9.192388
4  1.414214  16.970563
5  0.000000   0.000000
6  0.000000   0.000000
```
=> Implement std and var at rolling and expanding in Series, Frame, SeriesGroupBy, FrameGroupBy

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/indexing.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_frame_plot.py, databricks/koalas/tests/test_reshape.py, databricks/koalas/window.py
Since the `ks` is used as koalas' import naming convention we recommended like `from databricks.koalas as ks`
Let's don't use `ks` as variable name for Series, use `kser` instead for unity & readability of our codes and to avoid confusing.
Plus, i think maybe we better also avoid using of just `s` as possible for more readability.
=> Let's use 'kser' rather than 'ks' or 's' as variable name for Series 

databricks/koalas/series.py
I found the same doctest for Dataframe.rank() and Series.rank().
- DataFrame.rank
https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.DataFrame.rank.html#databricks.koalas.DataFrame.rank
- Series.rank
https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.Series.rank.html#databricks.koalas.Series.rank
I think the doctest of Series.rank should be changed.
So, I modified it.
=> Modify doctest of Series.rank method

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py
This PR proposes to:
- Fix column comparison operators to treat NULL as False
- Resolve #999.
pandas treats NULL as False
```python
>>> pser
0    0.0
1    1.0
2    2.0
3    NaN
dtype: float64
>>> pser == 0
0     True
1    False
2    False
3    False  <- bool
dtype: bool
```
Koalas currently treats NULL as NULL
```python
>>> kser
0    0.0
1    1.0
2    2.0
3    NaN
>>> kser == 0
0     True
1    False
2    False
3     None  <- not bool
>>> kser == 0
0     True
1    False
2    False
3    False  <- bool
Name: 0, dtype: bool
```
=> Fix comparison operators to treat NULL as False

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_ops_on_diff_frames.py, docs/source/reference/frame.rst
Resolves #884 
This PR implement `where` of `DataFrame` 
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.where.html#pandas.DataFrame.where)
and `mask` of `DataFrame` (same as where except for the opposite cond)
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mask.html#pandas.DataFrame.mask)
```python
>>> df1 = ks.DataFrame({'A': [0, 1, 2, 3, 4], 'B':[100, 200, 300, 400, 500]})
>>> df2 = ks.DataFrame({'A': [0, -1, -2, -3, -4], 'B':[-100, -200, -300, -400, -500]})
>>> df1
A    B
0  0  100
1  1  200
2  2  300
3  3  400
4  4  500
>>> df2
A    B
0  0 -100
1 -1 -200
2 -2 -300
3 -3 -400
4 -4 -500
>>> df1.where(df1 > 0).sort_index()
A      B
0  NaN  100.0
1  1.0  200.0
2  2.0  300.0
3  3.0  400.0
4  4.0  500.0
>>> df1.where(df1 > 1, …
```
=> Implement DataFrame.where() & DataFrame.mask()

databricks/koalas/series.py
if given series like below,
```python
>>> kser = ks.Series([1, 100, 1, 100, 1, 100])
>>> kser
0      1
1    100
2      1
3    100
4      1
5    100
```
And if we want to get an index of maximum value, we can use `idxmax()`
the pandas doc says, "If multiple values equal the maximum, the 'first' row label with that value is returned",  (Actually, our doc have missed the part, 'first')
So in this case, it should returns '1' which is the first row label of those maximum values.
but the existing behavior returns random label like this.
```python
>>> kser.idxmax()
5
>>> kser.idxmax()
5
>>> kser.idxmax()
1
>>> kser.idxmax()
5
>>> kser.idxmax()
3
>>> kser.idxmax()
3
>>> kser.idxmax()
1
```
so i think it should be better fixed.
(those descriptions above are also applied to `idxmin()` exactly same)
=> Fix Series.idxmax() & idxmin() to make result properly

databricks/koalas/series.py
Remove `fillna` from `Series.between` because comparison operators fill `NULL` with a boolean value (#1029).
https://github.com/databricks/koalas/blob/fe93ac1e6247d5f1ee658d90a887eacbb5ffe655/databricks/koalas/series.py#L740-L744
=> Remove fillna from Series.between

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_stats.py
This PR proposes to make `corr` return `koalas.DataFrame`.
=> Make corr return koalas.DataFrame

databricks/koalas/generic.py, databricks/koalas/missing/frame.py, databricks/koalas/series.py, docs/source/reference/frame.rst
Implement DataFrame.first_valid_index
```python
>>> kdf = ks.DataFrame({'a': [None, 2, 3, 2],
...                     'b': [None, 2.0, 3.0, 1.0],
...                     'c': [None, 200, 400, 200]},
...                     index=['Q', 'W', 'E', 'R'])
>>> kdf
a    b      c
Q  NaN  NaN    NaN
W  2.0  2.0  200.0
E  3.0  3.0  400.0
R  2.0  1.0  200.0
>>> kdf.first_valid_index()
'W'
```
Support for MultiIndex columns
```
>>> kdf.columns = pd.MultiIndex.from_tuples([('a', 'x'), ('b', 'y'), ('c', 'z')])
>>> kdf
a    b      c
x    y      z
Q  NaN  NaN    NaN
W  2.0  2.0  200.0
E  3.0  3.0  400.0
R  2.0  1.0  200.0
>>> kdf.first_valid_index()
'W'
```
and integrate with `Series.first_valid_index()` into `generic.py` since they can share same implementation.
=> Implement first_valid_index for DataFrame & Integrate with Series

databricks/koalas/missing/series.py
I tried to implement Series.ravel(),
But i think it seems that it requires to compute whole dataset that has potentially raises out of memory.
So i think that we better don't support this function explicitly and let users know alternative. (`to_numpy().ravel()`)
```python
>>> ks.Series([1, 2, 3]).ravel()
databricks.koalas.exceptions.PandasNotImplementedError: The method `ks.Series.ravel()` is not implemented. If you want to collect your flattened underlying data as an NumPy array, use 'to_numpy().ravel()' instead.
```
=> Explicitly don't use Series.ravel()

databricks/koalas/base.py, databricks/koalas/tests/test_ops_on_diff_frames.py
As @ueshin pointed out in https://github.com/databricks/koalas/pull/1029#discussion_r350422624, the fix #1029 didn't cover the case below. This PR fixes it.
```python
>>> s1 = pd.Series([True, False, True], index=list("ABC"), name="x")
>>> s2 = pd.Series([True, True, False], index=list("ABD"), name="x")
>>> s1
A     True
B    False
C     True
Name: x, dtype: bool
>>> s2
A     True
B     True
D    False
Name: x, dtype: bool
>>> s1 | s2
A     True
B     True
C     True
D    False
Name: x, dtype: bool
>>> (ks.from_pandas(s1) | ks.from_pandas(s2)).sort_index()
A    True
B    True
C    True
D    None
Name: x, dtype: object
```
=> Add Null handling for different frames

databricks/koalas/series.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/tests/test_series.py
=> Allow Series.__getitem__ to take boolean Series

databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py, docs/source/reference/series.rst
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.pct_change.html#pandas.Series.pct_change
```python
>>> kser = ks.Series([90, 91, 85])
>>> kser
0    90
1    91
2    85
>>> kser.pct_change()
0         NaN
1    0.011111
2   -0.065934
>>> kser.pct_change(periods=2)
0         NaN
1         NaN
2   -0.055556
"""
```
=> Implement pct_change() for Series

databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/utils.py
Resolves #1088 
```python
>>> kser1
lama    speed      45.0
koalas  length    200.0
cow     speed       1.2
power      30.0
length    250.0
falcon  speed       1.5
weight    320.0
power       1.0
>>> kser2
lama    speed     -45.0
weight    200.0
length     -1.2
cow     speed      30.0
weight   -250.0
length      1.5
falcon  speed     320.0
weight      1.0
length     -0.3
```
existing `kser1 + kser2`  works like below which was not correct.
```python
>>> kser1 + kser2
cow     length    None
falcon  weight    None
cow     speed     None
falcon  speed     None
koalas  length    None
lama    speed     None
cow     power     None
falcon  power     None
falcon    None
falcon    None
falcon    None
lama    lama      None
lama      None
lama …
```
=> Produce correct output against multiIndex when 'compute.ops_on_diff_frames' is enabled

databricks/koalas/base.py, databricks/koalas/tests/test_numpy_compat.py
This PR implements `__array_ufunc__`  (see https://docs.scipy.org/doc/numpy/reference/ufuncs.html#output-type-determination) to allow some of basic ufunc can run against Koalas Series and Index (some dunder APIs).
```python
>>> kdf = np.add(kdf.id, kdf.id)
>>> type(kdf)
<class 'databricks.koalas.series.Series'>
>>> kdf
0     0
1     2
2     4
3     6
4     8
5    10
6    12
7    14
8    16
9    18
Name: id, dtype: int64
```
=> Add a basic NumPy ufunc compatibility

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
#885 
Inspired by https://github.com/databricks/koalas/issues/1003#issuecomment-556908359
the data type yield from iterator is `pd.Series`. I assume each row is small enough.
=> Implement Dataframe.iterrows using spark.dataframe.toLocalIterator

databricks/koalas/series.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/tests/test_series.py
**1..** We can avoid operations on different DataFrames. See below:
```python
>>> kdf = ks.DataFrame({'a': [1,2,3]})
>>> kdf.a.where(kdf.a > 1)
File "/.../koalas/databricks/koalas/series.py", line 3916, in where
kdf['__tmp_cond_col__'] = cond
File "/.../koalas/databricks/koalas/frame.py", line 8089, in __setitem__
kdf = align_diff_frames(assign_columns, self, value, fillna=False, how="left")
File "/.../koalas/databricks/koalas/utils.py", line 187, in align_diff_frames
combined = combine_frames(this, that, how=how)
File "/.../koalas/databricks/koalas/utils.py", line 122, in combine_frames
"Cannot combine the series or dataframe because it comes from a different dataframe. "
ValueError: …
```
=> Avoid to return a different DataFrame from Series where (and multiple small bug fixes)

databricks/koalas/series.py, databricks/koalas/tests/test_series.py
Reopen of #1065
fix more properly with considering of more examples commented at https://github.com/databricks/koalas/pull/1065#issuecomment-558303388
```python
>>> pser = pd.Series([1, 100, None, 100, 1, 100], index=[10, 3, 5, 2, 1, 8])
>>> kser = ks.from_pandas(pser)
>>>
>>> pser.idxmax()
3
>>> kser.idxmax()
3
>>> pser.idxmin()
10
>>> kser.idxmin()
10
```
=> Fix idxmax() / idxmin() for Series work properly

databricks/koalas/base.py, databricks/koalas/numpy_compat.py, databricks/koalas/tests/test_numpy_compat.py
This PR completes NumPy's ufunc support (followup of https://github.com/databricks/koalas/pull/1096).
See also https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#standard-array-subclasses
E.g.:
```python
>>> kser = np.sqrt(kdf.id)
>>> type(kser)
<class 'databricks.koalas.series.Series'>
>>> kser
0    0.000000
1    1.000000
2    1.414214
3    1.732051
4    2.000000
5    2.236068
6    2.449490
7    2.645751
8    2.828427
9    3.000000
```
=> Complete NumPy ufunc compatibility in Series

databricks/koalas/usage_logging/__init__.py
When logging is enabled, docs for replaced properties didn't exist, and as a side-effect, doctests for the properties were not run.
=> Add __doc__ for replaced property when logging is enabled.

.travis.yml, requirements-dev.txt, setup.py
Seems still unstable with PyArrow 0.15. Let me set the upper bound again for now.
=> Set the pyarrow version upper bound again.

databricks/koalas/base.py, databricks/koalas/series.py, databricks/koalas/tests/test_series.py
Unlike pandas, `koalas.Series` can't set the index name like below.
```python
>>> pser = pd.Series([1, 2, 3, 4, 5])
>>> pser.index.name = 'koalas'
>>> pser.index.name
'koalas'
>>> kser = ks.Series([1, 2, 3, 4, 5])
>>> kser.index.name = 'koalas'
>>> kser.index.name
```
For MultiIndex also
```python
>>> midx = pd.MultiIndex([['lama', 'cow', 'falcon'],
...                       ['speed', 'weight', 'length']],
...                      [[0, 0, 0, 1, 1, 1, 2, 2, 2],
...                       [0, 1, 2, 0, 1, 2, 0, 1, 2]])
>>> pser = pd.Series([45, 200, 1.2, 30, 250, 1.5, 320, 1, 0.3], index=midx)
>>> pser.index.names
FrozenList([None, None])
>>> pser.index.names = ['hello', 'koalas']
>>> pser.index.names
FrozenList(['hello', 'koalas'])
>>> midx = pd.MultiIndex([['lama', 'cow', 'falcon'],
... …
```
=> Setting index name / names for Series

databricks/koalas/generic.py, databricks/koalas/tests/test_groupby.py
Resolve #1095 
```python
>>> kser = ks.Series([1, 2, 3, 4, 5], name='x')
>>> kser.groupby('x').head(2)
...
KeyError: ('x',)
```
```python
>>> pdf = pd.DataFrame({'a': [1, 2, 6, 4, 4, 6, 4, 3, 7],
...                             'b': [4, 2, 7, 3, 3, 1, 1, 1, 2],
...                             'c': [4, 2, 7, 3, None, 1, 1, 1, 2],
...                             'd': list('abcdefght')},
...                            index=[0, 1, 3, 5, 6, 8, 9, 9, 9])
>>> pdf.groupby(pdf)
...
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
>>> pdf.a.groupby(pdf)
...
ValueError: Grouper for '<class 'pandas.core.frame.DataFrame'>' not 1-dimensional
```
=> disable 'str' for 'SeriesGroupBy', disable 'DataFrame' for 'GroupBy'

databricks/koalas/namespace.py, docs/source/reference/general_functions.rst
Resolves #1044 
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_numeric.html#pandas.to_numeric)
i think we can directly use pandas one, except the case of `Series`
```python
>>> kser = ks.Series(['1.0', '2', '-3'])
>>> kser
0    1.0
1      2
2     -3
>>> ks.to_numeric(kser)
0    1.0
1    2.0
2   -3.0
Name: 0, dtype: float32
If given Series contains invalid value to cast float, just cast it to `np.nan`
>>> kser = ks.Series(['apple', '1.0', '2', '-3'])
>>> kser
0    apple
1      1.0
2        2
3       -3
>>> ks.to_numeric(kser)
0    NaN
1    1.0
2    2.0
3   -3.0
Name: 0, dtype: float32
Also support for list, tuple, np.array, or a single numeric type
>>> ks.to_numeric(['1.0', '2', '-3'])
array([ 1.,  2., -3.])
>>> …
```
=> Implements Top-level function to_numeric()

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, docs/source/reference/frame.rst
Resolves #1043 
```python
>>> kdf = ks.DataFrame({'a': [1, 2, 3, 2],
...                     'b': [4.0, 2.0, 3.0, 1.0],
...                     'c': [300, 200, 400, 200]})
>>> kdf
a    b    c
0  1  4.0  300
1  2  2.0  200
2  3  3.0  400
3  2  1.0  200
>>> kdf.idxmax()
a    2
b    0
c    2
```
For Multi-column Index
```python
>>> kdf = ks.DataFrame({'a': [1, 2, 3, 2],
...                     'b': [4.0, 2.0, 3.0, 1.0],
...                     'c': [300, 200, 400, 200]})
>>> kdf.columns = pd.MultiIndex.from_tuples([('a', 'x'), ('b', 'y'), ('c', 'z')])
>>> kdf
a    b    c
x    y    z
0  1  4.0  300
1  2  2.0  200
2  3  3.0  400
3  2  1.0  200
>>> kdf.idxmax()
(a, x)    2
(b, y)    0
(c, z)    2
```
=> Implements idxmax()/idxmin() for DataFrame

docs/source/reference/indexing.rst
as commented in https://github.com/databricks/koalas/pull/1114#discussion_r356962995,
i filled up the missing docs for `Index` and `MultiIndex`
=> Fill up the missing docs for Index/MultiIndex

databricks/koalas/frame.py, databricks/koalas/indexes.py, databricks/koalas/missing/frame.py, docs/source/reference/frame.rst
This PR proposes `DataFrame.info`.
```python
>>> ks.range(100).info()
<class 'databricks.koalas.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 1 columns):
id    100 non-null int64
```
Resolves #872
=> Implement DataFrame.info

databricks/koalas/base.py, databricks/koalas/tests/test_indexes.py
In pandas, `pd.MultiIndex.isna()`, `pd.MultiIndex.isnull()`, `pd.MultiIndex.notna()`, `pd.MultiIndex.notnull()` return same error message that `isna is not defined for MultiIndex` like below.
```python
>>> pidx = pd.MultiIndex.from_tuples([('a', 'x', 1), ('b', 'y', 2)])
>>> pidx.isna()
...
NotImplementedError: isna is not defined for MultiIndex
>>> pidx.isnull()
...
NotImplementedError: isna is not defined for MultiIndex
>>> pidx.notna()
...
NotImplementedError: isna is not defined for MultiIndex
>>> pidx.notnull()
...
NotImplementedError: isna is not defined for MultiIndex
```
i think we'd better mimic them for our functions.
=> 'isna' type functions should return proper message for MultiIndex

databricks/koalas/frame.py, databricks/koalas/tests/test_numpy_compat.py
This PR proposes to complete NumPy's universal functions support against DataFrame.
```python
>>> np.log(kdf)
id
0       NaN
1  0.000000
2  0.693147
3  1.098612
4  1.386294
5  1.609438
6  1.791759
7  1.945910
8  2.079442
9  2.197225
```
=> Complete NumPy universal functions compat for DataFrames

databricks/koalas/frame.py
This PR fixes the existing DataFrame's arithmetic and comparison APIs to take the same DataFrame as its argument. See below:
```python
>>> kdf + kdf
id
0   0
1   2
2   4
3   6
4   8
5  10
6  12
7  14
8  16
9  18
```
=> Support arithmetic and comparison APIs on itself in DataFrame

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
the existing implementation can support only `Index`
so fix it to support `MultiIndex` also.
```python
>>> kidx = ks.MultiIndex.from_tuples([('a', 'x'), ('b', 'y')])
>>> kidx.names = ['hello', 'koalas']
>>> kidx
MultiIndex([('a', 'x'),
('b', 'y'),
('c', 'z')],
names=['hello', 'koalas'])
>>> kidx.rename(['aloha', 'databricks'])
MultiIndex([('a', 'x'),
('b', 'y')],
names=['aloha', 'databricks'])
```
=> Fix rename() for Index to support MultiIndex also

requirements-dev.txt, setup.py
Pandas 1.0.0 will be released soon and it says it will only support Python 3.6.1 and higher, and also it might contain behavior changes.
We will still support Python 3.5 for a while, we should set the upper-bound for pandas for now to confirm Koalas works with it.
=> Set the upper-bound for pandas.

databricks/koalas/base.py, databricks/koalas/tests/test_series.py
This PR Resolves comment https://github.com/databricks/koalas/pull/949#discussion_r356364770
```python
>>> kdf
a    b
0  1  NaN
1  2  1.0
2  3  NaN
>>> kdf.a
0    1
1    2
2    3
Name: a, dtype: int64
>>> kdf.a.value_counts()
2    1
3    1
1    1
Name: a, dtype: int64
```
=> Fix value_counts() to work properly when dropna is True

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.MultiIndex.from_product.html#pandas.MultiIndex.from_product
```python
>>> numbers = [0, 1, 2]
>>> colors = ['green', 'purple']
>>> ks.MultiIndex.from_product([numbers, colors],
...                            names=['number', 'color'])
MultiIndex([(0,  'green'),
(0, 'purple'),
(1,  'green'),
(1, 'purple'),
(2,  'green'),
(2, 'purple')],
names=['number', 'color'])
```
=> Implement from_product() for MultiIndex

docs/source/getting_started/install.rst, docs/source/user_guide/best_practices.rst
It's nothing special.
I found a few typos, check it out please.
- in docs/source/getting_started/install.rst
- un-ter -> un-tar
- in docs/source/user_guide/best_practices.rst 
- interpretor -> interpreter
Thank you.
=> Fix some typos in install.rst & best_practices.rst

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py
an alias for `size`
```python
>>> pidx = pd.Index(range(1000))
>>> kidx = ks.Index(range(1000))
>>> len(pidx)
1000
>>> len(kidx)
1000
```
for MultiIndex
```python
>>> pidx = pd.MultiIndex.from_tuples([('a', 'x', 1), ('b', 'y', 2), ('c', 'z', 3)])
>>> kidx = ks.MultiIndex.from_tuples([('a', 'x', 1), ('b', 'y', 2), ('c', 'z', 3)])
>>> len(pidx)
3
>>> len(kidx)
3
```
=> Add len() for Index & MultiIndex

databricks/koalas/indexing.py, databricks/koalas/series.py, databricks/koalas/tests/test_indexing.py
Resolve #1158 
```python
>>> kdf
max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
>>> kdf.loc['cobra':'viper', 'max_speed']
cobra    1
viper    4
Name: max_speed, dtype: int64
>>> kdf.to_pandas().loc['cobra':'viper', 'max_speed']
cobra    1
viper    4
Name: max_speed, dtype: int64
```
=> Fix .loc to work properly when using 'slice'

databricks/koalas/internal.py, databricks/koalas/typedef.py
I use the manual build version of PySpark for development. As of https://github.com/apache/spark/commit/ee8d66105885929ac0c0c087843d70bf32de31a1, we need some changes accordingly.
=> Prepare PySpark 3 for dev purpose

databricks/koalas/internal.py, databricks/koalas/tests/test_indexes.py
```python
column_index = pd.MultiIndex.from_tuples([('a', 'x'), ('a', 'y'), ('b', 'z')])
pdf = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=column_index)
pdf.set_index(('a', 'x'), append=True, inplace=True)
ks.from_pandas(pdf)
```
Before:
```
File "/.../koalas/databricks/koalas/namespace.py", line 70, in from_pandas
return DataFrame(pobj)
File "/.../koalas/databricks/koalas/frame.py", line 380, in __init__
super(DataFrame, self).__init__(_InternalFrame.from_pandas(pdf))
File "/.../koalas/databricks/koalas/internal.py", line 771, in from_pandas
column_index_names=column_index_names)
File "/.../koalas/databricks/koalas/internal.py", line 431, in __init__
for …
```
=> Fix column name as a tuple in multi column index

databricks/koalas/groupby.py, databricks/koalas/missing/groupby.py, databricks/koalas/tests/test_groupby.py
Close #1166 
Manual test:
```
>>> df = ks.DataFrame({'a': [1, 1, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
20/01/04 18:16:35 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
>>> df.groupby('a').describe()
20/01/04 18:17:09 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single partition, this can cause serious performance degradation.
20/01/04 18:17:10 WARN WindowExec: No Partition Defined for Window operation! Moving all data to a single …
```
=> DataFrameGroupBy.describe

databricks/koalas/indexes.py, databricks/koalas/missing/indexes.py, docs/source/reference/indexing.rst
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.is_all_dates.html#pandas.Index.is_all_dates
```python
>>> idx = ks.Index([datetime(2019, 1, 1, 0, 0, 0), datetime(2019, 2, 3, 0, 0, 0)])
>>> idx
DatetimeIndex(['2019-01-01', '2019-02-03'], dtype='datetime64[ns]', freq=None)
>>> idx.is_all_dates
True
>>> idx = ks.Index([datetime(2019, 1, 1, 0, 0, 0), None])
>>> idx
DatetimeIndex(['2019-01-01', 'NaT'], dtype='datetime64[ns]', freq=None)
>>> idx.is_all_dates
True
>>> idx = ks.Index([0, 1, 2])
>>> idx
Int64Index([0, 1, 2], dtype='int64')
```
=> Add property is_all_dates for Index/MultiIndex

databricks/koalas/groupby.py
=> Create docstring for ``DataFrameGroupBy.describe`` and reimplement leveraging `_InternalFrame`

databricks/koalas/frame.py, databricks/koalas/plot.py, databricks/koalas/tests/test_indexes.py, databricks/koalas/utils.py
This PR syncs Koalas to support PySpark 3.0. It's development purpose mainly.
=> Sync with PySpark upstream in Apache Spark

databricks/koalas/frame.py, docs/source/reference/io.rst
pandas always overwrites. Currently, only JSON and CSV overwrites in Koalas. This PR proposes to consistently overwrite for now.
```python
>>> pd.DataFrame({'a':[1,2,3]})
a
0  1
1  2
2  3
>>> pd.DataFrame({'a':[1,2,3]}).to_parquet("/tmp/abc.parquet")
>>> pd.DataFrame({'a':[1,2,3]}).to_parquet("/tmp/abc.parquet")
>>> pd.DataFrame({'a':[1,2,3]}).to_parquet("/tmp/abc.parquet")
```
=> Change default write mode to overwrite to be consistent with pandas

databricks/koalas/indexes.py, databricks/koalas/missing/indexes.py, docs/source/reference/indexing.rst
```python
idx = ks.Index(['a', 'b', 'c'])
midx = ks.MultiIndex.from_tuples([('a', 'x'), ('b', 'y'), ('c', 'z')])
idx.equals(idx)
midx.equals(idx)
from databricks.koalas.config import option_context
with option_context('compute.ops_on_diff_frames', True):
idx.equals(ks.Index(['a', 'b', 'c']))
```
=> Implement Index/MultiIndex.equals

databricks/koalas/internal.py
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<command-3232250281008415> in <module>()
1 import pandas as pd
2 import numpy as np
----> 3 import databricks.koalas as ks
4 from pyspark.sql import SparkSession
/databricks/python/lib/python3.5/site-packages/databricks/koalas/__init__.py in <module>()
47     os.environ["ARROW_PRE_0_15_IPC_FORMAT"] = "1"
48 
---> 49 from databricks.koalas.frame import DataFrame
50 from databricks.koalas.indexes import Index, MultiIndex
51 from databricks.koalas.series import Series
/databricks/python/lib/python3.5/site-packages/databricks/koalas/frame.py in <module>()
47 from databricks import koalas as ks  # For running doctests and reference …
```
=> Fix circular reference between Series and _InternalFrame in type hint for old Python 3.5.x

databricks/koalas/indexes.py
`identical` and `equals` should be `True` for the comparison between the same object.
```py
>>> idx = pd.Index(['a', 'b', 'c'])
>>> midx = pd.MultiIndex.from_tuples([('a', 'x'), ('b', 'y'), ('c', 'z')])
>>> midx.names = ("nameA", "nameB")
>>> idx.identical(idx)
True
>>> midx.identical(midx)
True
>>> idx.equals(idx)
True
>>> midx.equals(midx)
True
```
=> Fix identical and equals for the comparison between the same object.

databricks/koalas/frame.py, databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/internal.py
The usage of `_InternalFrame.attach_default_index` is spreading out of `_InternalFrame`, and we might not be able to control the index column name.
We should make the function generate the index column name instead of the fixed name.
=> Make attach_default_index generate the index column name.

databricks/koalas/frame.py
It seems failing in my InteliJ env. This PR explicitly add `+ELLIPSIS` for `...`.
```
Expected:
== Parsed Logical Plan ==
...
== Analyzed Logical Plan ==
...
== Optimized Logical Plan ==
...
...
Got:
== Parsed Logical Plan ==
Project [__index_level_0__#0L, id#1L]
+- Project [__index_level_0__#0L, id#1L, monotonically_increasing_id() AS __natural_order__#4L]
+- LogicalRDD [__index_level_0__#0L, id#1L], false
<BLANKLINE>
== Analyzed Logical Plan ==
__index_level_0__: bigint, id: bigint
Project [__index_level_0__#0L, id#1L]
```
=> Add +ELLIPSIS to DataFrame.explain doctest

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/internal.py, databricks/koalas/series.py, databricks/koalas/tests/test_internal.py
This PR adds:
- `attach_distributed_sequence_column` for the case when we need a sequence in an API.
- Use `SPARK_DEFAULT_INDEX_NAME` instead of `SPARK_INDEX_NAME_FORMAT(0)` for default column name.
=> Add attach_distributed_sequence_column with SPARK_DEFAULT_INDEX_NAME in InternalFrame

databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
Can be tested with the codes below:
```python
kdf = ks.DataFrame({'cust_id':['a', 'a', 'a', 'b', 'b'],
'sales': [100, 200, 300, 400, 500],
'days':[12.1,13.1,14.1,78.1,87.2]})
kdf.groupby('cust_id')['days'].apply(lambda x: x.ewm(alpha=0.5, adjust=False).mean())
pdf = kdf.to_pandas()
pdf.groupby('cust_id')['days'].apply(lambda x: x.ewm(alpha=0.5, adjust=False).mean())
```
```
0    12.10
1    12.60
2    13.35
3    78.10
4    82.65
Name: days, dtype: float64
```
Basic idea is that, it creates a DataFrame from Series to reuse existing implementations, and resolves the columns by name.
=> Select the series correctly in SeriesGroupBy APIs

databricks/koalas/generic.py, databricks/koalas/indexing.py
This moves `iat `implementation to `iloc` and adds the infrastructure to support other types of access via `iloc`.
=> Move iat implementation to iloc.

databricks/koalas/groupby.py, databricks/koalas/internal.py
We should not have renamed the columns in `_InternalFrame.with_new_columns`, otherwise the new column names could be unexpectable.
=> Fix `_InternalFrame.with_new_columns` not to rename columns.

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series.py
Fixes `DataFrame/Series.clip` function to use `_InternalFrame.with_new_columns` and preserve its index.
=> Fix clip to use `_InternalFrame.with_new_columns`.

databricks/koalas/config.py, databricks/koalas/frame.py, docs/source/user_guide/options.rst
Koalas doesn't guarantee the row ordering, so `head` could return some rows from distributed partitions and the result is not deterministic, which might confuse users. (See #411, #1064, or #1219)
```py
>>> spark = ks.utils.default_session({'spark.master': 'local-cluster[4, 2, 1024]'})
>>> spark.conf.set('spark.sql.execution.arrow.enabled', True)
>>> kdf = ks.DataFrame({'a': range(10)})
>>> pdf = kdf.to_pandas().head(3)
```
```py
>>> for _ in range(100):
...     assert kdf.head(3).to_pandas().equals(pdf), 'NOT equals.'
... else:
...     print('equals.')
...
File "<stdin>", line 2, in <module>
AssertionError: NOT equals.
```
If `compute.ordered_head` is set to True, Koalas performs natural ordering beforehand, but it will …
=> Add a config to perform natural ordering when head.

databricks/conftest.py, databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/indexes.py, databricks/koalas/namespace.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_groupby.py, databricks/koalas/tests/test_indexes.py
This PR targets to reduce the elapsed time in tests by using less partitions in shuffle.
Seems it can decrease roughly around 15 ~ 20 mins.
=> Reduce test time by lowering 'spark.sql.shuffle.partitions'

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Previously, it threw the exception as below:
```
File "/.../koalas/databricks/koalas/frame.py", line 5398, in sort_values
by = [self[colname]._scol for colname in by]
File "/.../koalas/databricks/koalas/frame.py", line 5398, in <listcomp>
by = [self[colname]._scol for colname in by]
File "/.../koalas/databricks/koalas/frame.py", line 8334, in __getattr__
"'%s' object has no attribute '%s'" % (self.__class__.__name__, key))
AttributeError: 'DataFrame' object has no attribute '_scol'
```
```python
mi = pd.MultiIndex.from_tuples([('a', 'b')])
kdf = ks.range(10)
kdf.columns = mi
kdf.sort_values("a")
```
=> Throw a better exception in DataFrame.sort_values when multi-index column is used

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
`DataFrame.fillna()` should not change the index values.
```py
>>> pdf = pd.DataFrame({'x': [np.nan, 2, 3, 4, np.nan, 6],
...                     'y': [1, 2, np.nan, 4, np.nan, np.nan],
...                     'z': [1, 2, 3, 4, np.nan, np.nan]}).set_index(['x', 'y'])
>>>
>>> pdf.fillna(-1)
z
x   y
NaN 1.0  1.0
2.0 2.0  2.0
3.0 NaN  3.0
4.0 4.0  4.0
NaN NaN -1.0
6.0 NaN -1.0
>>> pdf.fillna({'x': -1, 'y': -2, 'z': -5})
z
x   y
NaN 1.0  1.0
2.0 2.0  2.0
3.0 NaN  3.0
4.0 4.0  4.0
NaN NaN -5.0
6.0 NaN -5.0
```
whereas:
```py
>>> ks.from_pandas(pdf).fillna(-1)
z
x    y
-1.0  1.0  1.0
2.0  2.0  2.0
3.0 -1.0  3.0
4.0  4.0  4.0
-1.0 -1.0 -1.0
6.0 -1.0 -1.0
>>> ks.from_pandas(pdf).fillna({'x': -1, 'y': -2, 'z': -5})
z
x    y
-1.0  1.0  1.0
2.0  2.0 …
```
=> Fix fillna not to change index values.

databricks/koalas/tests/test_rolling.py
A line of code was testing `Expanding`  rather than `Rolling` in `test_rolling.py`
=> [MINOR] one of test for Rolling is not working properly

databricks/koalas/frame.py, databricks/koalas/tests/test_ops_on_diff_frames.py
Fix `DataFrame.__setitem__` with tuple-named Series derived from a different DataFrame.
e.g.,:
```py
>>> ks.set_option("compute.ops_on_diff_frames", True)
>>> kdf = ks.DataFrame({'a': [1, 2, 3, 2], 'b': [4.0, 2.0, 3.0, 1.0]})
>>> kdf['c'] = ks.Series([10, 20, 30, 20], name=('1', '2'))
>>> kdf
c
NaN  a    b
0  10  1  4.0
1  20  2  2.0
3  20  2  1.0
2  30  3  3.0
```
The result should be:
```py
>>> kdf
a    b   c
0  1  4.0  10
1  2  2.0  20
3  2  1.0  20
2  3  3.0  30
```
=> Fix DataFrame.__setitem__ with tuple-named Series.

databricks/koalas/series.py
Resolve https://github.com/databricks/koalas/issues/1248
Since the Python interpreter calls \_\_repr\_\_ if \_\_str\_\_ is not implemented, 
the output will be identical to pandas using the implemented \_\_repr\_\_ of __series.py__.
```python
>>> ks = ks.Series([1, 3, 5, np.nan, 6, 8])
>>> print(ks)
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
>>> print(str(ks))
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
>>> print(repr(ks))
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
>>> ps = pd.Series([1, 3, 5, np.nan, 6, 8])
>>> print(ps)
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
>>> print(str(ps))
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
>>> …
```
=> Fix output of print() matches with pandas of Series

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Fix `fillna` to support partial column index for multi-index columns.
E.g.,
```py
>>> pdf = pd.DataFrame({('x', 'a'): [np.nan, 2, 3, 4, np.nan, 6],
...                     ('x', 'b'): [1, 2, np.nan, 4, np.nan, np.nan],
...                     ('y', 'c'): [1, 2, 3, 4, np.nan, np.nan]})
>>> pdf
x         y
a    b    c
0  NaN  1.0  1.0
1  2.0  2.0  2.0
2  3.0  NaN  3.0
3  4.0  4.0  4.0
4  NaN  NaN  NaN
5  6.0  NaN  NaN
>>> pdf.fillna({'x': -1})
x         y
a    b    c
0 -1.0  1.0  1.0
1  2.0  2.0  2.0
2  3.0 -1.0  3.0
3  4.0  4.0  4.0
4 -1.0 -1.0  NaN
5  6.0 -1.0  NaN
```
=> Fix fillna to support partial column index for multi-index columns.

databricks/koalas/generic.py, databricks/koalas/tests/test_groupby.py
Resolve https://github.com/databricks/koalas/issues/1252
By doing type validation on item __as_index__  in groupby, 
I think it will be fine if other parameters are added later.
Now, when checking grouping of multiple columns, koalas can find mistakes.
```python
>>> pdf = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
...                   'foo', 'bar', 'foo', 'foo'],
...                    'B': ['one', 'one', 'two', 'three',
...                    'two', 'two', 'one', 'three'],
...                    'C': np.random.randn(8),
...                    'D': np.random.randn(8)})
>>> kdf = ks.from_pandas(pdf)
>>> kdf.groupby('B', 'A').sum().sort_index()
File "/Users/hwpark/Desktop/dev/git_koalas/koalas/databricks/koalas/gene …
```
=> Add as_index check logic to groupby parameter

databricks/koalas/frame.py
We can apply `DataFrame._apply_series_op` util function to `DataFrame.round` as well.
=> Apply utils to `DataFrame.round`.

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/namespace.py, databricks/koalas/strings.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_namespace.py, databricks/koalas/tests/test_reshape.py, databricks/koalas/tests/test_series.py, databricks/koalas/tests/test_series_string.py
we're raising `ValueError` for some 'NotImplemented' elements.
i think it's better to raise `NotImplementedError` rather than `ValueError` for those elements so that we can find more easily when we want to implement them.
=> Raising NotImplementedError for elements that actually are not implemented.

dev/pytest
Before
After
@HyukjinKwon @ueshin @itholic 
What do you think?
=> Use `--color=yes` in pytest to make logs on GitHub Action look pretty

.github/workflows/master.yml
- Cache properly for conda env. We should better cache environment.
- Name jobs pretty
- Separate dependency installation and run tests in Github Actions
- Minor commets fixes.
=> Cache properly for conda env, name jobs pretty and separate dependency installation and run tests in Github Actions

.github/workflows/master.yml, .travis.yml
Spark 2.4.5 was released. This PR proposes to use it in both Travis CI and Github Actions.
=> Use Spark 2.4.5 in Travis and Github Actions

databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
This PR proposes to implement `DataFrame.apply` with both `axis` 0 and 1. Note that, `DataFrame.apply(..., axis=1)` with global aggregations is impossible.
It can be tested with the examples below:
```python
df = ks.DataFrame([[4, 9]] * 10, columns=['A', 'B'])
df.apply(np.sqrt, axis=0)
def sqrt(x) -> ks.Series[float]:
return np.sqrt(x)
df.apply(sqrt, axis=0)
df.apply(np.sum, axis=1)
def summation(x) -> int:
return np.sum(x)
df.apply(summation, axis=1)
```
Basically the approach is using group map Pandas UDF by grouping by partitions.
```python
from pyspark.sql.functions import pandas_udf, PandasUDFType
from pyspark.sql import functions as F
df = spark.createDataFrame(
[(1, 1.0), (1, 2.0), (2, 3.0), (2, 5.0), (2, 10.0)],
("id", "v")) …
```
=> Implement DataFrame.apply

databricks/koalas/frame.py, databricks/koalas/indexing.py, databricks/koalas/internal.py
Now that we can remove workarounds added previously in `_InternalFrame.scol_for` and `.column_name_for`.
Now they only allow tuples for columns or strings as index column names to avoid misuse of these methods.
=> Remove workarounds in `_InternalFrame.scol_for` and `.column_name_for`.

dev/gendoc.py
Currently, draft release note is included in the documentation. We should only include published release notes. Travis CI and Read the Docs can see this because it uses my github auth totkens to unlimit Github API calls., so they can upload.
This PR filter out draft release note explicitly. I manually tested and verified it works.
FYI, the JSON looks like this:
```json
{
"url": "https://api.github.com/repos/databricks/koalas/releases/18404404",
"assets_url": "https://api.github.com/repos/databricks/koalas/releases/18404404/assets",
"upload_url": "https://uploads.github.com/repos/databricks/koalas/releases/18404404/assets{?name,label}",
"html_url": "https://github.com/databricks/koalas/releases/tag/v0.11.0",
"id": 18404404,
"node_id": "MDc6UmVsZWFzZTE4NDA0NDA0",
"tag_name": "v0.11.0", …
```
=> Filter out draft release notes when generating release documentation

.github/workflows/master.yml, dev/pytest
Codecov in Github Actions are not correctly working for now:
```
...
==> GitHub Actions detected.
project root: .
Yaml found at: codecov.yml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy exists disable via -X coveragepy
-> Running coverage xml
==> Searching for coverage reports in:
+ .
-> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
+ ./coverage.xml bytes=484024
==> Appending adjustments
http://docs.codecov.io/docs/fixing-reports
-> No adjustments found
==> Gzipping contents
==> Uploading reports
url: https://codecov.io
query: branch=master&commit=31b9ae070e85c9b84c100e2861ec9eacf1e5190a&build=&build_url=&name=&tag=&slug=databricks%2Fkoalas&service=github-actions&flags=&pr=&job=
-> Pinging Codecov …
```
=> Add Codecov support in Github Actions.

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
This PR proposes to implement `DataFrame.query`
```python
>>> df = ks.DataFrame({'A': range(1, 6),
...                    'B': range(10, 0, -2),
...                    'C C': range(10, 5, -1)})
>>> df
A   B  C C
0  1  10   10
1  2   8    9
2  3   6    8
3  4   4    7
4  5   2    6
>>> df.query('A > B')
A  B  C C
4  5  2    6
The previous expression is equivalent to
>>> df[df.A > df.B]
A  B  C C
4  5  2    6
For columns with spaces in their name, you can use backtick quoting.
>>> df.query('B == `C C`')
A   B  C C
0  1  10   10
The previous expression is equivalent to
>>> df[df.B == df['C C']]
A   B  C C
0  1  10   10
```
=> Implement DataFrame.query

databricks/koalas/frame.py, databricks/koalas/groupby.py, databricks/koalas/series.py, databricks/koalas/tests/test_utils.py, databricks/koalas/utils.py
There is some mismatch between pandas and Koalas when using `inplace` parameter like the below.
- pandas (only allows `True` or `False`)
```python
>>> pdf
A    B    C  D
0  1  2.0  NaN  0
1  1  4.0  NaN  1
2  2  NaN  NaN  5
3  2  3.0  1.0  4
>>> pdf.fillna('A', inplace=1)
...
ValueError: For argument "inplace" expected type bool, received type int.
```
- Koalas (allows any type)
```python
>>> kdf
A    B    C  D
0  1  2.0  NaN  0
1  1  4.0  NaN  1
2  2  NaN  NaN  5
3  2  3.0  1.0  4
>>> kdf.fillna('A', inplace=1)
>>> kdf
A    B    C  D
0  1  2.0    A  0
1  1  4.0    A  1
2  2    A    A  5
3  2  3.0  1.0  4
```
i think we should fix them to make work same with pandas.
so, i think we'd better have an util function `validate_bool_kwarg` for this (and also …
=> Add util function validate_bool_kwarg

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
This PR implements a Koalas specific API in order to directly use pandas DataFrame APIs.
For pandas Series APIs, we have a workaround for instance:
```python
>>> ks.range(10)[['id']].apply(lambda series: series)['id']
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: id, dtype: int64
```
however, there is no way to use the APIs in the pandas DataFrame.
There is a similar API called [`map_partitions`](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions) in Dask and this API is inspired by it.
=> Implement DataFrame.map_in_pandas

docs/source/getting_started/install.rst
By default, Anaconda does not have `conda-forge` channel in the config, causing
```
conda install koalas
```
from [Getting started](https://koalas.readthedocs.io/en/latest/getting_started/install.html) to fail. The issue is not apparent for the people not accustomed to `conda` as demonstrated in [this SO post](https://stackoverflow.com/questions/60263669/how-to-install-koalas-with-conda/60263951#60263951).
=> add conda-forge channel

databricks/koalas/frame.py
This is nit.
there is a missing case for `validate_bool_kwarg` is found, just added.
=> [MINOR] applying util func 'validate_bool_kwarg' to 'DataFrame.query'

databricks/koalas/frame.py
As requested at https://github.com/databricks/koalas/pull/1273#discussion_r380129074 ,
and since `map_in_pandas` (#1276 ) has been merged,
just uncommented existing doctest for DataFrame.query
=> [MINOR] Uncomment doctest for DataFrame.query

databricks/koalas/frame.py
This is a follow-up of #1273.
The Spark column names are not always the same as its column label.
This PR is to rename data columns prior to filter to make sure the column names are as expected.
=> Rename data columns prior to filter to make sure the column names are as expected.

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/series.py, databricks/koalas/series.py, databricks/koalas/testing/utils.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series.py, docs/source/reference/frame.rst, docs/source/reference/series.rst
Implement `axes` for DataFrame & Series.
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.axes.html)
```python
>>> df = ks.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
>>> df.axes
[RangeIndex(start=0, stop=2, step=1), Index(['col1', 'col2'],
dtype='object')]
```
and add test function `assert_list_eq` for comparing all member of list with `assert_eq`
=> Add 'axes' for DataFrame & Series and 'assert_list_eq' for testing

.github/workflows/master.yml, .travis.yml, databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/missing/frame.py, databricks/koalas/missing/indexes.py, databricks/koalas/missing/series.py, databricks/koalas/namespace.py, databricks/koalas/tests/test_dataframe_conversion.py, databricks/koalas/tests/test_expanding.py, databricks/koalas/tests/test_groupby.py, databricks/koalas/tests/test_indexes.py, databricks/koalas/tests/test_reshape.py, databricks/koalas/tests/test_rolling.py, databricks/koalas/tests/test_series_conversion.py, databricks/koalas/tests/test_series_plot.py, databricks/koalas/tests/test_stats.py, databricks/koalas/window.py, requirements-dev.txt, setup.py
Related with #1194 
This PR is for updating newly added & deprecated & deleted APIs on pandas 1.0.0 to keep compatible with pandas 1.0.0 to be released soon, based on [What’s new in 1.0.0](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html)
=> Support pandas >=1.0.0

databricks/koalas/namespace.py, databricks/koalas/tests/test_csv.py
This PR proposes to let extra options have higher priority to allow workarounds.
For instance, after this PR, you can disable schema inference:
```python
>>> ks.read_csv("tmp.csv").dtypes
a    int32
b    int32
c    int32
dtype: object
>>> ks.read_csv("tmp.csv", inferSchema=False).dtypes
a    object
b    object
c    object
```
=> Let extra options have higher priority to allow workarounds in read_csv

databricks/koalas/tests/test_csv.py
The PR was synced after Black integration and the tests passed at https://github.com/databricks/koalas/pull/1296. But looks there was a sync'ing problem.
=> Fix style at test_csv.py according to the linter script

databricks/koalas/missing/frame.py, databricks/koalas/missing/indexes.py, databricks/koalas/missing/series.py
Missing/deprecated functions/properties removed in pandas 1.0 were also removed from Koalas (#1197), but we should still show error messages at least when a user using pandas<1.0 tries to use such functions/properties.
=> Add removed missing/deprecated functions/properties back.

databricks/koalas/frame.py
This PR adds some documentations for the fact that index is switched to the default index when type hints are specified.
See also #1307.
=> Add a note when type hint is provided to DataFrame.apply

databricks/koalas/frame.py
As we discussed at https://github.com/databricks/koalas/pull/1291#discussion_r380478346 ,
made the docstring more properly with adding more example and explanations.
=> Fixing & Adding example in docstring for DataFrame.query

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/internal.py
This PR fix `DataFrame.pivot` to support multi-index when using input's index
```python
pdf = pd.DataFrame({'a': [4, 2, 3, 4, 8, 6],
'b': [1, 2, 2, 4, 2, 4],
'e': [10, 20, 20, 40, 20, 40],
'c': [1, 2, 9, 4, 7, 4],
'd': [-1, -2, -3, -4, -5, -6]},
index=[10, 20, 30, 40, 50, 60])
kdf = ks.DataFrame(pdf)
kdf.columns = pd.MultiIndex.from_tuples([('x', 'a'), ('x', 'b'), ('y', 'e'), ('z', 'c'), ('w', 'd')])
kdf = kdf.set_index(('x', 'b'), append=True)
kdf.pivot(columns=('x', 'a'), values=('y', 'e'))
```
Before:
```
File "/.../koalas/databricks/koalas/frame.py", line 5451, in pivot
df.set_index("__DUMMY__", append=True, inplace=True)
File …
```
=> Fix DataFrame.pivot to support multi-index when using input's index

databricks/koalas/frame.py, docs/source/reference/frame.rst
Small follow up to rephrase the examples in `DataFrame.query`.
=> Rephrase the notes and examples in DataFrame.query

setup.py
According to https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py, we had better use `author` instead of `maintainer`.
=> Use `author` instead of `maintainer`.

databricks/koalas/frame.py
`DataFrame.pivot` without `index` argument should preserve the original index names.
```py
>>> pdf = pd.DataFrame({"foo": ['one', 'one', 'two', 'two'], "bar": ['A', 'A', 'B', 'C'], "baz": [1, 2, 3, 4]}, columns=['foo', 'bar', 'baz'])
>>> pdf.index.name = 'x'
>>> pdf
foo bar  baz
x
0  one   A    1
1  one   A    2
2  two   B    3
3  two   C    4
>>> pdf.pivot(columns='bar', values='baz')
bar    A    B    C
x
0    1.0  NaN  NaN
1    2.0  NaN  NaN
2    NaN  3.0  NaN
3    NaN  NaN  4.0
```
whereas:
```py
>>> ks.from_pandas(pdf).pivot(columns='bar', values='baz').sort_index()
bar    A    B    C
0    1.0  NaN  NaN
1    2.0  NaN  NaN
2    NaN  3.0  NaN
3    NaN  NaN  4.0
```
=> DataFrame.pivot without index argument should preserve the original index names.

databricks/koalas/indexing.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/utils.py
`DataFrame` (`DataFrame.loc`) should be able to handle a Series from index as well:
- before
```py
>>> kdf = ks.DataFrame({('x','a'):[1,2,3], ('y','b'):[4,5,6]})
>>> kser = kdf.index.to_series()
>>> kser
0    0
1    1
2    2
>>> kdf[[kser]]
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/frame.py", line 9306, in __getitem__
return self.loc[:, key]
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/indexing.py", line 286, in __getitem__
column_label_names=column_label_names,
File "/Users/ueshin/workspace/databricks-koalas/master/databricks/koalas/internal.py", line 523, in __init__
len(self._column_scols), …
```
=> Fix _LocIndexerLike to handle a Series from index.

README.md, docs/source/getting_started/index.rst, docs/source/getting_started/videos.rst
The "Koalas talks" page in the documentations is like:
=> Add links to the previous talks.

databricks/koalas/frame.py
We can simplify `pivot` for the case where the `index` argument is not specified.
=> Simplify pivot when the `index` argument is not specified.

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
We can support unstack with MultiIndex using pivot_table.
But as discussed at https://github.com/databricks/koalas/issues/886#issuecomment-585593019, we should still be careful to use it.
=> Support MultiIndex in DataFrame.unstack.

databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_series.py, databricks/koalas/typedef.py
This is related to #1323.
Adding support Spark UDT when converting from/to pandas DataFrame/Series.
=> Support Spark UDT when converting from/to pandas DataFrame/Series.

databricks/koalas/config.py
While i'm using the option `plotting.sample_ratio`.
I got a little bit confusion caused by improper exception message.
If i use `1.1` as a value for `plotting.sample_ratio`, it raises following exception.
```python
>>> with option_context("plotting.sample_ratio", 1.1):
...     kdf.plot.area()
...
ValueError: 'plotting.sample_ratio' should be 1 >= value >= 0.
```
it says 'plotting.sample_ratio' should be `1 >= value >= 0`.
So I used 1, it raises exception again.
```python
>>> with option_context("plotting.sample_ratio", 1):
...     kdf.plot.area()
...
ValueError: The value for option 'plotting.sample_ratio' was <class 'int'>; however, expected types are [(<class 'float'>, <class 'NoneType'>)].
```
Maybe it might not be …
=> [MINOR] Fix exception message for sample_ratio more properly

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
Adding `stack()` for `DataFrame`.
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html
Resolves #877.
=> Implement stack() for DataFrame.

databricks/koalas/base.py, databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/internal.py, databricks/koalas/ml.py, databricks/koalas/mlflow.py, databricks/koalas/namespace.py, databricks/koalas/plot.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, databricks/koalas/tests/test_internal.py, databricks/koalas/utils.py, databricks/koalas/window.py
This PR proposes to refine and refactor `_InternalFrame`.
- `index_map`: uses `OrderedDict` instead of `List[Tuple[...]]`
</br>
- `column_name_for` -> `spark_column_name_for`
Now, it purely searches by labels (and index name) instead of internal Spark column name when it searches index.
- `scol_for` -> `spark_column_for`
</br>
- `sdf` -> `spark_frame`
- `scol` -> `spark_column`
- `scols` -> `spark_columns`
- `columns ` -> `spark_column_names`
</br>
- `data_columns` -> `data_spark_column_names`
- `column_scols` -> `data_spark_columns`
</br>
- `index_columns` -> `index_spark_column_names`
- `index_scols` -> `index_spark_columns`
</br>
- `spark_internal_df` -> `to_internal_spark_frame`
- `spark_df` -> `to_external_spark_frame`
- `pandas_df` -> `to_pandas_frame`
=> Refine _InternalFrame by renaming and leveraging OrderedDict

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/tests/test_stats.py
Currently, Koalas' statics functions such as count, sum, min, max, etc. returns a pandas Series.
Resolves #1332
=> Return a Koalas series instead of pandas' in stats APIs at Koalas DataFrame

databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/series.py, databricks/koalas/tests/test_indexes.py, databricks/koalas/tests/test_indexing.py
As discussed at https://github.com/databricks/koalas/pull/1328#discussion_r388681347, we can consolidate the `Index.repeat()` and `MultiIndex.repeat()` by updating its anchor with a new scol.
Also resolves #1190 and other functions which were mistakenly using `index_scols` in `Index`, whose usage is valid now.
=> Fix Index._with_new_scol to update its anchor.

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py
Adding support slice as `rows_sel` for `iloc` indexer.
E.g.,
```py
>>> pdf = pd.DataFrame({'a':list('abcdefghij')})
>>> pdf
a
0  a
1  b
2  c
3  d
4  e
5  f
6  g
7  h
8  i
9  j
>>> pdf.iloc[2:5]
a
2  c
3  d
4  e
>>> pdf.iloc[2:-3]
a
2  c
3  d
4  e
5  f
6  g
>>> pdf.iloc[-8:-3]
a
2  c
3  d
4  e
5  f
6  g
>>> pdf.iloc[2:-3:2]
a
2  c
4  e
6  g
>>> pdf.iloc[5:]
a
5  f
6  g
7  h
8  i
9  j
>>> pdf.iloc[5:2]
Empty DataFrame
Columns: [a]
Index: []
```
Resolves #1230
=> Support slice as `rows_sel` for `iloc` indexer.

docs/source/reference/series.rst
i noticed pandas added it into documentation (https://pandas.pydata.org/pandas-docs/stable/reference/series.html#plotting). I am adding it accordingly in Koalas as well.
=> Add Series.plot.density into the documentation

databricks/koalas/generic.py, databricks/koalas/groupby.py, databricks/koalas/tests/test_ops_on_diff_frames_groupby.py, databricks/koalas/utils.py
This PR proposes to support the operations between series from different DataFrames in `groupby()`.
```python
ks.set_option('compute.ops_on_diff_frames', True)
kdf = ks.DataFrame({"a": [1, 2, 6, 4, 4, 6, 4, 7], "b": [4, 2, 7, 3, 3, 1, 1, 2]})
kdf.groupby(ks.Series([4, 2, 7, 3, 1, 1, 1, 2, 2])).sum()
```
The approach is similar with other implementations of `compute.ops_on_diff_frames`.
Before:
```
File "/.../koalas/databricks/koalas/generic.py", line 1437, in groupby
col_by = [_resolve_col(df, col_or_s) for col_or_s in by]
File "/.../koalas/databricks/koalas/generic.py", line 1437, in <listcomp>
col_by = [_resolve_col(df, col_or_s) for col_or_s in by]
File …
```
=> Add the support for operations between different DataFrames in groupby()

databricks/koalas/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_indexing.py
Looks pandas conditionally uses `iloc` approach when the input is `int` against index operators in Series and Frame.
```python
dates = pd.date_range('20130101', periods=6)
pdf = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
kdf = ks.from_pandas(pdf)
kdf[0:3]
```
```
A         B         C         D
2013-01-01  2.143975 -2.069608 -0.013988 -0.311598
2013-01-02 -0.448577  0.076479 -0.356269  0.965872
2013-01-03  0.203477  0.738288 -1.453629 -0.146019
```
Resolves #287
=> Fix index operator against Series and Frame to use iloc conditionally

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py
Adding support slice as `rows_sel` for `iloc` indexer.
E.g.,
```python
>>> pdf = pd.DataFrame({'a':list('abcdefghij'), 'b':list('abcdefghij')})
>>> pdf.iloc[[-1, 1, 2,3]]
a  b
9  j  j
1  b  b
2  c  c
3  d  d
>>> pdf.iloc[[-1, 1, 2,3], :]
a  b
9  j  j
1  b  b
2  c  c
3  d  d
>>> pdf.iloc[[-1, 1, 2,3], :1]
a
9  j
1  b
2  c
3  d
>>> pdf.iloc[[]]
Empty DataFrame
Columns: [a, b]
Index: []
```
Resolve #556
=> Support iterable as `rows_sel` for `iloc` indexer

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/tests/test_stats.py
Spark can't contain mixed types in its output. Statistic APIs in DataFrame outputs it. This PR explicitly disallow `numeric_only` or mention the limitation by it.
=> Explicitly don't support to disable numeric_only in stats APIs at DataFrame

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
This PR proposes `unique` for MultiIndex and integration with existing `Index.unique`
```python
>>> ks.MultiIndex.from_tuples([("A", "X"), ("A", "Y"), ("A", "X")]).unique()
MultiIndex([('A', 'X'),
('A', 'Y')],
)
```
=> Implements MultiIndex.unique()

databricks/koalas/indexes.py, databricks/koalas/indexing.py, databricks/koalas/tests/test_indexes.py, databricks/koalas/tests/test_indexing.py
Adding support MultiIndex for `loc` indexer with slice as `row_sel`.
E.g.,
```py
>>> pser
x  a    1
b    2
y  c    3
d    4
z  e    5
dtype: int64
>>> pser.loc['y':]
y  c    3
d    4
z  e    5
dtype: int64
>>> pser.loc[:'y']
x  a    1
b    2
y  c    3
d    4
dtype: int64
>>> pser.loc[('x','b'):]
x  b    2
y  c    3
d    4
z  e    5
dtype: int64
>>> pser.loc[:('y','c')]
x  a    1
b    2
y  c    3
dtype: int64
>>> pser.loc[('x','b'):('y','c')]
x  b    2
y  c    3
dtype: int64
>>> pser.loc['x':('y','c')]
x  a    1
b    2
y  c    3
dtype: int64
>>> pser.loc[('x','b'):'y']
x  b    2
y  c    3
d    4
dtype: int64
```
Resolves #1175, Closes #1182.
=> Support MultiIndex for `loc` indexer with slice as `row_sel`.

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py
Adding support slice as `col_sel` for `loc` indexer.
E.g.,
```py
>>> kdf
x     y     z
a  b  c  d  e
0  1  2  3  4  5
>>> kdf.loc[:, 'y':]
y     z
c  d  e
0  3  4  5
>>> kdf.loc[:, :'y']
x     y
a  b  c  d
0  1  2  3  4
>>> kdf.loc[:, ('x', 'b'):]
x  y     z
b  c  d  e
0  2  3  4  5
>>> kdf.loc[:, :('y', 'c')]
x     y
a  b  c
0  1  2  3
>>> kdf.loc[:, ('x', 'b'):('y', 'c')]
x  y
b  c
0  2  3
>>> kdf.loc[:, 'x':('y', 'c')]
x     y
a  b  c
0  1  2  3
>>> kdf.loc[:, ('x', 'b'):'y']
x  y
b  c  d
0  2  3  4
```
Resolves #1176, Closes #1188.
=> Support slice as `col_sel` for `loc` indexer.

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py
`MultiIndex.drop()` doesn't follow renaming et al which makes index spark column name and index name differ.
E.g.,
```py
>>> kidx = ks.MultiIndex.from_tuples(
...     [("a", "x"), ("b", "y"), ("c", "z")], names=["level1", "level2"]
... )
>>> kidx.names = ["lv1", "lv2"]
>>> kidx
MultiIndex([('a', 'x'),
('b', 'y'),
('c', 'z')],
names=['lv1', 'lv2'])
>>> kidx.drop(["x", "y"], level="lv2")
...
pyspark.sql.utils.AnalysisException: 'Cannot resolve column name "lv2" among (level1, level2, __natural_order__);'
```
=> Fix MultiIndex.drop() to follow renaming et al.

databricks/koalas/indexes.py, databricks/koalas/missing/indexes.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
This PR proposes `Index.union` & `MultiIndex.union`
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.union.html#pandas.Index.union)
- Index
```python
>>> idx1 = ks.Index([1, 2, 3, 4])
>>> idx2 = ks.Index([3, 4, 5, 6])
>>> idx1.union(idx2).sort_values()
Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')
```
- MultiIndex
```python
>>> midx1 = ks.MultiIndex.from_tuples([("x", "a"), ("x", "b"), ("x", "c"), ("x", "d")])
>>> midx2 = ks.MultiIndex.from_tuples([("x", "c"), ("x", "d"), ("x", "e"), ("x", "f")])
>>> midx1.union(midx2).sort_values()
MultiIndex([('x', 'a'),
('x', 'b'),
('x', 'c'),
('x', 'd'),
('x', 'e'),
('x', 'f')],
)
```
=> Implements union() for Index & MultiIndex

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
This PR proposes Implement of [DataFrame.take](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.take.html#pandas.DataFrame.take)
```python
>>> df = ks.DataFrame([('falcon', 'bird', 389.0),
...                    ('parrot', 'bird', 24.0),
...                    ('lion', 'mammal', 80.5),
...                    ('monkey', 'mammal', np.nan)],
...                   columns=['name', 'class', 'max_speed'],
...                   index=[0, 2, 3, 1])
>>> df
name   class  max_speed
0  falcon    bird      389.0
2  parrot    bird       24.0
3    lion  mammal       80.5
1  monkey  mammal        NaN
>>> df.take([0, 3])
name   class  max_speed
0  falcon    bird      389.0
1  monkey  mammal        NaN
>>> df.take([1, 2], axis=1)
class  max_speed
0    bird      389.0
2    bird …
```
=> Implement DataFrame.take

databricks/koalas/groupby.py, databricks/koalas/tests/test_groupby.py
This PR fixes `SeriesGroupBy.apply()` to work, and also to respect various output.
For example, pandas supports below:
**Series groupby:**
Function: series -> scalar
Return: a series
Function: series -> series
Return: a series
Function: series -> frame
Return: a frame
**DataFrame groupby:**
Function: frame -> scalar
Return: a series
Function: frame -> series
Return: a frame but the values of the series becomes columns.
Function: frame -> frame
Return: a frame
Resolves #1300
=> Fix GroupBy.apply() to respect various output

databricks/koalas/frame.py, databricks/koalas/namespace.py, databricks/koalas/tests/test_namespace.py
This PR proposes to add `axis` at `ks.concat(...)`.
```python
df1 = ks.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = ks.DataFrame([['bird', 'polly'], ['monkey', 'george']], columns=['animal', 'name'])
ks.concat([df1, df2], axis=1)
```
```
letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george
```
Resolves #625, Closes #1009.
=> Add column axis in ks.concat

databricks/koalas/base.py, databricks/koalas/indexes.py, databricks/koalas/indexing.py
This PR proposes to compute `is_monotonic`/`is_monotonic_decreasing` in a distributed manner.
The approach is:
1. Check if it's ordered within each partition
2. Calculate min/max from each partition and check if the min/max of partitions are ordered.
=> Compute Index.is_monotonic/Index.is_monotonic_decreasing in a distributed manner

databricks/koalas/indexes.py, databricks/koalas/missing/indexes.py, databricks/koalas/series.py, databricks/koalas/tests/test_indexes.py, docs/source/reference/indexing.rst
This PR proposes `Index.asof`
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.asof.html#pandas.Index.asof)
```python
>>> idx = ks.Index(['2013-12-31', '2014-01-02', '2014-01-03'])
>>> idx.asof('2014-01-01')
'2013-12-31'
>>> idx.asof('2014-01-02')
'2014-01-02'
>>> idx.asof('1999-01-02')
nan
```
=> Implements asof() for Index

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/series.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
This PR proposes `DataFrame.eval()`
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.eval.html#pandas.DataFrame.eval)
```python
>>> df = ks.DataFrame({'A': range(1, 6), 'B': range(10, 0, -2)})
>>> df
A   B
0  1  10
1  2   8
2  3   6
3  4   4
4  5   2
>>> df.eval('A + B')
0    11
1    10
2     9
3     8
4     7
```
Assignment is allowed though by default the original DataFrame is not
modified.
```python
>>> df.eval('C = A + B')
A   B   C
0  1  10  11
1  2   8  10
2  3   6   9
3  4   4   8
4  5   2   7
>>> df
A   B
0  1  10
1  2   8
2  3   6
3  4   4
4  5   2
```
Use ``inplace=True`` to modify the original DataFrame.
```python
>>> df.eval('C = A + B', inplace=True)
>>> df
A   B   C
0  1  10  11
1  2   8  10
2  3   6   9
3  4   4   8
4  5   2 …
```
=> Implements DataFrame.eval()

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Currently `DataFrame.duplicated` and `DataFrame.drop_duplicates` don't support `MultiIndex`.
We should support them.
e.g.,
```py
>>> pdf
a  b  c
0.660073  1  1  1
0.255808  1  1  1
0.796535  2  1  1
0.562986  3  4  5
>>> pdf.duplicated()
0.660073    False
0.255808     True
0.796535    False
0.562986    False
dtype: bool
>>> pdf.set_index("a", append=True).duplicated()
a
0.660073  1    False
0.255808  1     True
0.796535  2     True
0.562986  3    False
dtype: bool
```
or
```py
>>> pdf.drop_duplicates()
a  b  c
0.660073  1  1  1
0.796535  2  1  1
0.562986  3  4  5
>>> pdf.set_index("a", append=True).drop_duplicates()
b  c
a
0.660073 1  1  1
0.562986 3  4  5
```
=> Support MultiIndex for DataFrame.duplicated, drop_duplicates.

databricks/koalas/indexing.py, databricks/koalas/internal.py, databricks/koalas/tests/test_indexing.py
Fixing a bug in iloc for Series when the series is modified.
```py
>>> kser = ks.Series([1, 2, 3])
>>> (kser + 1).iloc[0]
...
pyspark.sql.utils.AnalysisException: 'Cannot resolve column name "`(0 + 1)`" among (__distributed_sequence_column__, __index_level_0__, 0);'
```
=> Fix iloc for Series when the series is modified.

.github/workflows/master.yml
This PR sets `GITHUB_OAUTH_KEY` as an environment variable so https://github.com/databricks/koalas/blob/master/dev/gendoc.py can generate documentation without hitting API call limit
=> Set Github token for documentation generation in Github Action

databricks/koalas/indexes.py, databricks/koalas/tests/test_indexes.py
Some refactoring is done for `Index.asof()`
=> Fix nan tests for Index.asof() and remove unnecessary code

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py
Support `__setitem__` for `loc`/`iloc` with Series.
e.g.,
```py
>>> kser = ks.Series([1, 2, 3], index=["cobra", "viper", "sidewinder"])
>>> kser
cobra         1
viper         2
sidewinder    3
>>> kser.loc[kser % 2 == 1] = -kser
>>> kser
cobra        -1
viper         2
sidewinder   -3
>>> kser.loc[["viper", "sidewinder"]] = 10
>>> kser
cobra         -1
viper         10
sidewinder    10
>>> kser.loc["viper"] = 50
>>> kser
cobra         -1
viper         50
sidewinder    10
>>> kser.loc[:] = 10
>>> kser
cobra         10
viper         10
sidewinder    10
>>> kser.loc[:"viper"] = 20
>>> kser
cobra         20
viper         20
sidewinder    10
>>> kser.loc["viper":] …
```
=> Add __setitem__ for loc/iloc with Series.

databricks/koalas/frame.py, databricks/koalas/namespace.py, databricks/koalas/tests/test_namespace.py, docs/source/reference/general_functions.rst
Manage broadcast hint for dataframes.
Provides `broadcast` function which, from a given koalas DataFrame, returns a new one with broadcast hint.
Broadcast join can now be performed in `DataFrame.join`, `DataFrame.merge` and `DataFrame.update.`
A broadcast join may be more efficient than sort merge join (Spark default) between a small dataframe and a big daframe. It gives every node a copy of a the small dataframe, which reduces the number of shuffle between partitions. By default, Spark performs it if a dataframe is smaller than ~10MB, but the user should be able to force it.
=> Manage broadcast hint for dataframes.

databricks/koalas/frame.py, databricks/koalas/missing/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
This PR proposes `DataFrame.markdown()` which is newly added in pandas > 1.0.0.
(https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html#pandas.DataFrame.to_markdown)
```
>>> kdf = ks.DataFrame(data={"animal_1": ["elk", "pig"], "animal_2": ["dog", "quetzal"]})
>>> print(kdf.to_markdown())
|    | animal_1   | animal_2   |
|---:|:-----------|:-----------|
|  0 | elk        | dog        |
|  1 | pig        | quetzal    |
```
=> Implements DataFrame.to_markdown

requirements-dev.txt
Seems we don't face the warnings from Sphinx (see https://github.com/databricks/koalas/pull/417). It seems fixed in the upstream Sphinx. This PR use the latest Sphinx in requirements-dev.txt
=> Use the latest Sphinx in requirements-dev.txt

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py, docs/source/reference/frame.rst
Resolves #1373 
Here, we have a `DataFrame` named `df`
```python
>>> import pyspark
>>> df = ks.DataFrame([(.2, .3), (.0, .6), (.6, .0), (.2, .1)],
...                   columns=['dogs', 'cats'])
>>> df
dogs  cats
0   0.2   0.3
1   0.0   0.6
2   0.6   0.0
3   0.2   0.1
```
Set the StorageLevel to `MEMORY_ONLY`.
```python
>>> with df.persist(pyspark.StorageLevel.MEMORY_ONLY) as cached_df:
...     print(cached_df.count())
...
dogs    4
cats    4
```
Set the StorageLevel to `DISK_ONLY`.
```python
>>> with df.persist(pyspark.StorageLevel.DISK_ONLY) as cached_df:
...     print(cached_df.count())
...
dogs    4
cats    4
```
If a StorageLevel is not given, it uses `MEMORY_AND_DISK` by default.
```python
>>> with df.persist() as cached_df:
... …
```
=> Implements DataFrame.persist() with additional tests for DataFrame.cache()

databricks/koalas/frame.py, databricks/koalas/generic.py, databricks/koalas/namespace.py
This PR adds a way to specify index column when reading and writing. For example,
```python
ks.range(1).to_parquet("/tmp/foo", index_col="index")
ks.read_parquet("/tmp/foo", index_col="index")
```
Resolves #1376
=> Add a way to specify index column in I/O APIs

databricks/koalas/frame.py, databricks/koalas/tests/test_dataframe.py
Now that we can specify the storage level via caching by `DataFrame.persist()` function.
We should also have `storage_level` property to show the current storage level.
=> Add storage_level property in _CachedDataFrame.

.github/workflows/master.yml
Github Actions fails fast by default. This PR targets to permissively run all tests.
=> Permissively run all tests in Github Actions

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py
Fixing a bug of `iloc.__setitem__` which throws an `AnalysisException` even when the value is the other Series from the same DataFrame.
```py
>>> kdf = ks.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
>>> kser = kdf.a
>>> kser.iloc[[1]] = -kdf.b
...
pyspark.sql.utils.AnalysisException: 'Resolved attribute(s) b#2L missing from __distributed_sequence_column__#44L,__index_level_0__#0L,a#1L,__natural_order__#48L in ...
```
=> Fix iloc.__setitem__ with the other Series from the same DataFrame.

.github/workflows/master.yml, .readthedocs.yml, docs/requirements-readthedocs.txt, requirements-dev.txt
This is a follow-up of #1387.
If there is a dependency which doesn't exist in conda in a requirements file, we can't use it for conda and it takes some steps for contributors to set up their development environment.
We should separate the requirements file for Read the Docs.
=> Separate a requirements file for Read the Docs.

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py, databricks/koalas/tests/test_ops_on_diff_frames.py, databricks/koalas/utils.py
E.g.,
```py
>>> kser = ks.Series([1, 2, 3], index=["cobra", "viper", "sidewinder"])
>>> kser.loc[["cobra", "viper"]] = ks.Series([4, 5], index=["cobra", "viper"])
>>> kser
cobra         4
viper         5
sidewinder    3
```
=> Add support Series from different DataFrames for `loc/iloc.__setitem__`.

.github/workflows/master.yml
As pandas 1.0.3 released, I think It would be better match the version of pandas in our CI.
=> Update the version of pandas up-to-date for CI

databricks/koalas/indexing.py, databricks/koalas/tests/test_indexing.py, databricks/koalas/tests/test_ops_on_diff_frames.py
Moving `__setitem__` for loc/iloc with DataFrame to use the similar logic as with Series.
=> Refine __setitem__ for loc/iloc with DataFrame.
