- databricks/koala/structures.py
- databricks/koala/tests/test_dataframe.py
> Add isnull(), notnull(), isna(), notna().

- databricks/koala/structures.py
- databricks/koala/tests/test_dataframe.py
The latest commit #71 seems to have broken the build, reverting for the time bing.
> Reverting latest commit

- databricks/koalas/missing/__init__.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- dev/_make_missing_functions.py
> Simplify stub code.

- README.md
> README update with contribution and development guide

- setup.py
Closes #101
It's here: https://pypi.org/project/koalas/
!!!
> PyPi package setup

- dev/_make_missing_functions.py
> Add instruction for _make_missing_functions

- README.md
> Add release instruction

- .travis.yml
The current `conda` in travis seems `4.6.14`, so `conda activate` should work.
> Use `conda activate` in travis.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
> Allow substraction resulting in timestamp

- databricks/koalas/frame.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/utils.py
This PR mainly address the comments in https://github.com/databricks/koalas/pull/134
> Add some documentation, todo, make databricks.koalas.utils

- README.md
- docs/index.rst
Added the introduction in the documentation. Also fixed some typos in README.
> Add introduction in Koalas documentation.

- README.md
- docs/source/quickstart.rst
> Use `import databricks.koalas as ks` style.

- .gitignore
- databricks/__init__.py
- databricks/koalas/dask/utils.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/test_series_datetime.py
- dev/lint-python
- requirements-dev.txt
This PR adds Mypy type hint linter in our tests and Python linter process.
Closes https://github.com/databricks/koalas/issues/162
> Add Mypy type hint linter in Koalas lint check

- databricks/koalas/metadata.py
> Add docs to metadata.

- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
This PR contains `values` property and `get_values()` method. 
The lazy evaluation tested in this issue #118
> add to_numpy()

- databricks/koalas/metadata.py
This is a follow up of #189 to add type annotations.
> Add type annotations to metadata.

- databricks/koalas/series.py
> Add docstring in Series.rename and Series.alias

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
This PR adds 'ascending' option to sort_values with doctest/docstring.
Resolves #132
Closes #53
> Add 'ascending', 'inplace', na_position` option to sort_values with doctest/docstring

- .travis.yml
- README.md
- dev/pytest
> Integrating Codecov with Koalas project

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe_conversion.py
- docs/source/reference/frame.rst
> DataFrame.to_string

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/typedef.py
- docs/source/reference/frame.rst
+ Only axis = 0 is supported in this method 
+ Dataframe and Series are not supported as value
> Add fillna

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/typedef.py
This PR propose to simplify fillna and the tests of fillna.
> Cleanup and simplify the logics of fillna

- databricks/conftest.py
- databricks/koalas/series.py
Hi @thunterdb Take a look at this PR, If it looks good then we work other function
> Inline docs for value_counts()

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/utils.py
This simplifies somewhat the calls to `GroupBy`.
Closes #225
> Cleanups to groupy

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/typedef.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
`isin()` method for series and dataframe.
> Add isin()

- databricks/koalas/namespace.py
This also gets us some free test cases.
> Inline docs for get_dummies

- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
as requested by @rxin, this PR refactor `test_dataframe.py` & `test_series.py`
> refactor test_dataframe & test_series

- databricks/koalas/CONTRIBUTING.md
Here is a WIP document about the scope and the vision of the Koalas project. This still lacks structures and examples, but it provides some guidance about where I believe the project should go. Feedback is welcome!
Resolves #119.
> [WIP] Design principles for Koalas

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/typedef.py
This PR cleans up isin and removes list type checker introduced together.
Let's do the type check one separately for other APIs too.
> Cleanup isin and remove list type check util for now

- databricks/koalas/exceptions.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/missing/__init__.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_series.py
- dev/_make_missing_properties.py
> Add stubs for missing properties.

- databricks/koalas/namespace.py
- docs/source/reference/io.rst
range is a super useful tool for testing. I always wanted it myself ... here you go.
> koalas.range

- databricks/koalas/frame.py
This PR has inline documentation for the `koalas.DataFrame.pipe` method.
Feedbacks are welcome :-)
> Inline doc for DataFrame.pipe

- databricks/koalas/generic.py
> Inline docs for all functions in generic.py

- databricks/koalas/frame.py
- databricks/koalas/series.py
- docs/Makefile
- docs/source/conf.py
> Treat warnings as errors in documentation build

- databricks/koalas/generic.py
This is a follow-up of #273 and #274.
> Fix flakiness.

- databricks/conftest.py
- databricks/koalas/frame.py
- databricks/koalas/series.py
This PR closes #236 to resolve conflicts and doc corrections.
> Inline doc for Series APIs

- databricks/koalas/frame.py
- databricks/koalas/series.py
This PR adds assertions for unused arguments at the constructors of DataFrame and Series on some conditions.
> Add assertions for constructor in both DataFrame and Series

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe_conversion.py
- docs/source/reference/frame.rst
Implementation of `to_csv()`. Part of #169
> DataFrame.to_csv

- databricks/koalas/frame.py
- databricks/koalas/namespace.py
Make the doc more consistent for a few functions.
> Various doc updates

- .travis.yml
See https://docs.travis-ci.com/user/languages/python/ as well for how to setup Python 3.7 in Travis.
> Test against Python 3.7 too in CI

- databricks/koalas/frame.py
The same logic looks at `validate_arguments_and_invoke_function`
> Remove duplicated codes at to_clipboard

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
> Add Series.is_unique property

- databricks/koalas/indexing.py
6 notes looks overwhelming ..
Before:
After:
> Reduce the number of notes in loc

- .travis.yml
This PR makes conda environment in travis-ci pin Python version to avoid upgrading unexpectedly.
> Pin Python version.

- MANIFEST.in
- README.md
- docs/source/index.rst
- setup.py
This PR added `MANIFEST.in` to include `LICENSE` file in the package and refine `setup.py`, also updated documents.
> Refine the package management and documents.

- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Seems like just an alias of length. It counts nulls too.
> Add DataFrame.size and Series.size

- databricks/koalas/indexing.py
#364 and #341 cause breaking build due to implementation conflict.
This PR fixes it.
> Fix iloc tests.

- databricks/koalas/base.py
This is a follow-up of #368 to fix type-hints.
> Fix type-hints for all/any.

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/missing/series.py
- docs/source/reference/frame.rst
- docs/source/reference/indexing.rst
- docs/source/reference/series.rst
This PR adds `empty` property in DataFrame, Series, Index
> Add DataFrame, Series, Index.empty

- codecov.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://codecov.io/gh/gliptak/koalas/list/0e186fdd889dc50f1368fa8faf4ea1143d4c0a16/
> Correct code coverage exclude

- databricks/koalas/__init__.py
> Fix `_auto_patch` to respect the env variable.

- databricks/koalas/series.py
- databricks/koalas/strings.py
- databricks/koalas/tests/test_series_string.py
- databricks/koalas/typedef.py
- docs/source/reference/series.rst
As discussed in #281, this PR creates Series.str functions for manipulating strings in Koalas Series.
> Koalas Series.str functions

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/namespace.py
- docs/source/reference/io.rst
Link the read and write methods with each other.
> Cross link top level I/O methods

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_conversion.py
- databricks/koalas/tests/test_dataframe_spark_io.py
- docs/source/reference/frame.rst
- docs/source/reference/io.rst
Resolves #442.
I also moved Parquet section in I/O higher.
> DataFrame.to_parquet

- databricks/koalas/frame.py
- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
- docs/source/reference/frame.rst
- docs/source/reference/io.rst
> ks.read_table / DataFrame.to_table

- .gitignore
- databricks/conftest.py
- databricks/koalas/frame.py
- databricks/koalas/namespace.py
- databricks/koalas/utils.py
- dev/pytest
- docs/source/reference/frame.rst
- docs/source/reference/io.rst
This PR takes over #452 so that they can be tested in doctests and unittests.
Closes #452
Resolves #444
> ks.read_delta / DataFrame.to_delta

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
This PR adds DataFrame.drop_duplicates.
> Add DataFrame.drop_duplicates

- docs/source/reference/series.rst
> Fix typo in the doc str -> plot

- databricks/koalas/frame.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
This is a follow-up of #466 and some doc fixes.
> Update a docstring and add missing APIs.

- databricks/koalas/frame.py
This is a follow-up of #381.
We should use `self` for the first argument to instance methods.
> Fix a merge function argument name to use `self` instead of `left`.

- databricks/koalas/__init__.py
- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/namespace.py
- dev/pytest
- docs/source/reference/frame.rst
- docs/source/reference/general_functions.rst
This PR proposes to add:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.melt.html?highlight=melt#pandas.DataFrame.melt
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.melt.html?highlight=melt#pandas.melt
> Add DataFrame.melt and koalas.melt

- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
This PR adds get_dtype_counts in DataFrame and Series
> Add get_dtype_counts in DataFrame and Series

- databricks/koalas/groupby.py
- docs/source/reference/groupby.rst
"See Also" links from `groupby.py` are broken.
> Fix links from groupby.py.

- databricks/koalas/datetimes.py
- databricks/koalas/tests/test_series_datetime.py
- docs/source/reference/series.rst
Implement the remaining dt methods per issue #282
> Implement the remaining dt methods

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
> DataFrame.update()

- databricks/koalas/plot.py
> Clean up plot - add license, inline the documentation, cleanup imports

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
This PR adds DataFrame.T and DataFrame.transpose.
This will be an expensive operation ... but still work.
Resolves #467
> Add DataFrame.T and DataFrame.transpose

- databricks/koalas/missing/common.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/missing/series.py
This PR adds a reason why memory_usage is unimplemented
> Add a reason why memory_usage is unimplemented

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- docs/source/reference/series.rst
This PR adds Series.rank - https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rank.html?highlight=rank#pandas.Series.rank
> Add Series.rank

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- docs/source/reference/frame.rst
This PR adds `DataFrame.select_dtypes`
> Add DataFrame.select_dtypes

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
> DataFrame.replace

- databricks/koalas/frame.py
This is a follow-up of #495 to address comments.
> Follow-up of the replace PR.

- databricks/koalas/series.py
Add a note in rank that all data will be moved into single node
> Add a note in rank that all data will be moved into single node

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
This PR takes over #500 #501, #504.
> Add DataFrame.cummin(), cummax() and cumsum()

- databricks/koalas/frame.py
> Add columns.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
> Fix typos in error messages

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
This PR adds `DataFrame.reindex`. 
Resolves #421
> Add reindex in DataFrame

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/typedef.py
- docs/source/reference/frame.rst
This PR adds transform API in DataFrame.
> Add DataFrame.transform()

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/series.rst
> Add Series.median()

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- docs/source/reference/series.rst
This PR adds Series.T and Series.transpose
> Add Series.T and Series.transpose

- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/series.py
- docs/source/reference/frame.rst
This PR adds DataFrame.median().
> Add DataFrame.median

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
This PR adds Series.cumprod and DataFrame.cumprod
> Add Series.cumprod and DataFrame.cumprod

- databricks/koalas/base.py
- databricks/koalas/missing/series.py
- docs/source/reference/series.rst
This PR adds hasnans in Series and Index
> Add hasnans in Series and Index

- databricks/koalas/namespace.py
- docs/source/reference/general_functions.rst
This PR adds isna, isnull, notna, notnull
> Add isna, isnull, notna, notnull

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
I am going to merge this commit by his name.
>  Add DataFrame.shift()

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
This PR adds Series.quantile().
> Add Series.quantile()

- databricks/koalas/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- docs/source/reference/series.rst
> Add Series.diff()

- databricks/koalas/series.py
This PR matches the output with pd.Series.quantile output:
```python
>>> pd.Series([1., 2., 3., 4., 5.]).quantile([.25, .5, .75])
0.25    2.0
0.50    3.0
0.75    4.0
dtype: float64
```
```python
>>> ks.Series([1., 2., 3., 4., 5.]).quantile([.25, .5, .75])
0.25    2.0
0.50    3.0
0.75    4.0
```
> Remove index name from Series.quantile output

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
> add method and limit parameter for DataFrame.fillna()

- databricks/koalas/frame.py
We need `column=[...]` in doctests for Python 3.5.
> Add `columns=[...]`.

- .travis.yml
- requirements-dev.txt
- setup.py
Pandas 0.25 was released (https://pypi.org/project/pandas/).
We tried to test with pandas 0.25, but there are failures: https://travis-ci.com/databricks/koalas/jobs/217695045.
> Set the upper-bound of pandas version.

- .travis.yml
- databricks/koalas/plot.py
- requirements-dev.txt
- setup.py
This PR adds pandas 0.25 support.
We should reduce the usage of private properties ... 
Resolves #578
> Add pandas 0.25 support

- databricks/koalas/generic.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/missing/series.py
This PR proposes to add more deprecations found in release notes at https://pandas.pydata.org/pandas-docs/stable/whatsnew/index.html#version-0-25
> Add more deprecation APIs

- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- docs/source/reference/groupby.rst
This PR adds `GroupBy.apply` by using grouped map pandas UDF.
Resolves #409
> Add GroupBy.apply()

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- docs/source/reference/groupby.rst
This PR adds `GroupBy.transform` by using grouped map pandas UDF.
> Add GroupBy.transform()

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
This PR adds DataFrame.filter()
> Add DataFrame.filter()

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Adding support `col_level` and `col_fill` arguments for `DataFrame.reset_index()` method as well as fixing the method with multi-level columns.
Resolves #301.
> Fix reset_index with multi-level columns.

- databricks/koalas/tests/test_stats.py
I might miss the context, but the tests for stats seem strange?
They should be as this PR?
> Fix tests for stats.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
> Fix merge for how='right' or how='outer'.

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
> Add multiple aggregations on a single column

- databricks/koalas/indexing.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_indexing.py
> Fix multi-index column access with indexers.

- databricks/koalas/groupby.py
This PR adds transform and apply in SeriesGroupBy by reusing the ones in DataFrameGroupBy
> Add transform and apply in SeriesGroupBy

- databricks/koalas/groupby.py
- databricks/koalas/missing/groupby.py
- databricks/koalas/tests/test_groupby.py
- docs/source/reference/groupby.rst
Add groupby.size function by F.count
> Add groupby.size 

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
This PR adds size property in Index.
> Add size in Index

- databricks/koalas/frame.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_groupby.py
create a new PR base on https://github.com/databricks/koalas/pull/576
> fillna function rewrite

- databricks/koalas/frame.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_dataframe.py
> Support names of index levels

- databricks/koalas/frame.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_dataframe.py
Fix an issue on the comment https://github.com/databricks/koalas/pull/621#pullrequestreview-271639317.
> Fix column access with named column index.

- databricks/koalas/plot.py
- databricks/koalas/tests/test_frame_plot.py
- docs/source/reference/frame.rst
> ENH: Add bar plot for DataFrame

- databricks/koalas/plot.py
area plot still works and tests all pass locally, @HyukjinKwon thanks for pointing it out!!
> CLN: Cleaner Series col name assignment in SampledPlot

- databricks/koalas/plot.py
- databricks/koalas/tests/test_frame_plot.py
- docs/source/reference/frame.rst
working correctly with y specified: 
working correctly without y:
same error message that pandas has if y is None and subplots is not True:
> ENH: Implement pie plot for Frame

- databricks/koalas/config.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/utils.py
related with #724  i added compute.ops_on_diff_frames
> Add configuration value: compute.ops_on_diff_frames

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- docs/source/reference/frame.rst
This PR implements by simply using top n. It anyway needs to collects into driver side to show the table pretty.
Resolves #708
> Add DataFrame.style property

- databricks/koalas/sql.py
As you can see in the following screenshot,
There were some missing sql test using Series, so I added it to Doc test.
could someone check this change maybe if available?
Thanks.
> Add missing tests for sql

- databricks/koalas/__init__.py
- databricks/koalas/namespace.py
- docs/source/reference/io.rst
> Add read_sql_table, read_sql_query, and read_sql.

- requirements-dev.txt
- setup.py
As a result of #746, update the lower version of pandas to 0.23.2.
Closes #746.
> Update the lower version of pandas.

- databricks/koalas/namespace.py
Found the doc test of 'notna' is not tested properly like below.
Fixed some mistakes in how to execute the function so that it is properly tested.
And add doctest for when object not DataFrame or Series.
could someone check this out when available?
Thanks :)
> Fix some untested doctest for namespace

- databricks/koalas/missing/series.py
As discussed in issue #702 ,
not to explicitly use nbytes from the Series.
> Explicitly don't support nbytes in Series

- databricks/koalas/plot.py
feel like `to_frame` is a bit redundant, remove it should also work.
> CLN: Simplify TopN plot

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/namespace.py
- databricks/koalas/plot.py
- databricks/koalas/strings.py
- databricks/koalas/utils.py
Fix typos from all main & test source codes in `databricks/koalas` and `databricks/koalas/tests`
(but no typos found in `tests`)
> [MINOR] Fix all typos in whole main & test source codes

- databricks/koalas/plot.py
- databricks/koalas/tests/test_series_plot.py
This PR make current plot implement consistent, and remove `KoalasBoxPlotSummary` for now. Seems like the generalization can be done differently later. Currently seems a bit overkill to me.
Mainly this PR moves codes just to be consistent.
> Refactor and move KoalasBoxPlot to be consistent in plot implementations.

- docs/source/index.rst
- docs/source/themes/nature_with_gtoc/layout.html
- docs/source/themes/nature_with_gtoc/static/nature.css_t
> Put the logo on the docs page.

- dev/gendoc.py
This PR proposes to retry downloading pandoc and related requests.
Manually tested by using weird version and switching on and off wifi.
> Retry downloading pandoc and related requests

- databricks/koalas/usage_logging/__init__.py
> Add Expanding and Rolling to usage logging.

- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
The current implementations skip handling `_scol`.
> Fix Series.nsmallest and nlargest.

- dev/gendoc.py
This PR retries to call Github API as well.
> Retry Github API call as well in documentation generation

- README.md
> Edit some wordings in README.md and change logo's location

- databricks/koalas/plot.py
> [MINOR] Remove unnecessary backticks in plot.py

- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
> ENH: Implement Series.drop_duplicates

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_csv.py
> Add more options to `read_csv`.

- docs/source/user_guide/index.rst
- docs/source/user_guide/options.rst
- docs/source/user_guide/pandas_pyspark.rst
> Add an API compatibility guide for pandas and PySpark users

- .travis.yml
Add a space to adjust indent in `.travis.yml`.
> [MINOR] Adjust indent in .travis.yml

- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/utils.py
This fixes the bug at https://github.com/databricks/koalas/pull/923#discussion_r334500746.
> Fix `utils.combine_frames` for Series with different level of indexes.

- CONTRIBUTING.md
- databricks/koalas/indexing.py
> [MINOR] fix typo & remove unused import

- README.md
Databricks Runtime Instruction should better be in Getting Started
> Move FAQ to Getting Started

- databricks/koalas/series.py
> Fix to use `_internal` instead of `_kdf`.

- databricks/koalas/tests/test_series.py
Fix typos created by this PR https://github.com/databricks/koalas/commit/b7f1fe0d2499699f0866031301f2d40ef8f6c49c#diff-10c60606750ccfb376a0419542432a58L492
> Fix a typo in SeriesTest

- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/utils.py
The `combine_frames` didn't handle the case where the right hand side arguments are modified Series.
Resolves #1013.
> Fix combine_frames to handle where the right hand side arguments are modified Series

- databricks/koalas/window.py
> Keeps column index in groupby.expanding()

- databricks/koalas/window.py
- Avoid to use `lag` which refers the value in the offset. `min_periods` refers the number of values.
- Use `row_number` instead to count the number of values properly as many as `min_periods`.
- Match the documentation with `Expanding`
- Fix ordering of defined APIs to match with `Expanding`.
> Clean up and handle min_periods properly in rolling of Series and Frame

- databricks/koalas/window.py
This PR proposes to deduplicate the method implementation at `Expanding` and `Rolling` to `_RollingAndExpanding`.
Now, windowing logics of `Expanding`, `ExpandingGroupBy`,  `Rolling` and `RollingGroupBy` are all located in `_RollingAndExpanding`.
> Deduplicate Expanding and Rolling codes at _RollingAndExpanding

- databricks/koalas/series.py
> Remove 'in sorted order' in the doc of Series.mode

- databricks/koalas/series.py
Reverts databricks/koalas#1065
> Revert "Fix Series.idxmax() & idxmin() to make result properly"

- README.md
Include link to Help Thirsty Koalas Fund
> Include link to Help Thirsty Koalas Fund

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
- docs/source/reference/indexing.rst
I'm back to Koalas. This is my first commit in `Index.py`. Keep Going Koalas!
> Implement Index.shape & MultiIndex.shape 

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/test_indexes.py
- docs/source/reference/indexing.rst
Get MultiIndex unique value count in every level.
> Implement MultiIndex.levshape

- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_indexing.py
This PR is one of refactorings for `indexing`
> Refine iloc.

- databricks/koalas/indexing.py
This PR is one of refactorings for `indexing`.
> Refine loc.

- databricks/koalas/indexing.py
> Introduce _IndexerLike.

- databricks/koalas/numpy_compat.py
- databricks/koalas/tests/test_numpy_compat.py
This PR proposes to support 'ops_on_diff_frames' option for NumPy ufunc compat in Series
```python
>>> a = ks.range(10).id
>>> b = ks.range(10, 20).id
>>> ks.set_option('compute.ops_on_diff_frames', True)
>>> np.arctan2(a, b)
0    0.000000
1    0.090660
2    0.165149
3    0.226799
4    0.278300
5    0.321751
6    0.358771
7    0.390607
8    0.418224
9    0.442374
Name: id, dtype: float64
```
> Support 'compute.ops_on_diff_frames' for NumPy ufunc compat in Series

- databricks/koalas/base.py
- databricks/koalas/indexes.py
- databricks/koalas/tests/test_series.py
This PR address the comment at https://github.com/databricks/koalas/pull/1116#discussion_r358984275
> Move value_counts for struct into only multi-index's

- databricks/koalas/indexing.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_series.py
> Add support scalar values as row_sel for `loc` indexer.

- databricks/koalas/base.py
- databricks/koalas/indexing.py
Addressing https://github.com/databricks/koalas/pull/1159#discussion_r364100375.
> Reduce the number of Spark jobs.

- databricks/koalas/frame.py
> Clearify the series within DataFrame.transform are seguments of the whole Koalas series

- databricks/koalas/internal.py
It removes the (outdated) documentations for private variables. Instead, it adds some examples against the constructor. So we don't forget to update the doctests as well.
> Add some examples to describe private vars via __init__ in DataFrame

- databricks/koalas/internal.py
Improve 'distributed-sequence' default index by using Scalar Pandas UDF to handle only offset for each partition instead of the whole data in the partition with Grouped Map Pandas UDF.
As a side effect, we can prune the index column if we don't need it:
- before
```py
>>> ks.options.compute.default_index_type = 'distributed-sequence'
>>> ks.range(100).explain()
*(3) Project [__index_level_0__#23L, id#24L]
+- FlatMapGroupsInPandas [__spark_partition_id#15], default_index(id#0L, __natural_order__#2L, __spark_partition_id#15), [__index_level_0__#23L, id#24L, __natural_order__#25L]
+- *(2) Sort [__spark_partition_id#15 ASC NULLS FIRST], false, 0
+- Exchange hashpartitioning(__spark_partition_id#15, 200)
+- *(1) Project …
```
> Improve 'distributed-sequence' default index.

- databricks/koalas/frame.py
- databricks/koalas/internal.py
Added `with_new_columns` and `with_filter` utilities to `_InternalFrame` and changed the usage in `DataFrame`. We can replace with the methods in other places but I'd leave it to the following PRs.
> Add utility methods to `_InternalFrame`.

- databricks/koalas/groupby.py
- databricks/koalas/internal.py
- databricks/koalas/series.py
- databricks/koalas/window.py
This is a follow-up of #1199 to apply the utilities in other places.
> Apply the utilities to other places.

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
This PR is a followup of #1105. Addressed left comments.
> Add negative test cases and error handling at MultiIndex.swaplevel

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_groupby.py
following up #1202 
- add more test cases
- raise proper message for string type
> Add more test cases and improve error message in DataFrameGroupBy.describe

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
We should use a new `_InternalFrame` when we rename the index.
Resolves #1210, Closes #1206 Closes #1207
> Fix `Index.rename`.

- databricks/koalas/tests/test_groupby.py
A small followup of https://github.com/databricks/koalas/pull/1224 and https://github.com/databricks/koalas/pull/1229
Now, we can cover this case
> Add a test case when series.groupby series references the same column but with different values

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
Introduce `_apply_series_op` util function to consolidate the same pattern of code to call corresponding Series functions.
> Introduce `_apply_series_op` util function for DataFrame.

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/series.py
- databricks/koalas/window.py
Add `_apply_series_op` to Series as well to be able to use it in `_Frame`.
> Add `_apply_series_op` to Series as well.

- databricks/koalas/groupby.py
This is a follow-up of #1237 and #1242 to apply the similar way to `GroupBy`.
> Apply the similar `_apply_series_op` to GroupBy.

- databricks/koalas/frame.py
We can apply `_InternalFrame.with_new_columns` util function in `DataFrame._assign` as well.
> Apply util function to `DataFrame._assign`.

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/ml.py
- databricks/koalas/mlflow.py
- databricks/koalas/namespace.py
- databricks/koalas/plot.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_internal.py
- databricks/koalas/utils.py
- databricks/koalas/window.py
As per the discussion at https://github.com/databricks/koalas/pull/1258#discussion_r376759915, renaming `column_index` to `column_labels`.
> Rename column_index to column_labels.

- databricks/koalas/frame.py
When `DataFrame.where`, there were so many joins in its plan and it depends on the number of columns. E.g.,:
```py
>>> df1 = ks.DataFrame({'A': [0, 1, 2, 3, 4], 'B':[100, 200, 300, 400, 500]})
>>> df1.where(df1 > 0).explain()
*(8) Project [__index_level_0__#704L, CASE WHEN __tmp_cond_col_A__#808 THEN cast(A#1L as double) ELSE NaN END AS A#1002, CASE WHEN B#674 THEN cast(B#2L as double) ELSE NaN END AS B#1003]
+- SortMergeJoin [__index_level_0__#704L], [__index_level_0__#0L], LeftOuter
:- *(5) Sort [__index_level_0__#704L ASC NULLS FIRST], false, 0
:  +- Exchange hashpartitioning(__index_level_0__#704L, 200)
:     +- *(4) Project [__index_level_0__#0L AS __index_level_0__#704L, A#1L, B#2L, A#673 AS __tmp_cond_col_A__#808]
:        +- SortMergeJoin …
```
> Fix where to reduce the number of joins.

- .gitignore
The coverage file name was changed to `coverage.xml` at #1266.
> Add coverage.xml to .gitignore.

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/plot.py
- databricks/koalas/series.py
Added `with_new_sdf` utility to `_InternalFrame`.
> Add another utility method to `_InternalFrame`.

- databricks/koalas/internal.py
- docs/source/development/design.rst
- docs/source/user_guide/faq.rst
So far we don't support Structured Streaming.
We should explicitly add a doc and throw a better exception for now. (related to #1297)
> Add an faq about Structured Streaming.

- databricks/koalas/frame.py
The approach is basically similar with `DataFrame._reduce_for_stat_function`.
> Make nunique in DataFrame to return a Koalas DataFrame instead of pandas'

- .github/workflows/master.yml
Remove an unnecessary duplicate in our `master.yml`.
> [MINOR] Remove unnecessary line from master.yml (GitHub Actions)

- dev/gendoc.py
This PR proposes to reuse previously downloaded pandoc; do not download if pandoc is found in the path. 
This targets to reduce the build time taken in the readthedocs. Currently, the documentation build in Read the Docs is being failed due to timeout.
> Reuse previously downloaded pandoc; do not download if pandoc is found in the path

- README.md
- docs/source/getting_started/videos.rst
This PR adds some more Koalas talks.
> Add some more Koalas talks

- databricks/koalas/indexes.py
- databricks/koalas/namespace.py
- databricks/koalas/numpy_compat.py
- databricks/koalas/window.py
Clean up some unused imports in main & tests.
> [MINOR] Clean up some unused imports

- .github/workflows/master.yml
> Fix the conda download url.

- README.md
- docs/source/getting_started/index.rst
- docs/source/getting_started/videos_blogs.rst
This PR adds some blog posts in Koalas documentation.
> Add blog posts in Koalas documentation

- databricks/koalas/frame.py
- databricks/koalas/namespace.py
Adding `hint` function in DataFrame, which is adding a various types of hint, similar to `ks.broadcast()` but not only broadcast hint.
> Add hint function in DataFrame.

- databricks/koalas/frame.py
- databricks/koalas/series.py
- docs/source/reference/series.rst
Refine mutual links for `aggregate`, `apply`, and `transform`, and links to the each equivalent function between `DataFrame` and `Series`.
> Add links to each other in the doc.

- databricks/koalas/frame.py
Spark 3.0 supports `mode` parameter for `explain()` to show various types of explains.
This PR adds the `mode` parameter to `explain()` to follow Spark 3.0, but with a restriction for `Spark<3.0` that it only supports `"simple"` and `"extended"`.
```py
>>> df.explain(mode="extended")
== Parsed Logical Plan ==
...
== Analyzed Logical Plan ==
...
== Optimized Logical Plan ==
...
...
```
> Add mode parameter to DataFrame.explain.

- databricks/koalas/frame.py
This PR proposes to use `mapInPandas` in Spark 3.0.
> Use mapInPandas for apply_batch API in Spark 3.0

- docs/source/user_guide/index.rst
- docs/source/user_guide/transform_apply.rst
> Add user guide for transform and apply in documentation

- databricks/koalas/plot.py
Raise ValueError that is not raised now.
> Raise ValueError that is not raised now

- databricks/koalas/groupby.py
Use `verify_temp_column_name` for a temporary column name.
> Use verify_temp_column_name.

- databricks/koalas/groupby.py
`GroupBy.nunique` should not update the internal state.
> Fix GroupBy.nunique not to update the internal state.

- databricks/koalas/tests/test_series.py
Adding missing test for Series.to_frame() with parameter `name`
> Add test for Series.to_frame() with  parameter

- databricks/koalas/tests/test_series.py
Adding missing test for Series.shape
> Add test for Series.shape

- databricks/koalas/groupby.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
Now we can remove the previous workaround.
> Cleanup a previous workaround.

- databricks/koalas/series.py
Adding a missing test for using the ``np.ufunc`` parameter of ``Series.transfor_batch``.
> Add doctest for Series.transform_batch with np.ufunc parameter

- databricks/koalas/frame.py
> [MINOR] Fix typos in frame.py

- databricks/koalas/frame.py
Adding missing doctest and test cases in frame.py
>  Added missing doctest and test cases in frame.py

- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/indexing.py
- databricks/koalas/series.py
- databricks/koalas/utils.py
Adding `same_anchor` util to check if the anchors of the given DataFrame or Series are the same or not.
> Add same_anchor util.

- databricks/koalas/tests/test_dataframe.py
This is a follow-up of #1538 to add some tests.
> Add some tests in test_explode.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
Implementing multi-index support in `DataFrame.filter`
> Implements multi-index support in Dataframe.filter

- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_series.py
Addressing a comment https://github.com/databricks/koalas/pull/1511#issuecomment-635553162.
> Move filter function back to DataFrame and add it to Series.

- .github/workflows/master.yml
- dev/lint-python
- docs/requirements-readthedocs.txt
- docs/source/development/contributing.rst
- requirements-dev.txt
pydata_sphinx_theme is now available on PyPi and conda:
- https://pypi.org/project/pydata-sphinx-theme/
- https://anaconda.org/conda-forge/pydata-sphinx-theme
> Use official pydata_sphinx_theme releases

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/tests/test_dataframe.py
- docs/source/reference/frame.rst
Implement `DataFrame.mad`
- Basic Examples
```python
>>> df = ks.DataFrame({'a': [1, 2, 3, np.nan], 'b': [0.1, 0.2, 0.3, np.nan]}, columns=['a', 'b'])
>>> df.mad()
a    0.666667
b    0.066667
>>> df.mad(axis=1)
0    0.45
1    0.90
2    1.35
3     NaN
```
> Implement DataFrame.mad

- databricks/koalas/frame.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/window.py
It's fine to apply filter after select, but move filter before select to make sure it works.
> Make filters apply first.

- databricks/koalas/frame.py
Resolves https://github.com/databricks/koalas/issues/1516
> Remove subset parameter in DataFrame.replace

- .github/workflows/master.yml
- README.md
- databricks/koalas/plot.py
- docs/source/getting_started/install.rst
- docs/source/user_guide/transform_apply.rst
Several typos have been found and fixed.
> [MINOR] Fix typos

- databricks/koalas/indexes.py
This is a follow-up of #1564 which was missing the fix for `Index`.
> Fix index.__repr__ to use cached pandas Index and reuse between Index and MultiIndex.

- README.md
- docs/source/development/contributing.rst
This PR proposes to avoid recommending one specific package manager. Each has its own benefits and disadvantages.
> Avoid recommending Conda

- README.md
> Fix installation step to make it more neutral

- docs/source/conf.py
Read the Docs build is about to reach the time limit. This PR proposes to reuses the generated rst files in Read the Docs build to speed up.
> Let Read the Docs build reuse generated rst files

- databricks/koalas/tests/test_utils.py
- dev/pytest
The test `databricks/koalas/tests/test_dataframe_conversion.py::DataFrameConversionTest::test_to_clipboard` came to fail for some reason.
I think we can just disable it.
> Disable to_clipboard tests.

- docs/source/development/contributing.rst
- docs/source/development/design.rst
This PR proposes to update contribution guide and release cycle.
> Update contribution guide about Koalas release cycle

- databricks/koalas/series.py
> [MINOR] typo in Series.unique()

- .github/workflows/master.yml
Github Actions has its own miniconda already installed. This PR uses it and clean up.
> Use Github Actions' builtin miniconda

- docs/source/user_guide/best_practices.rst
> Add document for case sensitivity

- .github/workflows/master.yml
- requirements-dev.txt
Fixes build failures:
- set the upper bound for matplotlib as same as pandas
- avoid using pyarrow 0.13.0
> Fix build failures.

- databricks/koalas/extensions.py
Fixes extension documents since the examples for each extension decorator don't work as-is.
> Fix extension documents.

- databricks/koalas/namespace.py
- databricks/koalas/tests/test_dataframe_spark_io.py
Enables to read multiple sheets from multiple Excel files.
> Add support multiple sheets in multiple files for read_excel.

- databricks/koalas/tests/test_default_index.py
> Remove unneeded mix-in.

- .github/workflows/master.yml
- databricks/conftest.py
- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/sql.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_namespace.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_stats.py
Use `checkpoint` for `distributed-sequence`.
> Use checkpoint for distributed-sequence.

- README.md
Now we can easily check the download stats via "downloads" badge provided by [PePy](https://pepy.tech/project/Koalas).
How does it look ?
> Suggestion to add downloads badge

- databricks/koalas/generic.py
Adding the abstract `Frame.fillna` to clarify there are the methods in the sub classes.
> Add the abstract method for Frame.fillna.

- databricks/koalas/groupby.py
Fixing index name when groupby.apply returns a single row.
```py
>>> kdf = ks.DataFrame({'A': 'a a b'.split(), 'B': [1, 2, 3], 'C': [4, 6, 5]})
>>> kdf.groupby('A').apply(sum).sort_index()
A  B   C
__groupkey_0__
a               aa  3  10
b                b  3   5
```
```py
>>> pdf.groupby('A').apply(sum).sort_index()
A  B   C
A
a  aa  3  10
b   b  3   5
```
> Fix index name when groupby.apply returns a single row.

- databricks/koalas/frame.py
> Fix docstring for some cases doesn't preserve the order

- .github/workflows/master.yml
- databricks/conftest.py
- databricks/koalas/accessors.py
- databricks/koalas/frame.py
- databricks/koalas/indexes.py
- databricks/koalas/indexing.py
- databricks/koalas/internal.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/spark/accessors.py
- databricks/koalas/sql.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_default_index.py
- databricks/koalas/tests/test_groupby.py
- databricks/koalas/tests/test_indexes.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/tests/test_namespace.py
- databricks/koalas/tests/test_ops_on_diff_frames_groupby.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/tests/test_stats.py
Use `RDD.zipWithIndex` for `distributed-sequence`.
> Use RDD.zipWithIndex for distributed-sequence.

- databricks/koalas/tests/test_dataframe.py
`DataFrame.droplevel` has not been testing in pandas < 0.24.
Added expected result manually to cover the case.
> Add test for DataFrame.droplevel in pandas < 0.24

- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
Cleanup tests for `DataFrame.tail` and `Series.tail`
> [MINOR] Cleanup test for DataFrame.tail and Series.tail

- docs/source/development/contributing.rst
- docs/source/user_guide/pandas_pyspark.rst
- docs/source/user_guide/transform_apply.rst
Found & fixed several typos in the whole documents.
> [TRIVIAL] Fix typo in documents

- databricks/koalas/indexes.py
- databricks/koalas/missing/indexes.py
- databricks/koalas/tests/test_indexes.py
- docs/source/reference/indexing.rst
This PR proposes view for `Index` and `MiltiIndex`
This is just basically same as `copy`
> Implemented view for Index & MultiIndex

- README.md
We can have Apache 2.0 license badge :D
> Added Apache 2.0 license badge

- README.md
Reverts databricks/koalas#1799
> Revert "Added Apache 2.0 license badge"

- databricks/koalas/indexes.py
This is a follow-up of #1761 to address comments on https://github.com/databricks/koalas/pull/1761#pullrequestreview-497790324.
> Cleanup of refining Index constructor.

- databricks/koalas/frame.py
- databricks/koalas/groupby.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_indexing.py
- databricks/koalas/utils.py
Fixes the input check in `DataFrame`.
> Fix the input check in DataFrame.

- databricks/koalas/indexes.py
- databricks/koalas/tests/test_indexes.py
- docs/source/getting_started/install.rst
- requirements-dev.txt
- setup.py
> Remove upper bounds for numpy.

- databricks/koalas/strings.py
Rewrite Series.str.repeat to use SF.repeat function for better performance. No behavior change is introduced.
> Rewrite Series.str.repeat to use SF.repeat function

- databricks/koalas/namespace.py
Remove "pandas objects" from docstrings of `read_json` and `concat`.
> Update the docstring of `read_json` and `concat`

- databricks/koalas/groupby.py
- databricks/koalas/internal.py
- databricks/koalas/ml.py
- databricks/koalas/namespace.py
- databricks/koalas/series.py
- databricks/koalas/utils.py
Fixes type annotations.
After ##1784, those should accept non-string tuples.
> Fix type annotations.

- databricks/koalas/frame.py
- databricks/koalas/tests/test_dataframe.py
> DataFrame.reindex supports named columns index

- databricks/koalas/__init__.py
- databricks/koalas/accessors.py
- databricks/koalas/base.py
- databricks/koalas/frame.py
- databricks/koalas/generic.py
- databricks/koalas/indexing.py
- databricks/koalas/window.py
Fixes type hints for older Python 3.5.
> Fix type hints for older Python 3.5.

- docs/source/getting_started/install.rst
Self-contained description in the changes.
> Add a note about Koalas to be used in Spark's driver side

- docs/source/user_guide/types.rst
Update the data type doc a bit.
> Update the data type doc.

- databricks/koalas/frame.py
Some tests are testing with pandas DataFrame.
Fixed it to Koalas DataFrame properly.
> Fix some doctests in frame.py

- docs/source/getting_started/videos_blogs.rst
Adds videos from Data+AI Summit 2020 EUROPE:
- https://databricks.com/dataaisummit/europe-2020/keynotes
- https://databricks.com/session_eu20/koalas-interoperability-between-koalas-and-apache-spark
> Add videos from Data+AI Summit 2020 EUROPE.

- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
- databricks/koalas/tests/plot/test_frame_plot.py
- databricks/koalas/tests/plot/test_frame_plot_matplotlib.py
- databricks/koalas/tests/plot/test_series_plot_matplotlib.py
This PR extract histogram calculation logic from `matplotlib.py` to `core.py`.
This PR is dependent on https://github.com/databricks/koalas/pull/1997
> Extract histogram calculation logic from matplotlib to plot core

- databricks/koalas/plot/core.py
- databricks/koalas/plot/matplotlib.py
- databricks/koalas/tests/plot/test_series_plot.py
- databricks/koalas/tests/plot/test_series_plot_matplotlib.py
This PR moves core computation logic from matplotlib module to core module in plot.
> Extract box computing logic from matplotlib

- requirements-dev.txt
- setup.py
Set upperbound for pandas 1.2.0 before we fully support pandas 1.2.0
refer https://github.com/databricks/koalas/pull/1987
> Set upperbound for pandas 1.2.0

- README.md
- docs/source/getting_started/10min.ipynb
> Add a note about Databricks Community Edition

- databricks/koalas/frame.py
- databricks/koalas/missing/frame.py
- databricks/koalas/missing/series.py
- databricks/koalas/series.py
- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_ops_on_diff_frames.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/utils.py
- docs/source/reference/frame.rst
- docs/source/reference/series.rst
Add `DataFrame/Series.align` with parameters `join`, `axis`, and `copy` supported.
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.align.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.align.html
> Add DataFrame/Series.align.

- databricks/koalas/tests/test_dataframe.py
- databricks/koalas/tests/test_series.py
- databricks/koalas/typedef/typehints.py
> Use NullType for empty or null dataset.

- dev/gendoc.py
https://github.com/bebraw/pypandoc/pull/154 is merged and released. We can remove the hack for file name handling
> Remove pypandoc hack when downloading pandoc

- databricks/koalas/missing/indexes.py
Add some more missing functions to `DatatimeIndex`.
- `indexer_at_time`
- `indexer_between_time`
> Add some more missing functions to DatatimeIndex.

- databricks/koalas/__init__.py
- docs/source/getting_started/install.rst
Shows a warning message when Python 3.5.
> Show a warning message when Python 3.5.

- docs/source/user_guide/typehints.rst
This PR proposes to add a more correct note about the current status of typing in Koalas.
> Add a note about variadic generics in Koalas

- databricks/koalas/groupby.py
- databricks/koalas/internal.py
- databricks/koalas/tests/test_categorical.py
- databricks/koalas/typedef/typehints.py
Reuse the conversion logic in `InternalFrame.from_pandas` and `InternalFrame.to_pandas_frame` in groupby-apply.
> Reuse conversion from/to pandas DataFrame in groupby-apply.

- databricks/koalas/frame.py
We can reuse `Series.koalas._transform_batch` in `DataFrame.transform`.
> Reuse Series.koalas._transform_batch in DataFrame.transform.

- databricks/koalas/tests/test_categorical.py
Fix `test_frame_apply_batch_without_shortcut` which could be flaky.
> Fix test_frame_apply_batch_without_shortcut.

- databricks/koalas/generic.py
Add notes for tabulate in docstring of to_markdown, following pandas.
> Add notes for tabulate in docstring of to_markdown
